// Module 10 — Exam Prep & Capstone
export const MODULE_10 = [
  {
    id: 'L82',
    module: 'Exam & Capstone',
    moduleNum: 10,
    title: 'TCP exam strategy',
    duration: 7,
    hook: "The Tridium Certified Professional exam is the credential that proves your Niagara skill. Knowing the exam — not just the material — is half the battle.",
    content: [
      { type: 'h3', text: 'What TCP is' },
      { type: 'p', text: 'TCP (Tridium Certified Professional) certifies competence in Niagara N4. It typically follows instructor-led training and is the recognized baseline credential for Niagara engineers.' },
      { type: 'h3', text: 'What it tests' },
      { type: 'bullets', items: [
        'Niagara architecture — stations, hosts, Platform versus Station (Module 6)',
        'Drivers and device discovery, proxy points',
        'Wire sheet logic, points and extensions',
        'Schedules, alarms, histories',
        'Graphics (PX) and bindings',
      ]},
      { type: 'h3', text: 'Exam strategy' },
      { type: 'bullets', items: [
        'Know the vocabulary precisely — many questions hinge on exact terms (module vs palette, Platform vs Station)',
        'Watch for EXCEPT and NOT questions — read every word',
        'Manage time — flag hard questions and return to them',
        'Eliminate the obviously wrong options first',
      ]},
      { type: 'callout', text: 'Recurring exam trap: confusing terms that sound similar — module vs palette, Platform vs Station, proxy point vs extension. If you can define each crisply in one sentence, you have defused most of the trick questions before they are asked.' },
    ],
    quiz: [
      { q: 'TCP certifies competence primarily in:', options: ['Modbus', 'Niagara N4', 'BACnet wiring', 'Chiller design'], correct: 1 },
      { q: 'A good multiple-choice strategy is to:', options: ['Answer instantly', 'Eliminate obviously wrong options and watch for NOT/EXCEPT wording', 'Skip reading the question', 'Always pick the longest answer'], correct: 1 },
      { q: 'A common TCP trap is confusing:', options: ['Hot and cold', 'Similar-sounding terms like Platform vs Station', 'Numbers', 'Colours'], correct: 1 },
    ],
    takeaway: 'The TCP exam certifies Niagara N4 skill across architecture, drivers, wire sheets, points, schedules, alarms, and graphics. Know the exact vocabulary and watch for NOT/EXCEPT wording.',
  },
  {
    id: 'L83',
    module: 'Exam & Capstone',
    moduleNum: 10,
    title: 'TCP-style mock exam',
    duration: 15,
    hook: "A timed mock exam across the whole course. Treat it like the real thing — no notes, no PID Lab, no tutor. Pass at 75%.",
    content: [
      { type: 'h3', text: 'Mock exam' },
      { type: 'p', text: 'Ten questions spanning Modules 1 to 9 — foundations, HVAC controls, protocols, field devices, architecture, Niagara, design, commissioning, and specialties.' },
      { type: 'p', text: 'Pass at 75% (8 of 10). If you do not pass, the questions you missed go into spaced repetition — review them and come back.' },
      { type: 'callout', text: 'Sit it honestly: no looking back at lessons. The point of a mock is to find your weak spots while it is still cheap to find them.' },
    ],
    quiz: [
      { q: 'If the supervisor goes offline, a well-designed building:', options: ['Stops completely', 'Keeps running from its field controllers', 'Enters fire mode', 'Loses all data'], correct: 1 },
      { q: 'A PID loop oscillating around setpoint should first be fixed by:', options: ['Increasing P', 'Decreasing P', 'Increasing D heavily', 'Switching to on/off'], correct: 1 },
      { q: 'In a humid coastal climate, economizer changeover should use:', options: ['Fixed dry-bulb', 'Enthalpy (total heat)', 'A timer', 'CO2'], correct: 1 },
      { q: 'BACnet/IP cross-subnet discovery requires a correctly configured:', options: ['BBMD per subnet', 'Faster switch', 'VPN', 'Terminator'], correct: 0 },
      { q: 'A Modbus value reading as nonsense though comms are fine is most likely:', options: ['A dead sensor', 'Wrong byte/word order (endianness)', 'A wrong port', 'A missing terminator'], correct: 1 },
      { q: 'Coil control valves are almost always:', options: ['Quick-opening', 'Linear', 'Equal-percentage', 'Ball valves'], correct: 2 },
      { q: 'The running Niagara application is the:', options: ['Host', 'Station', 'Workbench', 'Module'], correct: 1 },
      { q: 'A good SOO line always names a controlled element, a target, and a:', options: ['Brand', 'Tolerance or condition', 'Price', 'Colour'], correct: 1 },
      { q: 'Functional performance testing proves:', options: ['Each point', 'Each sequence and mode from the SOO', 'The BOQ', 'Cable lengths'], correct: 1 },
      { q: 'FDD exists mainly to catch:', options: ['Cable faults', 'Silent performance drift after commissioning', 'Fire alarms', 'Power cuts'], correct: 1 },
    ],
    takeaway: 'A mock exam finds your weak spots cheaply. Missed questions feed straight into spaced repetition — review and re-attempt until you pass comfortably.',
    isBoss: true,
  },
  {
    id: 'L84',
    module: 'Exam & Capstone',
    moduleNum: 10,
    title: 'Capstone brief',
    duration: 8,
    hook: "Everything so far has been practice. The capstone is the real deliverable: design the BMS for a building, end to end. Here is the brief.",
    content: [
      { type: 'h3', text: 'The project' },
      { type: 'p', text: 'A 3-floor commercial office building in Accra. Each floor is roughly 800 square metres, open-plan with some cellular offices and meeting rooms.' },
      { type: 'h3', text: 'The systems' },
      { type: 'bullets', items: [
        'Two AHUs — one serving floors 1 and 2, one serving floor 3 — with VAV distribution and reheat',
        'A chilled water plant — two chillers, primary-secondary pumping, a cooling tower',
        'VRF serving the ground-floor retail units, integrated via a gateway',
        'Tenant electrical sub-metering per floor',
        'A standby generator with a BMS load-shed interface',
      ]},
      { type: 'h3', text: 'Your deliverables (next lessons)' },
      { type: 'bullets', items: [
        'A **point list** for the AHUs and the chilled water plant',
        'A **Sequence of Operation** for one AHU and the chilled water plant',
        'A **BOQ** structure with the major cost lines',
      ]},
      { type: 'callout', text: 'Approach the capstone exactly as a real Yakuver job. The point of the exercise is not a perfect answer — it is rehearsing the full design workflow, from scope to priced deliverable, so the first paid job is not the first time you do it.' },
    ],
    quiz: [
      { q: 'The capstone building is:', options: ['A 30-floor tower', 'A 3-floor Accra office with AHUs, chilled water, VRF, and metering', 'A single room', 'A factory'], correct: 1 },
      { q: 'The capstone deliverables are a point list, a BOQ, and a:', options: ['Marketing plan', 'Sequence of Operation', 'Lease agreement', 'Floor plan'], correct: 1 },
      { q: 'The main purpose of the capstone is to:', options: ['Get a perfect score', 'Rehearse the full real design workflow end to end', 'Test typing speed', 'Memorize the brief'], correct: 1 },
    ],
    takeaway: 'The capstone is a full BMS design for a 3-floor Accra office — AHUs, chilled water plant, VRF, sub-metering, generator interface. Deliverables: point list, SOO, BOQ. Treat it like a real job.',
  },
  {
    id: 'L85',
    module: 'Exam & Capstone',
    moduleNum: 10,
    title: 'Capstone — point list & SOO',
    duration: 10,
    hook: "Two of the three capstone deliverables — the point list and the SOO — are the heart of the design. Here is how to attack them.",
    content: [
      { type: 'h3', text: 'Building the point list' },
      { type: 'bullets', items: [
        'Start from your AHU template (around 30 points) and apply it to both AHUs',
        'Add the chilled water plant — chillers (status, fault, control via BACnet), pumps (VFD speed, status), CHW supply/return temps, flow, cooling tower',
        'Add VAV boxes — airflow, zone temp, reheat valve, damper per box',
        'Separate physical points (I/O) from software points (setpoints, modes, alarms)',
        'Total it, add 20% spare, and size the controllers',
      ]},
      { type: 'h3', text: 'Writing the SOO' },
      { type: 'bullets', items: [
        'One section for the AHU — modes, SAT control (sequenced coils, deadband), economizer (enthalpy for coastal Accra), static pressure reset, safeties, fire mode',
        'One section for the chilled water plant — staging, lead/lag rotation, CHW temperature reset, minimum-flow protection',
        'Every line testable — a controlled element, a target, and a tolerance',
      ]},
      { type: 'h3', text: 'Self-check' },
      { type: 'p', text: 'Cross-check: does every control action in the SOO have the points it needs on the point list? A sequence that commands a valve the point list does not include is a gap — find it now, not in commissioning.' },
      { type: 'callout', text: 'This cross-check — SOO against point list — is exactly the discipline that separates a clean job from a messy one. The two documents must be mutually consistent: every controlled thing in the SOO appears on the point list, and every point has a reason to exist.' },
    ],
    quiz: [
      { q: 'A good starting point for the capstone AHU point list is:', options: ['A blank page', 'Your reusable roughly 30-point AHU template', 'A competitor’s invoice', 'The BOQ'], correct: 1 },
      { q: 'For an economizer in coastal Accra, the SOO should specify changeover on:', options: ['Fixed dry-bulb', 'Enthalpy', 'A timer', 'CO2'], correct: 1 },
      { q: 'The key cross-check between the SOO and the point list is that:', options: ['They use the same font', 'Every control action in the SOO has the points it needs on the list', 'They are the same length', 'Neither mentions setpoints'], correct: 1 },
    ],
    takeaway: 'Build the capstone point list from reusable templates (AHU, plant, VAV), separate physical and software points, add spare. Write a testable SOO, then cross-check: every SOO control action must have its points on the list.',
  },
  {
    id: 'L86',
    module: 'Exam & Capstone',
    moduleNum: 10,
    title: 'Capstone — BOQ & review',
    duration: 9,
    hook: "The final capstone deliverable turns the design into a defensible number — and then you assess your own work against the standard of a real BMS engineer.",
    content: [
      { type: 'h3', text: 'Structuring the BOQ' },
      { type: 'bullets', items: [
        '**Hardware** — controllers (sized from the point list plus 20%), sensors, valves, actuators, panels, network gear, cabling',
        '**Software & licensing** — Niagara licences sized to the point count, graphics, drivers',
        '**Labour** — design, installation, programming, commissioning, project management',
        '**Ghana factors** — import duties, currency contingency, UPS and generator interface, freight',
      ]},
      { type: 'h3', text: 'Sanity-checking the number' },
      { type: 'p', text: 'Cross-check with the dollar-per-point rule of thumb from Module 1 — roughly 300 to 800 dollars per point all-in. If your detailed BOQ lands wildly outside that band, find out why before it goes to a client.' },
      { type: 'h3', text: 'Self-assessment rubric' },
      { type: 'bullets', items: [
        'Is every system in scope covered, with exclusions stated?',
        'Is the point list complete, consistent, and sized with spare?',
        'Is the SOO fully testable — element, target, tolerance on every line?',
        'Does the BOQ cover hardware, software, labour, and Ghana factors?',
        'Use the Ask the Tutor button to review your capstone and pressure-test your decisions',
      ]},
      { type: 'callout', text: 'Grade yourself honestly against the rubric — then use the AI tutor as a reviewer: paste your SOO or point list logic and ask it to find gaps, challenge assumptions, and apply Ghana context. That feedback loop is how the capstone actually levels you up.' },
    ],
    quiz: [
      { q: 'Niagara software licensing in the capstone BOQ should be sized to:', options: ['The number of floors', 'The point count', 'The number of staff', 'Nothing'], correct: 1 },
      { q: 'A good sanity check on the total BOQ is the Module 1 rule of thumb of roughly:', options: ['10 to 50 dollars per point', '300 to 800 dollars per point all-in', '5,000 dollars per point', '50,000 dollars per point'], correct: 1 },
      { q: 'The best use of the AI tutor on the capstone is to:', options: ['Write it for you', 'Review your work — find gaps and challenge assumptions', 'Grade other students', 'Nothing'], correct: 1 },
    ],
    takeaway: 'The capstone BOQ covers hardware, software/licensing, labour, and Ghana factors — sanity-checked against 300 to 800 dollars per point. Self-assess against the rubric and use the AI tutor as a reviewer.',
  },
  {
    id: 'L87',
    module: 'Exam & Capstone',
    moduleNum: 10,
    title: 'Graduation',
    duration: 6,
    hook: "Eighty-six lessons. From 'what is a BMS' to designing one end to end. This last lesson is about where you take it from here.",
    content: [
      { type: 'h3', text: 'What you have built' },
      { type: 'p', text: 'You have moved from zero BMS knowledge to an engineer who can read a building as a control problem, talk protocols, design point lists and sequences, understand Niagara, commission a system, and price a job. That is genuine expert-adjacent ground.' },
      { type: 'h3', text: 'Turning knowledge into mastery' },
      { type: 'bullets', items: [
        '**Get hands on Niagara** — download Workbench, build a demo station, sit the TCP exam',
        '**Read real documents** — get hold of actual point lists, SOOs, and ASHRAE Guideline 36, and read them critically',
        '**Apply it on a Yakuver job** — scope and bid real BMS work; the first real project teaches what no course can',
        '**Keep the flashcards alive** — spaced repetition only works if you keep reviewing',
      ]},
      { type: 'h3', text: 'Specialization paths' },
      { type: 'bullets', items: [
        '**Niagara integration specialist** — deep N4, multi-vendor integration',
        '**Energy & analytics** — FDD, M&V, optimization: the recurring-revenue layer',
        '**Design & commissioning lead** — own the SOO and the commissioning process end to end',
      ]},
      { type: 'callout', text: 'The real goal was never the certificate — it was confidence. You can now sit in a client meeting, scope BMS work, and back yourself. Build the BMS portfolio for Yakuver, take on the work, and let real projects turn this knowledge into mastery.' },
    ],
    quiz: [
      { q: 'The recommended way to turn this course knowledge into real mastery is to:', options: ['Stop here', 'Get hands-on with Niagara and apply it on real projects', 'Re-read the lessons only', 'Forget it'], correct: 1 },
      { q: 'Spaced-repetition flashcards keep working only if you:', options: ['Delete them', 'Keep reviewing them over time', 'Pass once and stop', 'Ignore them'], correct: 1 },
      { q: 'The energy & analytics specialization path is notable for being:', options: ['Hardware-only', 'The recurring-revenue layer — FDD, M&V, optimization', 'Unrelated to BMS', 'Exam-only'], correct: 1 },
    ],
    takeaway: 'You have reached expert-adjacent BMS knowledge end to end. Turn it into mastery with hands-on Niagara, the TCP exam, real Yakuver projects, and ongoing flashcard review.',
  },
];
