// Module 9 — Specialties
export const MODULE_9 = [
  {
    id: 'L73',
    module: 'Specialties',
    moduleNum: 9,
    title: 'Analytics & FDD — why it matters',
    duration: 7,
    hook: "Installing a BMS is a one-off sale. The building then runs for thirty years — and quietly drifts out of tune. Analytics and fault detection are how you, and the building, win the long game.",
    content: [
      { type: 'h3', text: 'The operating-phase problem' },
      { type: 'p', text: 'A building is commissioned perfectly once. Then sensors drift, setpoints get nudged, overrides are left in, and equipment ages. Within a year or two, performance has decayed — invisibly, because nothing has obviously broken.' },
      { type: 'h3', text: 'What analytics & FDD do' },
      { type: 'bullets', items: [
        '**FDD** means Fault Detection and Diagnostics — software that continuously analyses BMS data for faults and inefficiencies',
        'It catches the silent failures: simultaneous heating and cooling, stuck dampers, overridden points, schedules left running',
        'It turns the BMS from a control system into a continuous-improvement system',
      ]},
      { type: 'h3', text: 'The business case' },
      { type: 'p', text: 'FDD is the bridge from a one-off installation to recurring revenue — monitoring-based commissioning, performance contracts, managed services. It is also where buildings actually keep their promised energy savings.' },
      { type: 'callout', text: 'For Yakuver, FDD reframes the offer: not “we install a BMS” but “we keep your building performing.” That is a recurring-revenue relationship — and the data to do it is already flowing through the BMS you installed.' },
    ],
    quiz: [
      { q: 'FDD stands for:', options: ['Field Device Data', 'Fault Detection and Diagnostics', 'Fast Damper Drive', 'Final Design Document'], correct: 1 },
      { q: 'The core problem FDD addresses is that a commissioned building:', options: ['Stays perfect forever', 'Silently drifts out of tune over months and years', 'Cannot be measured', 'Has no data'], correct: 1 },
      { q: 'FDD reframes a BMS business from one-off installation toward:', options: ['No revenue at all', 'Recurring revenue — keeping buildings performing', 'Selling hardware only', 'Less work'], correct: 1 },
    ],
    takeaway: 'Buildings silently drift out of tune after commissioning. FDD (Fault Detection and Diagnostics) continuously analyses BMS data for faults — turning a one-off install into a recurring keep-it-performing service.',
  },
  {
    id: 'L74',
    module: 'Specialties',
    moduleNum: 9,
    title: 'Rule-based vs ML FDD',
    duration: 7,
    hook: "Fault detection comes in two flavours: explicit rules you write, and machine learning that finds patterns. Knowing which to trust where keeps you honest about what FDD really delivers.",
    content: [
      { type: 'h3', text: 'Rule-based FDD' },
      { type: 'bullets', items: [
        'You or the platform write explicit logical rules — if heating valve open AND cooling valve open, flag simultaneous heating and cooling',
        'Transparent, explainable, predictable — you know exactly why it fired',
        'Covers the well-known faults very well; needs a human to author the rules',
      ]},
      { type: 'h3', text: 'ML-based FDD' },
      { type: 'bullets', items: [
        'Learns normal behaviour from data, then flags anomalies',
        'Can surface unexpected or subtle issues no rule anticipated',
        'Less transparent — an anomaly flag is not the same as a diagnosed cause',
      ]},
      { type: 'h3', text: 'In practice' },
      { type: 'p', text: 'Most real platforms lead with a strong rule library — the common faults are well understood — and add ML for anomaly detection on top. Rules give you the diagnosis; ML widens the net. Common platforms include SkySpark, Clockworks, and Switch Automation, all of which ingest BMS data (well-tagged data, recall Module 6).' },
      { type: 'callout', text: 'Be precise with clients: rule-based FDD tells you what is wrong and why; ML anomaly detection tells you something looks unusual. Both are useful — overselling ML as automatic diagnosis erodes trust when the “fault” turns out to be a hot day.' },
    ],
    quiz: [
      { q: 'Rule-based FDD is characterized by:', options: ['Hidden logic', 'Explicit, explainable rules a human authors', 'No rules at all', 'Only machine learning'], correct: 1 },
      { q: 'ML-based FDD mainly adds the ability to:', options: ['Write rules', 'Surface unexpected anomalies no rule anticipated', 'Replace the BMS', 'Tag points'], correct: 1 },
      { q: 'Most FDD platforms in practice:', options: ['Use only ML', 'Lead with a rule library and add ML for anomalies', 'Use neither', 'Need no data'], correct: 1 },
    ],
    takeaway: 'Rule-based FDD uses explicit, explainable rules for known faults; ML-based FDD flags unanticipated anomalies. Real platforms (SkySpark, Clockworks, Switch) combine both — rules diagnose, ML widens the net.',
  },
  {
    id: 'L75',
    module: 'Specialties',
    moduleNum: 9,
    title: 'Cybersecurity — the BMS threat landscape',
    duration: 7,
    hook: "A BMS used to be an island. Now it is on the network, in the cloud, and remotely accessible — which means it is a target. BMS cybersecurity is no longer optional knowledge.",
    content: [
      { type: 'h3', text: 'Why BMS is a target' },
      { type: 'bullets', items: [
        'It is OT — controlling physical plant; an attack can disrupt a real building',
        'It is often poorly secured — default passwords, flat networks, old firmware',
        'It can be a **pivot point** — a way into the wider corporate network (a famous retail breach started through an HVAC vendor’s access)',
      ]},
      { type: 'h3', text: 'The common weaknesses' },
      { type: 'bullets', items: [
        'Default or shared credentials never changed',
        'BMS on a flat network with everything else — no segmentation',
        'Unpatched controllers and supervisors',
        'Remote access left wide open — exposed to the internet, no VPN, no MFA',
        'Protocols with no built-in security (classic BACnet, Modbus)',
      ]},
      { type: 'callout', text: 'The single highest-impact, lowest-cost security action on any BMS: change every default password and never share credentials. It sounds trivial; it is also how a large share of real BMS compromises happen. Do it on every job, without exception.' },
    ],
    quiz: [
      { q: 'A BMS is an attractive cyber target partly because it can be a:', options: ['Backup server', 'Pivot point into the wider corporate network', 'Printer', 'Database'], correct: 1 },
      { q: 'Which is a common BMS security weakness?', options: ['Strong unique passwords', 'Default or shared credentials never changed', 'Network segmentation', 'Multi-factor auth'], correct: 1 },
      { q: 'The highest-impact, lowest-cost BMS security action is:', options: ['Buy new hardware', 'Change every default password and never share credentials', 'Add graphics', 'Disable alarms'], correct: 1 },
    ],
    takeaway: 'A networked BMS is an OT attack target and a pivot into corporate networks. Common weaknesses: default passwords, flat networks, unpatched gear, open remote access. Changing default credentials is the cheapest big win.',
  },
  {
    id: 'L76',
    module: 'Specialties',
    moduleNum: 9,
    title: 'Securing the BMS',
    duration: 8,
    hook: "Knowing the threats is half the job. The other half is the concrete defences — and they layer into a practical hardening checklist you can apply to every project.",
    content: [
      { type: 'h3', text: 'Network defences' },
      { type: 'bullets', items: [
        '**Segmentation** — BMS on its own VLAN or network behind a firewall (Module 5)',
        '**No direct internet exposure** — remote access only via VPN, with multi-factor authentication',
        'Lock down switch ports and disable unused services',
      ]},
      { type: 'h3', text: 'Secure protocols & systems' },
      { type: 'bullets', items: [
        '**BACnet/SC (Secure Connect)** — the secure BACnet variant: encrypted, authenticated, firewall-friendly. The direction of travel for new work.',
        'Keep controllers and supervisors patched',
        '**Harden Niagara** — change defaults, use strong per-user accounts and roles, enable TLS, follow the vendor hardening guide',
      ]},
      { type: 'h3', text: 'People & process' },
      { type: 'bullets', items: [
        'Unique accounts per person, least-privilege roles, remove leavers’ access promptly',
        'Logging and audit trails — know who changed what',
        '**ISA/IEC 62443** — the recognized standard framework for OT and industrial control system security',
      ]},
      { type: 'callout', text: 'Security is layered — no single control is enough. Segmentation, secure protocols, patching, hardened Niagara, account discipline, and logging together make a BMS genuinely hard to attack. Treat a hardening checklist as a standard deliverable, not an extra.' },
    ],
    quiz: [
      { q: 'The secure, encrypted, authenticated variant of BACnet is:', options: ['BACnet MS/TP', 'BACnet/SC (Secure Connect)', 'BACnet/IP', 'Modbus'], correct: 1 },
      { q: 'BMS remote access should be:', options: ['Open to the internet', 'Via VPN with MFA, never directly internet-exposed', 'Password-free', 'Disabled entirely'], correct: 1 },
      { q: 'The recognized standard framework for OT and control-system security is:', options: ['ISO 9001', 'ISA/IEC 62443', 'IEEE 802.11', 'ASHRAE 90.1'], correct: 1 },
    ],
    takeaway: 'Harden a BMS in layers: network segmentation, VPN plus MFA remote access, BACnet/SC, patching, hardened Niagara, per-user least-privilege accounts, and logging — guided by ISA/IEC 62443.',
  },
  {
    id: 'L77',
    module: 'Specialties',
    moduleNum: 9,
    title: 'Smart metering & sub-metering',
    duration: 7,
    hook: "You cannot improve what you do not measure, and you cannot bill what you do not meter. A metering strategy turns a BMS into an energy-accountability platform.",
    content: [
      { type: 'h3', text: 'Why sub-meter' },
      { type: 'bullets', items: [
        'A single utility meter tells you the building’s total — and nothing about where it goes',
        '**Sub-metering** breaks consumption down — by tenant, by floor, by system (HVAC, lighting, plant)',
        'That enables tenant billing, accountability, and targeted efficiency work',
      ]},
      { type: 'h3', text: 'Designing a metering strategy' },
      { type: 'bullets', items: [
        'Decide the granularity — what do you need to see and bill separately?',
        'Choose the right meter class — monitoring-grade vs revenue-grade (Module 4)',
        'Integrate meters into the BMS (pulse, Modbus, or BACnet) so the data is trended and reported',
        'Energy/BTU meters for thermal, electrical meters for power',
      ]},
      { type: 'h3', text: 'From data to value' },
      { type: 'p', text: 'Metering data feeds dashboards, M&V (next lesson), tenant bills, and FDD. Without sub-metering, "the building uses too much energy" can never become "this floor’s AHU is the problem."' },
      { type: 'callout', text: 'In Ghana, tenant sub-metering and cost allocation is a strong, concrete BMS upsell — landlords want fair billing and tenants want to see their own usage. Just remember the Module 4 rule: bill only from revenue-grade meters.' },
    ],
    quiz: [
      { q: 'Sub-metering exists to:', options: ['Replace the utility meter', 'Break total consumption down by tenant, floor, or system', 'Save cable', 'Reduce sensors'], correct: 1 },
      { q: 'Meter data integrated into the BMS feeds all of these EXCEPT:', options: ['Dashboards', 'M&V', 'Tenant bills', 'The fire alarm sequence'], correct: 3 },
      { q: 'To bill tenants from sub-meters you must use:', options: ['Any meter', 'Revenue-grade meters', 'Only BTU meters', 'Pulse meters only'], correct: 1 },
    ],
    takeaway: 'Sub-metering breaks total energy down by tenant, floor, and system — enabling billing, accountability, and FDD. Design the granularity and meter class deliberately; bill only from revenue-grade meters.',
  },
  {
    id: 'L78',
    module: 'Specialties',
    moduleNum: 9,
    title: 'M&V and energy benchmarking',
    duration: 8,
    hook: "A client asks: did the BMS actually save what you promised? Measurement and Verification is the discipline that answers that honestly — and protects you when the answer is yes.",
    content: [
      { type: 'h3', text: 'What M&V is' },
      { type: 'p', text: 'M&V (Measurement and Verification) is the structured process of proving energy savings: establish a baseline, make the change, then measure the difference — adjusting fairly for things outside the BMS’s control.' },
      { type: 'h3', text: 'The adjustment problem' },
      { type: 'bullets', items: [
        'You cannot just compare last year’s bill to this year’s — weather, occupancy, and tenant changes differ',
        'M&V normalizes for these — for example adjusting for cooling degree days so a hotter year is not mistaken for a worse BMS',
        'The recognized framework is **IPMVP** — the International Performance Measurement and Verification Protocol',
      ]},
      { type: 'h3', text: 'Benchmarking' },
      { type: 'p', text: 'Benchmarking compares a building’s energy intensity — kWh per square metre per year — against similar buildings, or against itself over time. It tells you whether there is a problem worth chasing, the starting question before any optimization.' },
      { type: 'callout', text: 'M&V cuts both ways and that is its strength: it stops a client wrongly blaming the BMS for a hot-year bill increase, and it stops you overclaiming savings you cannot defend. Honest, normalized numbers build the trust that wins the next contract.' },
    ],
    quiz: [
      { q: 'M&V proves energy savings by comparing against a baseline while:', options: ['Ignoring weather', 'Normalizing for factors outside the BMS’s control, like weather and occupancy', 'Using last year’s bill directly', 'Guessing'], correct: 1 },
      { q: 'The recognized M&V framework is:', options: ['IPMVP', 'BACnet', 'ISO 9001', 'Guideline 36'], correct: 0 },
      { q: 'Energy benchmarking (kWh per square metre per year) is mainly used to:', options: ['Bill tenants', 'Tell whether there is a problem worth investigating', 'Replace metering', 'Tune PID loops'], correct: 1 },
    ],
    takeaway: 'M&V proves savings against a normalized baseline (adjusting for weather, occupancy) using the IPMVP framework. Benchmarking energy intensity tells you whether a problem is worth chasing. Honest numbers build trust.',
  },
  {
    id: 'L79',
    module: 'Specialties',
    moduleNum: 9,
    title: 'Ghana energy — tariffs, load shifting, solar',
    duration: 8,
    hook: "Energy strategy in Ghana is its own discipline — shaped by tariff structures, unreliable grid power, and a strong case for solar. A BMS is the tool that exploits all three.",
    content: [
      { type: 'h3', text: 'Tariffs and demand' },
      { type: 'bullets', items: [
        'Commercial **ECG tariffs** include energy charges and often **demand charges**, billed on your peak kW',
        'Shaving that peak — staggering plant starts, limiting simultaneous loads — directly cuts the demand charge',
        'A BMS is what executes peak-shaving and load-shedding logic automatically',
      ]},
      { type: 'h3', text: 'Generators and load shifting' },
      { type: 'bullets', items: [
        'Grid instability means generator running is common — and diesel power is expensive per kWh',
        'On generator, the BMS can shed non-critical load to stay within generator capacity',
        '**Load shifting** — moving flexible loads (pre-cooling, thermal storage) to cheaper or more available periods',
      ]},
      { type: 'h3', text: 'Solar PV + BMS' },
      { type: 'bullets', items: [
        'Solar PV is increasingly attractive in Ghana’s strong sun',
        'A BMS can align flexible loads with solar generation — run more plant when the PV is producing',
        'It also monitors and verifies PV output (M&V again)',
      ]},
      { type: 'callout', text: 'The Ghana energy pitch for a BMS is concrete and local: cut the ECG demand charge, run safely and economically on generator, and make the most of solar. These are cedi-denominated savings a client can feel — lead with them.' },
    ],
    quiz: [
      { q: 'An ECG commercial demand charge is billed on:', options: ['Total energy only', 'Your peak kW demand', 'The number of meters', 'Floor area'], correct: 1 },
      { q: 'When a building runs on generator, the BMS can:', options: ['Do nothing', 'Shed non-critical load to stay within generator capacity', 'Increase the load', 'Disable safeties'], correct: 1 },
      { q: 'A BMS supports solar PV by:', options: ['Replacing the panels', 'Aligning flexible loads with solar generation and monitoring output', 'Cooling the panels', 'Doing nothing'], correct: 1 },
    ],
    takeaway: 'In Ghana the BMS exploits the tariff structure (shave ECG demand charges), grid instability (shed load on generator, shift flexible loads), and solar (align loads to PV, verify output) — concrete cedi savings.',
  },
  {
    id: 'L80',
    module: 'Specialties',
    moduleNum: 9,
    title: 'Emerging areas',
    duration: 7,
    hook: "The BMS field is not standing still. Four emerging ideas — digital twins, AI optimization, grid-interactive buildings, and the data-product shift — are where the next decade of value sits.",
    content: [
      { type: 'h3', text: 'Digital twins' },
      { type: 'p', text: 'A digital twin is a live virtual model of a building, fed by BMS data. It allows simulation — test a sequence change or an energy strategy virtually before touching the real plant.' },
      { type: 'h3', text: 'AI-driven optimization' },
      { type: 'bullets', items: [
        'Software (BrainBox AI and similar) layers on top of the BMS and continuously optimizes setpoints',
        'It uses weather forecasts, occupancy patterns, and learned building behaviour to act ahead of demand',
        'The BMS still runs the building; the AI tunes it',
      ]},
      { type: 'h3', text: 'Grid-interactive buildings' },
      { type: 'p', text: 'A grid-interactive efficient building does not just consume — it responds to the grid, shedding or shifting load on a signal, even feeding back. The building becomes a flexible grid resource.' },
      { type: 'h3', text: 'The data shift' },
      { type: 'p', text: 'Across all of these the pattern is the same: value is moving from the hardware to the data and the logic layered on top of it. Well-tagged BMS data (Module 6) is the raw material for every emerging product.' },
      { type: 'callout', text: 'The strategic read for Yakuver: hardware installation is the entry point, but the durable value — analytics, AI optimization, grid services, data products — sits in the layer above. Build the data foundation now and you are positioned for what comes next.' },
    ],
    quiz: [
      { q: 'A digital twin is:', options: ['A backup controller', 'A live virtual model of a building fed by BMS data', 'A spare panel', 'A second JACE'], correct: 1 },
      { q: 'AI optimization tools like BrainBox AI typically:', options: ['Replace the BMS entirely', 'Layer on top and optimize setpoints, while the BMS still runs the building', 'Do nothing', 'Act as field sensors'], correct: 1 },
      { q: 'Across emerging BMS areas, value is moving toward:', options: ['The hardware', 'The data and the logic layered on top of it', 'Cabling', 'Panels'], correct: 1 },
    ],
    takeaway: 'Emerging BMS: digital twins (live virtual models), AI optimization (setpoint tuning on top of the BMS), grid-interactive buildings (load as a grid resource). Value is shifting from hardware to data and logic.',
  },
  {
    id: 'L81',
    module: 'Specialties',
    moduleNum: 9,
    title: 'Module 9 boss check',
    duration: 10,
    hook: "End of Module 9 — Specialties. The advanced topics that turn a competent BMS engineer into a strategic one. Let's check it.",
    content: [
      { type: 'h3', text: 'Module 9 recap' },
      { type: 'p', text: 'You covered analytics and FDD, rule-based versus ML fault detection, the BMS cyber threat landscape and how to harden a system, smart and sub-metering, M&V and benchmarking, Ghana energy strategy, and emerging areas.' },
      { type: 'p', text: 'This boss check has 8 questions across all of Module 9. Pass at 75% (6/8) to unlock Module 10 — exam prep and the capstone.' },
      { type: 'callout', text: 'These specialties are where recurring revenue and strategic differentiation live. They are also what take you past pure installation toward owning the value layer.' },
    ],
    quiz: [
      { q: 'FDD continuously analyses BMS data to catch:', options: ['Cable faults only', 'Silent faults and drift the building developed after commissioning', 'Nothing useful', 'Fire alarms'], correct: 1 },
      { q: 'Rule-based FDD differs from ML FDD in that it is:', options: ['Slower', 'Explicit and explainable — you know why it fired', 'Always wrong', 'Hardware'], correct: 1 },
      { q: 'A BMS is an attractive cyber target partly because it can be a pivot into:', options: ['The fire panel', 'The wider corporate network', 'The cooling tower', 'A trend log'], correct: 1 },
      { q: 'The cheapest high-impact BMS security action is:', options: ['Buying new controllers', 'Changing default passwords and not sharing credentials', 'More graphics', 'Disabling alarms'], correct: 1 },
      { q: 'To bill tenants, sub-meters must be:', options: ['Monitoring-grade', 'Revenue-grade', 'Ultrasonic', 'Pulse-only'], correct: 1 },
      { q: 'M&V proves savings by comparing to a baseline that is:', options: ['Last year’s raw bill', 'Normalized for weather and occupancy', 'Ignored', 'Guessed'], correct: 1 },
      { q: 'An ECG commercial demand charge is billed on:', options: ['Total kWh only', 'Peak kW demand', 'Floor area', 'Meter count'], correct: 1 },
      { q: 'Across emerging BMS areas, value is shifting toward:', options: ['Hardware', 'Data and the logic layered on it', 'Cable', 'Panels'], correct: 1 },
    ],
    takeaway: 'Module 9 complete. You understand FDD, cybersecurity, metering, M&V, Ghana energy strategy, and where the field is heading — the strategic layer above pure installation.',
    isBoss: true,
  },
];
