// Module 3 — Protocols Deep Dive
export const MODULE_3 = [
  {
    id: 'L20',
    module: 'Protocols',
    moduleNum: 3,
    title: 'BACnet — devices, objects, properties',
    duration: 7,
    hook: "BACnet is the language 95% of commercial buildings speak. Master its three-word grammar — device, object, property — and you can read any BACnet system on Earth.",
    content: [
      { type: 'h3', text: 'The hierarchy' },
      { type: 'p', text: 'BACnet describes everything as a nested structure. Three levels, top to bottom:' },
      { type: 'bullets', items: [
        '**Device** — one physical controller on the network. Every device has a unique Device Instance number (0 to 4,194,302).',
        '**Object** — a named thing inside a device: a sensor reading, a setpoint, a schedule. One device exposes many objects.',
        '**Property** — an attribute of an object: its present value, its name, its units, its alarm limits.',
      ]},
      { type: 'p', text: 'To read a temperature you address: Device 1001 to Analog Input 3 to Present_Value. That same path works on any vendor’s BACnet device.' },
      { type: 'h3', text: 'Why this matters' },
      { type: 'bullets', items: [
        'The structure is vendor-neutral — a Siemens controller and a Distech controller expose the same object model',
        'An integrator only needs the device instance, object type, object instance, and property name to read or write any point',
        'This is exactly what broke vendor lock-in (recall Module 1)',
      ]},
      { type: 'callout', text: 'The single most useful BACnet property is Present_Value (often abbreviated PV). Reading it gives the live value; writing it (where allowed) commands the point. Around 90% of integration work is reading and writing Present_Value on the right objects.' },
    ],
    quiz: [
      { q: 'In BACnet, a single physical controller on the network is a:', options: ['Object', 'Device', 'Property', 'Service'], correct: 1 },
      { q: 'The live reading of a sensor is held in which property?', options: ['Object_Name', 'Present_Value', 'Units', 'Description'], correct: 1 },
      { q: 'A BACnet Device Instance number must be:', options: ['Any text label', 'Unique across the whole BACnet internetwork', 'The same as the IP address', 'Between 1 and 100'], correct: 1 },
    ],
    takeaway: 'BACnet models everything as Device to Object to Property. Present_Value is the property you read and write most.',
  },
  {
    id: 'L21',
    module: 'Protocols',
    moduleNum: 3,
    title: 'BACnet object types',
    duration: 7,
    hook: "BACnet defines a fixed menu of object types. Knowing the dozen that matter lets you glance at a device and instantly know what it can do.",
    content: [
      { type: 'h3', text: 'The point objects' },
      { type: 'bullets', items: [
        '**AI / AO** — Analog Input / Output: a continuous physical sensor reading or output',
        '**BI / BO** — Binary Input / Output: an on/off physical status or command',
        '**AV / BV** — Analog / Binary Value: software values inside the controller — setpoints, flags, calculated results',
        '**MSV / MSI / MSO** — Multi-State Value/Input/Output: an enumerated state (Off/Low/High, or Occupied/Unoccupied)',
      ]},
      { type: 'h3', text: 'The structural objects' },
      { type: 'bullets', items: [
        '**Device** — the object describing the controller itself',
        '**Schedule** — a time-based object that writes values on a calendar',
        '**Calendar** — a list of special dates (holidays) a Schedule references',
        '**Trend Log** — collects historical samples of a property',
        '**Notification Class** — defines who receives alarms and at what priority',
      ]},
      { type: 'callout', text: 'The AI/AO/BI/BO versus AV/BV distinction trips people up. Physical points wired to terminals are AI/AO/BI/BO. Virtual points (setpoints, logic results, no wire) are AV/BV. If you can touch the wire it is an input/output object; if it only exists in software it is a value object.' },
    ],
    quiz: [
      { q: 'A setpoint that exists only in controller software, with no wire, is best represented as a:', options: ['AI', 'AO', 'AV', 'BI'], correct: 2 },
      { q: 'A point that can be Off, Low, or High is best modelled as a:', options: ['Binary Value', 'Multi-State Value', 'Analog Value', 'Trend Log'], correct: 1 },
      { q: 'Historical samples of a temperature over time are collected by a:', options: ['Calendar', 'Schedule', 'Trend Log', 'Notification Class'], correct: 2 },
    ],
    takeaway: 'BACnet point objects: AI/AO/BI/BO for physical wires, AV/BV/MSV for software values. Structural objects: Device, Schedule, Calendar, Trend Log, Notification Class.',
  },
  {
    id: 'L22',
    module: 'Protocols',
    moduleNum: 3,
    title: 'BACnet services & discovery',
    duration: 8,
    hook: "Objects are the nouns. Services are the verbs — how BACnet devices actually talk. Four services do almost everything.",
    content: [
      { type: 'h3', text: 'The core services' },
      { type: 'bullets', items: [
        '**ReadProperty / ReadPropertyMultiple** — fetch one or many property values',
        '**WriteProperty** — command a property value',
        '**Who-Is / I-Am** — discovery: a device broadcasts Who-Is, every device answers I-Am with its instance number',
        '**COV (Change of Value)** — subscribe once, and the device pushes an update only when the value changes, instead of constant polling',
      ]},
      { type: 'h3', text: 'Polling vs COV' },
      { type: 'p', text: 'Polling means repeatedly asking what the value is now — simple, but it loads the network. COV flips it: the device tells you only when something changes. On a busy network COV dramatically cuts traffic.' },
      { type: 'h3', text: 'The write priority array' },
      { type: 'p', text: 'A commandable object (like an AO) does not have a single writer. It has a 16-level Priority Array. Many sources can write to it; the highest-priority active entry wins. Life-safety sits at the top, manual operator overrides high, normal automation lower.' },
      { type: 'callout', text: 'The Priority Array is why a point sometimes ignores your write — a higher-priority entry is holding it. Always check the priority array before assuming a point or controller is faulty. Relinquishing your write (writing NULL at your level) hands control back down the stack.' },
    ],
    quiz: [
      { q: 'To discover every device on a BACnet network you use:', options: ['ReadProperty', 'Who-Is', 'WriteProperty', 'COV'], correct: 1 },
      { q: 'COV subscriptions reduce network traffic by:', options: ['Compressing the data', 'Pushing updates only on change instead of constant polling', 'Using fiber optic', 'Disabling alarms'], correct: 1 },
      { q: 'Your WriteProperty seems ignored by an AO. The most likely cause:', options: ['The wire is broken', 'A higher-priority entry in the Priority Array is active', 'BACnet is down', 'Wrong units'], correct: 1 },
    ],
    takeaway: 'BACnet verbs: Read/WriteProperty move data, Who-Is/I-Am discover devices, COV pushes changes. Commandable points obey a 16-level Priority Array — highest active level wins.',
  },
  {
    id: 'L23',
    module: 'Protocols',
    moduleNum: 3,
    title: 'BACnet MS/TP',
    duration: 8,
    hook: "BACnet MS/TP is the cheap twisted-pair bus that connects field controllers. It is also where most BACnet troubleshooting nightmares live. Wire it right and it just works for decades.",
    content: [
      { type: 'h3', text: 'What MS/TP is' },
      { type: 'p', text: 'MS/TP means Master-Slave / Token-Passing. It runs BACnet over a single RS-485 twisted pair, daisy-chained between devices. Cheap, robust, slow.' },
      { type: 'h3', text: 'The rules that keep it alive' },
      { type: 'bullets', items: [
        '**Daisy chain only** — device to device to device. No stars, no spurs, no T-taps.',
        '**Terminate both ends** — a 120 ohm resistor at each physical end of the bus, nowhere else',
        '**Unique MAC address** per device on the segment (0 to 127 for masters)',
        '**Same baud rate** on every device (38400 is the common default)',
        'Bias the line at one point, ground the shield at one end only',
      ]},
      { type: 'h3', text: 'Token passing' },
      { type: 'p', text: 'Only the device holding the token may talk. The token passes device to device in a logical ring. A device with a duplicate MAC, or one that drops off, disrupts token passing and slows or stalls the whole segment.' },
      { type: 'callout', text: 'About 80% of MS/TP faults are physical: a star or spur instead of a daisy chain, missing or doubled terminators, a duplicate MAC, or mixed baud rates. Before suspecting software, walk the cable and confirm the topology. A duplicate device instance and a duplicate MAC are different faults — both bite.' },
    ],
    quiz: [
      { q: 'The correct physical topology for an MS/TP bus is:', options: ['Star', 'Daisy chain', 'Ring of stars', 'Mesh'], correct: 1 },
      { q: 'How many 120 ohm terminators belong on a correctly wired MS/TP segment?', options: ['One', 'One at each physical end (two total)', 'One per device', 'None'], correct: 1 },
      { q: 'Two devices share MAC address 5 on one segment. Likely effect:', options: ['Nothing', 'Token-passing disruption slowing or stalling the segment', 'Faster comms', 'Higher voltage'], correct: 1 },
    ],
    takeaway: 'MS/TP is BACnet on one RS-485 pair — daisy-chained, terminated at both ends, unique MACs, matching baud. Most faults are physical wiring, not software.',
  },
  {
    id: 'L24',
    module: 'Protocols',
    moduleNum: 3,
    title: 'BACnet/IP and BBMD',
    duration: 7,
    hook: "When BACnet needs to cross a building or ride the corporate network, it runs over Ethernet as BACnet/IP. One UDP port and one acronym — BBMD — explain why it sometimes mysteriously fails.",
    content: [
      { type: 'h3', text: 'BACnet/IP basics' },
      { type: 'bullets', items: [
        'Runs over standard Ethernet/IP — fast, and reuses existing network cabling',
        'Uses **UDP port 47808** (0xBAC0) by default',
        'Devices on the same IP subnet discover each other with broadcasts',
      ]},
      { type: 'h3', text: 'The broadcast problem' },
      { type: 'p', text: 'BACnet discovery (Who-Is) relies on broadcasts. Routers do not forward broadcasts between subnets. So a device on subnet A cannot see a device on subnet B — even though they can ping each other fine.' },
      { type: 'h3', text: 'BBMD — the fix' },
      { type: 'p', text: 'A BBMD (BACnet Broadcast Management Device) on each subnet forwards broadcasts across the router on behalf of the local devices. There should be exactly one BBMD per subnet, each one knowing the others through its Broadcast Distribution Table (BDT).' },
      { type: 'callout', text: 'The classic BACnet/IP fault: devices ping fine but will not discover each other across subnets. The cause is almost always a missing, misconfigured, or duplicated BBMD. Rule: one BBMD per subnet, never two, and every BBMD’s BDT must list every other BBMD.' },
    ],
    quiz: [
      { q: 'BACnet/IP uses which UDP port by default?', options: ['80', '443', '47808', '502'], correct: 2 },
      { q: 'Because routers do not forward broadcasts, cross-subnet BACnet discovery needs:', options: ['A faster switch', 'A BBMD on each subnet', 'A VPN', 'More cable'], correct: 1 },
      { q: 'How many BBMDs should a single IP subnet have?', options: ['Zero', 'Exactly one', 'One per device', 'As many as possible'], correct: 1 },
    ],
    takeaway: 'BACnet/IP runs on UDP 47808. Cross-subnet discovery needs exactly one BBMD per subnet, each listing the others in its BDT.',
  },
  {
    id: 'L25',
    module: 'Protocols',
    moduleNum: 3,
    title: 'Modbus RTU & TCP',
    duration: 8,
    hook: "Modbus is older, simpler, and even more widespread than BACnet — it is in nearly every chiller, meter, and VFD. It has no self-description at all, which is both its weakness and the reason it never dies.",
    content: [
      { type: 'h3', text: 'Modbus in one breath' },
      { type: 'p', text: 'Modbus is a simple master/slave (now called client/server) protocol. The master asks, the slave answers. There is no discovery and no object names — just numbered registers.' },
      { type: 'bullets', items: [
        '**Modbus RTU** — serial, over RS-485. One master, multiple slaves, each with a unique slave ID (1 to 247).',
        '**Modbus TCP** — the same data model over Ethernet, port **502**. Allows multiple simultaneous masters.',
      ]},
      { type: 'h3', text: 'The four register types' },
      { type: 'bullets', items: [
        '**Coils** — read/write single bits (outputs)',
        '**Discrete Inputs** — read-only single bits (inputs)',
        '**Holding Registers** — read/write 16-bit words (setpoints, most data)',
        '**Input Registers** — read-only 16-bit words (sensor readings)',
      ]},
      { type: 'h3', text: 'Function codes' },
      { type: 'p', text: 'Each operation has a numbered function code — FC03 reads holding registers, FC04 reads input registers, FC06 and FC16 write them. The vendor’s register map document tells you which register holds what — Modbus itself never says.' },
      { type: 'callout', text: 'Modbus has zero self-description. The register map document IS the integration. No map, no integration — chase the vendor for it before you ever quote the job.' },
    ],
    quiz: [
      { q: 'Modbus TCP uses which port?', options: ['47808', '502', '80', '22'], correct: 1 },
      { q: 'A read-only 16-bit sensor value in Modbus is typically a:', options: ['Coil', 'Discrete Input', 'Holding Register', 'Input Register'], correct: 3 },
      { q: 'Unlike BACnet, Modbus has no:', options: ['Registers', 'Self-description or discovery', 'Function codes', 'Slave IDs'], correct: 1 },
    ],
    takeaway: 'Modbus is numbered registers — coils, discrete inputs, holding & input registers — accessed by function codes. RTU is serial, TCP is port 502. You always need the vendor register map.',
  },
  {
    id: 'L26',
    module: 'Protocols',
    moduleNum: 3,
    title: 'Modbus gotchas — the endianness trap',
    duration: 7,
    hook: "Two Modbus devices can be perfectly healthy and still hand you garbage numbers. The reason is endianness — and it is the single most common Modbus integration trap.",
    content: [
      { type: 'h3', text: 'The 32-bit problem' },
      { type: 'p', text: 'A Modbus register is only 16 bits. A floating-point value (like 24.7 degrees) needs 32 bits — two registers. The question: which register holds the high half, and in what byte order? Vendors disagree.' },
      { type: 'h3', text: 'The four combinations' },
      { type: 'bullets', items: [
        'Byte order — big-endian or little-endian within each register',
        'Word order — high word first, or low word first',
        'That is four possible interpretations of the same two registers',
        'Pick wrong and 24.7 might read as 5.3e-12, or a wildly large number',
      ]},
      { type: 'h3', text: 'How to crack it fast' },
      { type: 'bullets', items: [
        'Find a register whose value you already know (a setpoint visible on the device display)',
        'Try the four word/byte-order combinations until that known value reads correctly',
        'Apply the same combination to every 32-bit register from that vendor',
      ]},
      { type: 'callout', text: 'Other Modbus traps: register addresses off by one (the 40001-vs-0 base-address confusion), signed vs unsigned values, and scaling factors (a register reading 247 that means 24.7). Always confirm against a value you can independently verify.' },
    ],
    quiz: [
      { q: 'A 32-bit float in Modbus occupies:', options: ['Half a register', 'One register', 'Two registers', 'Four registers'], correct: 2 },
      { q: 'A temperature reads as a huge nonsense number though comms are fine. Most likely cause:', options: ['Broken sensor', 'Wrong byte/word order (endianness)', 'Wrong port', 'Dead battery'], correct: 1 },
      { q: 'The fastest way to crack the byte order is to:', options: ['Reboot the device', 'Test against a register whose correct value you already know', 'Replace the device', 'Switch to BACnet'], correct: 1 },
    ],
    takeaway: 'Modbus 32-bit values span two registers with four possible byte/word orderings. Calibrate against a known value, then apply that order everywhere. Watch base-address and scaling traps too.',
  },
  {
    id: 'L27',
    module: 'Protocols',
    moduleNum: 3,
    title: 'KNX & DALI',
    duration: 7,
    hook: "Two protocols rule lighting and small-building control: KNX for switches and rooms, DALI for the light fittings themselves. BMS engineers meet them at the gateway.",
    content: [
      { type: 'h3', text: 'KNX' },
      { type: 'bullets', items: [
        'A decentralized protocol common in Europe and the Middle East for lighting, blinds, and room control',
        'Runs mostly on a twisted pair; every device is a peer — no central controller required',
        'Devices link via **group addresses** — a switch and a light share a group address and that is the link',
        'Commissioned with one tool: **ETS** (Engineering Tool Software)',
      ]},
      { type: 'h3', text: 'DALI' },
      { type: 'bullets', items: [
        '**DALI-2** means Digital Addressable Lighting Interface — a dedicated bus for light fittings',
        'Each fitting (driver) gets a digital address — you dim and group fixtures individually in software, no rewiring',
        'It reports back: lamp failure, hours run, energy',
        'One DALI line handles up to 64 control gear addresses',
      ]},
      { type: 'h3', text: 'Where the BMS meets them' },
      { type: 'p', text: 'The BMS rarely speaks KNX or DALI natively. A gateway translates KNX or DALI to BACnet or Modbus, exposing lighting status and control as points the BMS can use.' },
      { type: 'callout', text: 'When scoping lighting integration, the gateway is the critical line item. Confirm exactly which points it exposes — often it gives on/off and level but hides per-fixture fault data. Specify the point exposure, not just “DALI gateway”.' },
    ],
    quiz: [
      { q: 'KNX devices are linked to each other by:', options: ['IP addresses', 'Group addresses', 'Serial numbers', 'Register maps'], correct: 1 },
      { q: 'DALI is a bus specifically for:', options: ['Chillers', 'Addressable light fittings', 'Pumps', 'Sensors only'], correct: 1 },
      { q: 'A BMS usually integrates KNX or DALI via:', options: ['Native support', 'A protocol gateway to BACnet or Modbus', 'Wi-Fi only', 'Nothing — it cannot'], correct: 1 },
    ],
    takeaway: 'KNX links devices by group address (commissioned in ETS); DALI digitally addresses individual light fittings. The BMS reaches both through a gateway — scope the exposed points carefully.',
  },
  {
    id: 'L28',
    module: 'Protocols',
    moduleNum: 3,
    title: 'Modern protocols — MQTT, OPC-UA, REST',
    duration: 8,
    hook: "BACnet and Modbus get data around the building. Three newer protocols get it to the cloud, to dashboards, and to other software. Increasingly, this is where the value moves.",
    content: [
      { type: 'h3', text: 'MQTT' },
      { type: 'bullets', items: [
        'A lightweight publish/subscribe messaging protocol — the backbone of IoT',
        'Devices **publish** data to topics on a **broker**; anything interested **subscribes**',
        'Tiny overhead, survives flaky connections — ideal for pushing BMS data to the cloud',
      ]},
      { type: 'h3', text: 'OPC-UA' },
      { type: 'bullets', items: [
        'An industrial interoperability standard — bridges BMS to manufacturing and SCADA systems',
        'Strongly typed, secure, with a rich information model',
        'Common where a building sits inside an industrial site',
      ]},
      { type: 'h3', text: 'REST APIs & webhooks' },
      { type: 'bullets', items: [
        'Modern supervisors expose **REST APIs** — read and write points over HTTPS with JSON',
        '**Webhooks** push events out to other apps (an alarm firing a Slack message)',
        'This is how a BMS integrates with analytics platforms, mobile apps, and custom software',
      ]},
      { type: 'callout', text: 'The architecture pattern of a modern BMS: BACnet/Modbus down at the equipment, MQTT or REST up to the cloud. The edge controller (often a JACE) is the translator between the two worlds. Knowing both layers is what makes you valuable beyond pure HVAC.' },
    ],
    quiz: [
      { q: 'MQTT moves data using which pattern?', options: ['Strict request/response', 'Publish/subscribe via a broker', 'Polling only', 'Broadcast only'], correct: 1 },
      { q: 'To let a mobile app read live points from a modern supervisor you would most likely use:', options: ['Modbus RTU', 'A REST API over HTTPS', 'BACnet MS/TP', 'DALI'], correct: 1 },
      { q: 'In a modern BMS, the typical split is:', options: ['BACnet everywhere', 'BACnet/Modbus at equipment, MQTT/REST to the cloud', 'Cloud only', 'Modbus straight to the cloud'], correct: 1 },
    ],
    takeaway: 'MQTT (pub/sub to a broker), OPC-UA (industrial bridge), and REST/webhooks (HTTPS + JSON) carry BMS data up to the cloud and other software, while BACnet/Modbus stay at the equipment.',
  },
  {
    id: 'L29',
    module: 'Protocols',
    moduleNum: 3,
    title: 'Module 3 boss check',
    duration: 12,
    hook: "End of Module 3 — Protocols. This is the module that most sharply separates strong BMS engineers from weak ones. Let's check it.",
    content: [
      { type: 'h3', text: 'Module 3 recap' },
      { type: 'p', text: 'You covered BACnet (devices, objects, properties, object types, services, MS/TP, BACnet/IP and BBMD), Modbus (RTU/TCP, registers, the endianness trap), KNX and DALI, and the modern protocols MQTT, OPC-UA, and REST.' },
      { type: 'p', text: 'This boss check has 8 questions across all of Module 3. Pass at 75% (6/8) to unlock Module 4.' },
      { type: 'callout', text: 'Protocols are abstract until you wire them. After this, the best practice you can do is read a real BACnet device with a free tool like YABE, and a real Modbus device with QModMaster.' },
    ],
    quiz: [
      { q: 'The BACnet path to a live value is Device to Object to:', options: ['Network', 'Property (Present_Value)', 'Service', 'Register'], correct: 1 },
      { q: 'A physical on/off status wired into a controller is which BACnet object?', options: ['AV', 'BV', 'BI', 'MSV'], correct: 2 },
      { q: 'You command a BACnet AO and nothing happens. Check first:', options: ['The IP subnet', 'The 16-level Priority Array', 'The baud rate', 'The calendar'], correct: 1 },
      { q: 'An MS/TP segment must be terminated:', options: ['At every device', 'At each physical end (two terminators)', 'Nowhere', 'Only at the controller'], correct: 1 },
      { q: 'Devices ping across subnets but cannot discover each other in BACnet. The fix involves a:', options: ['Faster switch', 'Correctly configured BBMD per subnet', 'New protocol', 'Longer cable'], correct: 1 },
      { q: 'A Modbus temperature reads as nonsense though comms are healthy. Most likely:', options: ['Wrong byte/word order (endianness)', 'Dead sensor', 'Wrong UDP port', 'Missing terminator'], correct: 0 },
      { q: 'Modbus integration is impossible without:', options: ['A BBMD', 'The vendor register map', 'A calendar object', 'COV'], correct: 1 },
      { q: 'In a modern BMS, data typically reaches the cloud via:', options: ['BACnet MS/TP', 'MQTT or a REST API', 'DALI', 'Dry contacts'], correct: 1 },
    ],
    takeaway: 'Module 3 complete. Protocols are the differentiator — you can now read and reason about BACnet, Modbus, KNX/DALI, and the modern cloud protocols.',
    isBoss: true,
  },
];
