// Module 8 — Commissioning
export const MODULE_8 = [
  {
    id: 'L65',
    module: 'Commissioning',
    moduleNum: 8,
    title: 'Pre-functional checks & power-up',
    duration: 7,
    hook: "Commissioning is where a BMS design becomes a working building. Rushing the first phase — pre-functional checks — guarantees pain in every phase after it.",
    content: [
      { type: 'h3', text: 'What pre-functional checks (PFC) cover' },
      { type: 'bullets', items: [
        'Installation verification — is every device installed, in the right place, to spec?',
        'Wiring verification — terminations correct, labelled, and matching the drawings',
        'Panel inspection — earthing, segregation, no loose conductors',
        'Confirm the point list — every listed point physically exists',
      ]},
      { type: 'h3', text: 'Safe power-up' },
      { type: 'bullets', items: [
        'Inspect before energizing — never power a panel you have not checked',
        'Power up in stages — supply, then controllers, then field devices',
        'Verify the controller boots, network comms come up, devices are discovered',
      ]},
      { type: 'h3', text: 'Why PFC comes first' },
      { type: 'p', text: 'Point-to-point and functional testing both assume the installation is correct. If you skip PFC, you discover wiring faults during functional testing — far more expensive to trace once everything is live and interacting.' },
      { type: 'callout', text: 'A disciplined commissioning engineer treats PFC as a gate, not a formality: functional testing does not start until pre-functional checks pass. Catching a swapped pair or a missing terminator now costs minutes; catching it during FPT costs a day.' },
    ],
    quiz: [
      { q: 'Pre-functional checks primarily verify:', options: ['Energy savings', 'That installation and wiring are correct and complete', 'Tenant comfort', 'The BOQ'], correct: 1 },
      { q: 'A panel should be powered up:', options: ['All at once', 'In stages — supply, controllers, then field devices', 'After functional testing', 'Never by the BMS engineer'], correct: 1 },
      { q: 'Skipping pre-functional checks means wiring faults surface:', options: ['Never', 'Later, during functional testing — far more expensive to trace', 'At design', 'In the BOQ'], correct: 1 },
    ],
    takeaway: 'Pre-functional checks verify installation and wiring before anything goes live; power up in stages. Treat PFC as a gate — functional testing assumes the install is already correct.',
  },
  {
    id: 'L66',
    module: 'Commissioning',
    moduleNum: 8,
    title: 'Point-to-point testing',
    duration: 8,
    hook: "Point-to-point testing is the slow, unglamorous heart of commissioning: prove every single point, end to end, before trusting any sequence.",
    content: [
      { type: 'h3', text: 'The P2P method' },
      { type: 'p', text: 'For every point on the list, prove the whole signal chain: field device, cable, terminal, controller, network, supervisor graphic. The value seen at the top must match reality at the bottom.' },
      { type: 'bullets', items: [
        '**AI** — apply or read a known value at the sensor, confirm it at the controller and the graphic',
        '**AO** — command 0%, 50%, 100%, and confirm the actuator physically moves to match',
        '**DI** — physically change the contact, confirm the status flips',
        '**DO** — command it, confirm the relay and the real load switch',
      ]},
      { type: 'h3', text: 'Catching the classics' },
      { type: 'bullets', items: [
        'Reversed action — a valve opens when it should close',
        'Swapped points — AHU-1’s sensor wired to AHU-2’s input',
        'Scaling errors — a value reading 10 times or one-tenth of reality',
      ]},
      { type: 'h3', text: 'Document as you go' },
      { type: 'p', text: 'Every point gets a dated, signed tick on the P2P checklist — which is simply the point list with a results column. That record is your evidence at handover and your defence in any dispute.' },
      { type: 'callout', text: 'P2P is tedious and it is non-negotiable. Every hour spent proving points individually saves many hours during functional testing, where an unproven point makes a whole sequence look broken and sends you hunting in the wrong place.' },
    ],
    quiz: [
      { q: 'Point-to-point testing proves:', options: ['Only the sensor', 'The whole chain from field device to supervisor graphic', 'Only the graphic', 'Energy use'], correct: 1 },
      { q: 'To P2P-test an AO you:', options: ['Read the sensor', 'Command 0/50/100% and confirm the actuator physically moves to match', 'Flip a contact', 'Do nothing'], correct: 1 },
      { q: 'P2P results are recorded on:', options: ['Nothing', 'The point list with a dated, signed results column', 'A photo only', 'The BOQ'], correct: 1 },
    ],
    takeaway: 'Point-to-point testing proves every point end to end — AI/AO/DI/DO each verified against physical reality, catching reversed, swapped, and scaling errors. Document every point on the checklist.',
  },
  {
    id: 'L67',
    module: 'Commissioning',
    moduleNum: 8,
    title: 'Sensor calibration & valve stroking',
    duration: 7,
    hook: "A point can pass point-to-point testing and still be wrong. Calibration and stroking make the field devices not just connected, but accurate.",
    content: [
      { type: 'h3', text: 'Sensor calibration' },
      { type: 'bullets', items: [
        'Compare each sensor against a trusted reference instrument — a calibrated thermometer, hygrometer, or manometer',
        'Apply an offset in the controller to correct small errors; replace the sensor if the error is large or non-linear',
        'Prioritize the sensors that drive control and billing — a 1-degree error on a control sensor wastes energy continuously',
      ]},
      { type: 'h3', text: 'Valve and damper stroking' },
      { type: 'bullets', items: [
        'Drive each valve and damper through its full travel — 0%, 50%, 100%',
        'Confirm it physically reaches the end positions — a valve that only reaches 90% cannot deliver full capacity',
        'Confirm the fail position by removing power or signal',
        'Check for the right characteristic and no sticking or hysteresis',
      ]},
      { type: 'h3', text: 'Why this comes before functional testing' },
      { type: 'p', text: 'Functional testing tunes and proves sequences. If a sensor is uncalibrated or a valve does not fully stroke, you will be tuning a loop against a lie — chasing a fault that is really a field-device problem.' },
      { type: 'callout', text: 'A mis-calibrated control sensor is a permanent, invisible energy leak — the building faithfully holds the wrong number forever. Calibration is not optional polish; on control and metering points it pays for itself in weeks.' },
    ],
    quiz: [
      { q: 'Sensor calibration is done by comparing against:', options: ['Another uncalibrated sensor', 'A trusted calibrated reference instrument', 'The graphic', 'The setpoint'], correct: 1 },
      { q: 'Stroking a valve confirms it:', options: ['Looks new', 'Reaches its true end positions and fail position through full travel', 'Is the right colour', 'Has a network card'], correct: 1 },
      { q: 'Tuning a control loop while the sensor is uncalibrated means you are:', options: ['Fine', 'Tuning against a lie — chasing a field-device fault as a control fault', 'Saving time', 'Already done'], correct: 1 },
    ],
    takeaway: 'Calibrate sensors against trusted references (offset or replace) and stroke valves/dampers through full travel and the fail position — before functional testing, so you tune against the truth.',
  },
  {
    id: 'L68',
    module: 'Commissioning',
    moduleNum: 8,
    title: 'Functional performance testing',
    duration: 8,
    hook: "Functional performance testing is the exam the building sits. It proves the systems do not just work in isolation, but deliver the Sequence of Operation under real conditions.",
    content: [
      { type: 'h3', text: 'What FPT proves' },
      { type: 'p', text: 'P2P proved each point. FPT proves each sequence — every mode, every interlock, every transition described in the SOO actually happens, with the equipment running and interacting.' },
      { type: 'h3', text: 'How FPT is run' },
      { type: 'bullets', items: [
        'Work through the SOO line by line — each line becomes a test case (this is why testable SOO language matters)',
        'Force conditions — drive setpoints, simulate occupancy, trigger modes',
        'Observe the real response and record pass or fail against the SOO',
        'Re-test after any fix — fixing one thing can break another',
      ]},
      { type: 'h3', text: 'The SOO is the test script' },
      { type: 'p', text: 'A well-written SOO converts directly into the FPT script. A vague SOO cannot be tested objectively — and that is exactly where commissioning turns into argument.' },
      { type: 'callout', text: 'FPT is where the value of disciplined upstream work is collected. A precise SOO and clean P2P make FPT a smooth confirmation. A vague SOO and skipped P2P make it a chaotic, disputed fault-hunt. The pain or the smoothness is decided long before FPT starts.' },
    ],
    quiz: [
      { q: 'Functional performance testing proves:', options: ['Each individual point', 'Each sequence and mode from the SOO, with equipment running', 'The BOQ', 'Cable lengths'], correct: 1 },
      { q: 'The FPT test script is derived directly from:', options: ['The BOQ', 'The Sequence of Operation', 'The panel layout', 'The invoice'], correct: 1 },
      { q: 'After fixing a fault found in FPT you should:', options: ['Stop', 'Re-test, since a fix can break something else', 'Skip ahead', 'Invoice immediately'], correct: 1 },
    ],
    takeaway: 'Functional performance testing proves every sequence and mode from the SOO under real conditions. The SOO is the test script — and clean P2P plus a precise SOO make FPT smooth.',
  },
  {
    id: 'L69',
    module: 'Commissioning',
    moduleNum: 8,
    title: 'Failure mode testing',
    duration: 7,
    hook: "Any BMS can be tested on a good day. The tests that actually protect the building are the ugly ones: what happens when the fire alarm hits, the power dies, or a sensor fails.",
    content: [
      { type: 'h3', text: 'Why failure testing is non-negotiable' },
      { type: 'p', text: 'Failure modes are the part of the SOO that exists precisely for rare, serious events. They are also the part most likely to be wired or programmed wrong — because they are never exercised in normal running. So they must be deliberately tested.' },
      { type: 'h3', text: 'What to test' },
      { type: 'bullets', items: [
        '**Fire alarm** — trigger the real signal, confirm AHUs go to fire mode, dampers move, fans stop as specified',
        '**Power failure & restoration** — kill power, confirm equipment fails to its safe position; restore it, confirm a safe staged restart with no surprise inrush',
        '**Sensor failure** — disconnect a sensor, confirm the controller detects the fault and reacts sanely (alarm, safe default) rather than acting on garbage',
        '**Comms loss** — drop the supervisor, confirm field controllers keep running (the Module 1 rule)',
      ]},
      { type: 'callout', text: 'Test failure modes by causing the real failure, not by simulating it in software. Pull the fuse. Drop the fire signal. Unplug the sensor. A failure mode that passed only as a forced point value is untested — and untested failure modes fail in the real event, when it matters most.' },
    ],
    quiz: [
      { q: 'Failure modes must be deliberately tested because they:', options: ['Run constantly', 'Are rarely exercised, so wiring or programming errors stay hidden until the real event', 'Are unimportant', 'Cost nothing'], correct: 1 },
      { q: 'The correct way to test a fire-alarm response is to:', options: ['Force a software point', 'Trigger the real fire signal and watch the equipment respond', 'Read the graphic', 'Skip it'], correct: 1 },
      { q: 'On loss of the supervisor, FPT should confirm that:', options: ['Everything stops', 'Field controllers keep running their sequences', 'The fire alarm sounds', 'Sensors fail'], correct: 1 },
    ],
    takeaway: 'Test failure modes — fire, power loss and restore, sensor failure, comms loss — by causing the real failure, not simulating it. Untested failure modes fail when it matters most.',
  },
  {
    id: 'L70',
    module: 'Commissioning',
    moduleNum: 8,
    title: 'Tuning loops on a live system',
    duration: 8,
    hook: "The PID Lab taught the intuition. Now you tune real loops on a running building — where every loop interacts and patience beats cleverness.",
    content: [
      { type: 'h3', text: 'Tuning in the field' },
      { type: 'bullets', items: [
        'Tune one loop at a time, and let it settle before judging it',
        'Start conservative — modest P, little or no I, no D (recall: most HVAC loops need only P or PI)',
        'Watch a trend, not a single instant — a loop’s behaviour is a curve over time',
      ]},
      { type: 'h3', text: 'Reading loop behaviour' },
      { type: 'bullets', items: [
        'Sluggish, slow to reach setpoint — increase P',
        'A steady offset that never closes — add or increase I',
        'Oscillating, hunting — reduce P',
        'Jittery, noisy output — reduce D',
      ]},
      { type: 'h3', text: 'Loops interact' },
      { type: 'p', text: 'HVAC loops are not independent. A retuned AHU SAT loop changes what every VAV box downstream sees. Tune from the source outward — plant, then air handlers, then terminals — and re-check downstream after every upstream change.' },
      { type: 'callout', text: 'Resist the urge to crank gains for a fast response. An aggressive loop looks impressive on a calm day and oscillates the moment a disturbance hits — wearing actuators and destroying comfort. A slightly slow, rock-stable loop beats a fast twitchy one every time.' },
    ],
    quiz: [
      { q: 'A control loop with a steady offset that never closes needs:', options: ['More P', 'More or added I', 'More D', 'A new sensor'], correct: 1 },
      { q: 'When tuning a building, you should tune:', options: ['All loops at once', 'One loop at a time, settling before judging', 'Only the fastest loop', 'Loops at random'], correct: 1 },
      { q: 'An over-aggressive, high-gain loop typically:', options: ['Is always best', 'Looks good when calm but oscillates on a disturbance', 'Saves energy', 'Needs no actuator'], correct: 1 },
    ],
    takeaway: 'Tune loops one at a time on trends, starting conservative (P or PI). Tune from plant outward since loops interact. A stable, slightly slow loop beats a fast twitchy one.',
  },
  {
    id: 'L71',
    module: 'Commissioning',
    moduleNum: 8,
    title: 'Handover & as-builts',
    duration: 7,
    hook: "The job is not done when the building works — it is done when the next team can run it without you. Handover is where a project becomes a reputation.",
    content: [
      { type: 'h3', text: 'The handover package' },
      { type: 'bullets', items: [
        '**As-built drawings** — riser, schematics, panel layouts, all updated to match what was actually installed',
        '**As-built point list** — final, reflecting reality',
        '**Final SOO** — matching the commissioned behaviour',
        '**O&M manuals** — device datasheets, controller and software details',
        '**Commissioning records** — signed P2P and FPT results',
        '**Backups** — controller programs and the Niagara station, with licences documented',
      ]},
      { type: 'h3', text: 'Training the FM team' },
      { type: 'bullets', items: [
        'Show them the graphics, alarms, schedules, and how to adjust setpoints',
        'Teach the daily and weekly checks and how to read a trend',
        'Be honest about limits — what they can change safely, and when to call you',
      ]},
      { type: 'h3', text: 'Handover as a relationship' },
      { type: 'p', text: 'A clean handover plus a competent FM team is the foundation of a maintenance contract — recurring revenue, and a building that keeps performing instead of decaying.' },
      { type: 'callout', text: 'The brutal truth of handover: if the documentation is poor and the FM team untrained, the building degrades within months and the BMS gets blamed — regardless of how good the engineering was. Handover quality is what the client actually remembers.' },
    ],
    quiz: [
      { q: 'As-built documentation means the drawings and point list:', options: ['Are the original design', 'Have been updated to match what was actually installed', 'Are hidden', 'Are optional'], correct: 1 },
      { q: 'A complete handover package includes program and station:', options: ['Graphics only', 'Backups, with licences documented', 'Nothing', 'Just the SOO'], correct: 1 },
      { q: 'Poor handover documentation and an untrained FM team most likely lead to:', options: ['A better building', 'The building degrading within months and the BMS being blamed', 'Lower energy use', 'Faster comms'], correct: 1 },
    ],
    takeaway: 'Handover delivers as-built drawings, point list and SOO, O&M manuals, signed commissioning records, and program backups — plus a trained FM team. Handover quality is what the client remembers.',
  },
  {
    id: 'L72',
    module: 'Commissioning',
    moduleNum: 8,
    title: 'Module 8 boss check',
    duration: 10,
    hook: "End of Module 8 — Commissioning. Turning an installation into a proven, working building. Let's check it.",
    content: [
      { type: 'h3', text: 'Module 8 recap' },
      { type: 'p', text: 'You covered pre-functional checks and safe power-up, point-to-point testing, sensor calibration and valve stroking, functional performance testing, failure mode testing, tuning loops on a live system, and handover with as-builts.' },
      { type: 'p', text: 'This boss check has 7 questions across all of Module 8. Pass at 75% (6/7) to unlock Module 9.' },
      { type: 'callout', text: 'Commissioning is where every earlier discipline pays off or comes back to bite. A clean point list and a testable SOO make commissioning smooth; sloppy ones make it a fight.' },
    ],
    quiz: [
      { q: 'Functional testing should not begin until:', options: ['The invoice is paid', 'Pre-functional checks have passed', 'The client arrives', 'A year has passed'], correct: 1 },
      { q: 'Point-to-point testing proves:', options: ['Each sequence', 'Each point end to end against physical reality', 'The BOQ', 'Energy savings'], correct: 1 },
      { q: 'Sensors are calibrated against:', options: ['The graphic value', 'A trusted reference instrument', 'The setpoint', 'Another uncalibrated sensor'], correct: 1 },
      { q: 'The FPT test script comes directly from the:', options: ['BOQ', 'Sequence of Operation', 'Panel layout', 'Riser diagram'], correct: 1 },
      { q: 'A fire-alarm response should be tested by:', options: ['Forcing a software point', 'Triggering the real fire signal', 'Reading the graphic', 'Skipping it'], correct: 1 },
      { q: 'When tuning a building, loops should be tuned:', options: ['All at once', 'One at a time, from the plant outward', 'Only the chiller loop', 'At random'], correct: 1 },
      { q: '"As-built" documentation means it:', options: ['Is the original design', 'Reflects what was actually installed', 'Is optional', 'Is hidden from the client'], correct: 1 },
    ],
    takeaway: 'Module 8 complete. You can take a BMS from installed to proven — checks, P2P, calibration, functional and failure testing, tuning, and a clean handover.',
    isBoss: true,
  },
];
