// Module 4 — Field Devices
export const MODULE_4 = [
  {
    id: 'L30',
    module: 'Field Devices',
    moduleNum: 4,
    title: 'Temperature sensors',
    duration: 7,
    hook: "Temperature is the most-measured value in any building. Three sensing technologies cover almost every case — and choosing wrong costs you accuracy or money.",
    content: [
      { type: 'h3', text: 'The three technologies' },
      { type: 'bullets', items: [
        '**RTD (PT100 / PT1000)** — a platinum element whose resistance rises predictably with temperature. Very accurate, very stable, more expensive. PT1000 is preferred for BMS — higher resistance means less lead-wire error.',
        '**Thermistor (NTC, e.g. 10k ohm)** — resistance falls steeply with temperature. Cheap, sensitive over a narrow range, less stable long term. Fine for HVAC comfort ranges.',
        '**Thermocouple** — two metals generating a tiny voltage with temperature. Huge range, used for very high temperatures (flues, boilers) — rare in comfort HVAC.',
      ]},
      { type: 'h3', text: 'Accuracy and placement' },
      { type: 'bullets', items: [
        'An RTD might be plus or minus 0.1 degree; a thermistor plus or minus 0.2 to 0.5 — usually fine for comfort, not for energy billing',
        'Placement beats sensor grade: a great sensor in a bad spot (sun, draft, dead pocket) reads worse than a cheap one placed well',
        'Averaging sensors (a long capillary) are used across large ducts where air is not well mixed',
      ]},
      { type: 'callout', text: 'For BMS, PT1000 is the safe default for anything that matters; 10k thermistors for ordinary zone and duct temperatures. Reserve thermocouples for high-temperature plant. And remember: in Ghana’s humidity, sensor location and proper sealing matter more than the spec-sheet accuracy.' },
    ],
    quiz: [
      { q: 'Which sensor is most accurate and stable for BMS use?', options: ['Thermocouple', '10k thermistor', 'PT1000 RTD', 'Bimetallic strip'], correct: 2 },
      { q: 'Thermocouples are mainly used for:', options: ['Comfort zone temperatures', 'Very high temperatures like flues', 'Humidity', 'Pressure'], correct: 1 },
      { q: 'A high-accuracy sensor placed in direct sun on a wall will:', options: ['Read accurately anyway', 'Read poorly — placement beats sensor grade', 'Fail immediately', 'Improve over time'], correct: 1 },
    ],
    takeaway: 'RTD (PT1000) for accuracy, thermistor (10k) for cheap comfort sensing, thermocouple for high heat. Placement matters more than the spec sheet.',
  },
  {
    id: 'L31',
    module: 'Field Devices',
    moduleNum: 4,
    title: 'Humidity, pressure & CO2 sensors',
    duration: 7,
    hook: "Beyond temperature, three measurements drive most control: humidity, pressure, and CO2. Each has a quirk that catches engineers out.",
    content: [
      { type: 'h3', text: 'Humidity' },
      { type: 'bullets', items: [
        'Almost all BMS humidity sensors are **capacitive** — a thin film whose capacitance changes with moisture',
        'They **drift** — expect to recalibrate every 1 to 2 years; humid climates accelerate the drift',
        'Measured as %RH; control to a band, not a tight setpoint',
      ]},
      { type: 'h3', text: 'Pressure' },
      { type: 'bullets', items: [
        '**Differential pressure (DP)** — across a filter, a fan, or a coil. Used for filter status and flow inference.',
        '**Static pressure** — duct pressure for VFD control (recall Module 2)',
        'DP sensors need the right range — a sensor scaled 0 to 2500 Pa is useless for a 0 to 100 Pa duct measurement',
      ]},
      { type: 'h3', text: 'CO2' },
      { type: 'bullets', items: [
        'Almost all use the **NDIR** principle — infrared absorption by CO2',
        'Drives demand-controlled ventilation: more people, more CO2, more fresh air',
        'Some need periodic auto-calibration against a known baseline; keep them away from people’s direct breath',
      ]},
      { type: 'callout', text: 'The recurring theme in field sensors is range and drift. A sensor with the wrong range gives you garbage resolution; a sensor never recalibrated slowly lies. Build recalibration into the maintenance contract — it is also a recurring revenue line for Yakuver.' },
    ],
    quiz: [
      { q: 'BMS humidity sensors are typically capacitive and notably:', options: ['Maintenance-free', 'Prone to drift, needing recalibration', 'Only for outdoor use', 'Digital only'], correct: 1 },
      { q: 'CO2 sensors in BMS almost all use which principle?', options: ['Capacitive film', 'NDIR infrared', 'RTD resistance', 'Ultrasonic'], correct: 1 },
      { q: 'A DP sensor scaled 0 to 2500 Pa used on a 0 to 100 Pa duct measurement gives:', options: ['Perfect data', 'Poor resolution — effectively garbage', 'Faster response', 'Nothing — it fails'], correct: 1 },
    ],
    takeaway: 'Humidity is capacitive and drifts (recalibrate). Pressure — match the range to the job. CO2 is NDIR and drives demand-controlled ventilation.',
  },
  {
    id: 'L32',
    module: 'Field Devices',
    moduleNum: 4,
    title: 'Flow & energy metering',
    duration: 8,
    hook: "You cannot manage what you cannot measure. Flow and energy meters turn a BMS from a comfort tool into an accountability tool — and they are where billing-grade accuracy suddenly matters.",
    content: [
      { type: 'h3', text: 'Flow meters' },
      { type: 'bullets', items: [
        '**Electromagnetic (mag)** — no moving parts, accurate, needs a conductive liquid; the BMS default for water',
        '**Ultrasonic** — clamps onto the pipe, often non-invasive; good for retrofits',
        '**Turbine / vortex** — mechanical or shedding-based; cheaper, more wear',
      ]},
      { type: 'h3', text: 'Energy / BTU metering' },
      { type: 'p', text: 'A thermal energy (BTU) meter combines a flow meter with two temperature sensors — supply and return. Energy equals flow times temperature difference times time. This tells you how much cooling a building or tenant actually consumed.' },
      { type: 'h3', text: 'Electrical metering' },
      { type: 'bullets', items: [
        'Current is measured with **CTs (current transformers)** clamped around conductors',
        '**Rogowski coils** are flexible CTs — easy to retrofit around awkward busbars',
        '**Revenue-grade** meters meet a legal accuracy class — required if you bill tenants from the reading',
      ]},
      { type: 'callout', text: 'Draw a hard line between monitoring-grade and revenue-grade. Monitoring meters guide optimization. Revenue-grade meters are billed against and have legal accuracy requirements — never let a client bill tenants off a monitoring-grade point. In Ghana, sub-metering tenants is a strong BMS upsell, but only with the right meter class.' },
    ],
    quiz: [
      { q: 'A thermal energy (BTU) meter measures cooling energy by combining flow with:', options: ['Pressure', 'Two temperatures — supply and return', 'Humidity', 'Voltage'], correct: 1 },
      { q: 'Current in an electrical energy meter is sensed using:', options: ['RTDs', 'CTs or Rogowski coils', 'NDIR sensors', 'Pulse contacts'], correct: 1 },
      { q: 'To bill tenants from a meter reading you must use:', options: ['Any meter', 'A revenue-grade meter of the required accuracy class', 'An ultrasonic meter', 'A thermistor'], correct: 1 },
    ],
    takeaway: 'Flow meters (mag, ultrasonic, turbine) plus temperature give energy (BTU) meters. Electrical metering uses CTs/Rogowski coils. Billing needs revenue-grade accuracy.',
  },
  {
    id: 'L33',
    module: 'Field Devices',
    moduleNum: 4,
    title: 'Valve & damper actuators',
    duration: 8,
    hook: "Sensors let the BMS see. Actuators let it act. The actuator's failure behaviour — what it does when power or signal dies — is a safety decision, not an afterthought.",
    content: [
      { type: 'h3', text: 'Spring return vs non-spring' },
      { type: 'bullets', items: [
        '**Spring return** — on power loss, a spring drives the actuator to a defined fail position. Used wherever a safe default matters.',
        '**Non-spring (fail-in-place)** — on power loss it simply stops where it is. Cheaper, used where any position is acceptable.',
      ]},
      { type: 'h3', text: 'Control signal types' },
      { type: 'bullets', items: [
        '**Modulating** — a 0 to 10V or 4 to 20mA signal positions it anywhere 0 to 100%',
        '**Floating (3-point)** — two digital outputs: one drives open, one drives closed, neither holds',
        '**2-position (on/off)** — fully open or fully closed only',
      ]},
      { type: 'h3', text: 'Sizing — torque' },
      { type: 'p', text: 'A damper actuator must produce enough torque to drive the damper against air pressure and friction across its full area. A valve actuator must produce enough force to close against the system differential pressure — the close-off pressure. Undersize it and the valve will not fully shut.' },
      { type: 'callout', text: 'The fail position is a design decision: a heating valve on a freeze-risk coil often fails open; an outside-air damper fails closed; a critical chilled water valve depends on the sequence intent. Specify it explicitly in the SOO — never leave it to whatever the actuator happened to ship as.' },
    ],
    quiz: [
      { q: 'An actuator that drives to a defined safe position on power loss is:', options: ['Non-spring', 'Spring return', 'Floating', '2-position'], correct: 1 },
      { q: 'Floating actuator control uses:', options: ['One analog signal', 'Two digital outputs — open and close', 'A 4 to 20mA loop', 'A pulse train'], correct: 1 },
      { q: 'A valve actuator with too little torque for the system pressure will:', options: ['Open too far', 'Fail to fully close against the close-off pressure', 'Respond too fast', 'Draw no power'], correct: 1 },
    ],
    takeaway: 'Actuators are spring-return (safe fail position) or fail-in-place; driven modulating, floating, or 2-position; and must be torque-sized for close-off pressure. Specify the fail position in the SOO.',
  },
  {
    id: 'L34',
    module: 'Field Devices',
    moduleNum: 4,
    title: 'Valve characteristics & sizing',
    duration: 9,
    hook: "Two valves can be the same size with the same actuator and behave completely differently. The difference is the valve characteristic — the relationship between how far it opens and how much it flows.",
    content: [
      { type: 'h3', text: 'The three characteristics' },
      { type: 'bullets', items: [
        '**Quick-opening** — most flow change happens early in the stroke; used for 2-position service',
        '**Linear** — flow is proportional to stroke; equal steps of travel give equal flow change',
        '**Equal-percentage** — each equal step of stroke changes flow by an equal percentage; small flow near closed, big flow near open',
      ]},
      { type: 'h3', text: 'Why equal-percentage wins for coils' },
      { type: 'p', text: 'A heating or cooling coil is itself non-linear — the first bit of flow does most of the work. An equal-percentage valve has the opposite curve. The two non-linearities cancel, giving a nearly linear, stable control loop. That is why coil control valves are almost always equal-percentage.' },
      { type: 'h3', text: 'Cv, authority, rangeability' },
      { type: 'bullets', items: [
        '**Cv (or Kv)** — the valve’s flow coefficient; the proper basis of sizing',
        '**Authority** — the valve’s pressure drop as a fraction of the loop’s total drop. Aim for 0.25 to 0.5 or higher. Low authority distorts the characteristic.',
        '**Rangeability** — the ratio of maximum to minimum controllable flow; higher gives better turndown',
      ]},
      { type: 'callout', text: 'The classic oversized-valve fault: a valve picked on pipe size instead of Cv ends up with almost no authority. It then does all its control in the first 10 to 20% of travel and slams between barely-open and shut. Size on Cv and authority, never on the pipe diameter.' },
    ],
    quiz: [
      { q: 'Coil control valves are almost always which characteristic?', options: ['Quick-opening', 'Linear', 'Equal-percentage', 'None of these'], correct: 2 },
      { q: 'Equal-percentage valves suit coils because they:', options: ['Are cheaper', 'Cancel the coil’s own non-linearity for a stable loop', 'Open faster', 'Need no actuator'], correct: 1 },
      { q: 'A valve sized on pipe diameter instead of Cv typically ends up:', options: ['Perfectly sized', 'Oversized with low authority, controlling in a tiny part of its stroke', 'Too small', 'Frictionless'], correct: 1 },
    ],
    takeaway: 'The valve characteristic is the stroke-to-flow relationship. Equal-percentage suits coils because it cancels coil non-linearity. Size on Cv and authority (0.25 to 0.5), never on pipe size.',
  },
  {
    id: 'L35',
    module: 'Field Devices',
    moduleNum: 4,
    title: 'Dampers & PICVs',
    duration: 7,
    hook: "Dampers control air the way valves control water — and one modern valve type, the PICV, quietly solves a balancing headache that used to need a specialist.",
    content: [
      { type: 'h3', text: 'Damper blade types' },
      { type: 'bullets', items: [
        '**Parallel blade** — all blades rotate the same way; airflow gets deflected to one side. Cheaper, fine for 2-position (open/shut) duty.',
        '**Opposed blade** — adjacent blades rotate oppositely; gives a more linear, predictable characteristic. Preferred for modulating control.',
      ]},
      { type: 'h3', text: 'Damper leakage and sizing' },
      { type: 'p', text: 'Even a closed damper leaks. Low-leakage dampers (with blade seals) matter for outside-air and isolation duties where leakage wastes energy or breaks a sequence. A damper sized too large modulates within a tiny arc — the same authority problem as valves.' },
      { type: 'h3', text: 'PICVs — pressure-independent control valves' },
      { type: 'bullets', items: [
        'A PICV combines a control valve with a built-in differential-pressure regulator',
        'It holds a set flow regardless of pressure swings elsewhere in the system',
        'That makes hydronic balancing largely automatic — no separate commissioning balance of every circuit',
      ]},
      { type: 'callout', text: 'PICVs cost more per valve but cut commissioning time and stop the rob-Peter-to-pay-Paul flow shifts when other circuits change. On a Yakuver project, pricing PICVs against the saved balancing labour is a strong, honest pitch.' },
    ],
    quiz: [
      { q: 'For a modulating control damper, the preferred blade type is:', options: ['Parallel', 'Opposed', 'Either works equally', 'Neither'], correct: 1 },
      { q: 'A PICV holds a set flow regardless of:', options: ['Temperature', 'System pressure swings elsewhere', 'Valve size', 'The actuator type'], correct: 1 },
      { q: 'An oversized modulating damper, like an oversized valve, will:', options: ['Work fine', 'Control within only a tiny arc of travel', 'Leak less', 'Need no actuator'], correct: 1 },
    ],
    takeaway: 'Opposed-blade dampers for modulating control; mind leakage and oversizing. PICVs build pressure-independent flow control into the valve, making hydronic balancing automatic.',
  },
  {
    id: 'L36',
    module: 'Field Devices',
    moduleNum: 4,
    title: 'VFDs from a BMS view',
    duration: 8,
    hook: "The variable frequency drive is how a BMS turns 'run the fan slower' into real energy savings. You do not need to be a drives engineer — you need the handful of things the BMS touches.",
    content: [
      { type: 'h3', text: 'What a VFD does' },
      { type: 'p', text: 'A VFD varies the frequency (and voltage) supplied to an AC motor, varying its speed. Because fan and pump power follow a cube law, modest speed reductions yield large energy savings — the whole reason VFDs dominate modern HVAC.' },
      { type: 'h3', text: 'What the BMS exchanges with a VFD' },
      { type: 'bullets', items: [
        '**Speed command** (output) — the 0 to 100% the drive should run at',
        '**Speed feedback** (input) — actual running speed or frequency',
        '**Run status** and **fault** (inputs) — is it running, has it tripped',
        '**Start/stop** (output) — though the run permissive is often hardwired for safety',
      ]},
      { type: 'h3', text: 'Hardwired vs networked' },
      { type: 'bullets', items: [
        '**Hardwired** — 0 to 10V speed, dry contacts for start and status. Simple, robust, few data points.',
        '**Networked** — a BACnet or Modbus card in the drive exposes dozens of parameters: current, power, energy, temperatures, detailed fault codes',
      ]},
      { type: 'callout', text: 'Networked VFD integration is high value: motor power and energy per drive turn the BMS into an energy and predictive-maintenance tool. But confirm the drive has the right fieldbus card and you have its register or object map before quoting — a Modbus VFD with no map is the Module 3 lesson all over again.' },
    ],
    quiz: [
      { q: 'VFDs save large amounts of energy because fan and pump power follow:', options: ['A linear law with speed', 'A cube law with speed', 'No relationship to speed', 'A square-root law'], correct: 1 },
      { q: 'Which is an input the BMS reads from a VFD?', options: ['Speed command', 'Run status and fault', 'Start command', 'Setpoint'], correct: 1 },
      { q: 'The advantage of networked VFD integration over hardwired is:', options: ['Lower cost', 'Access to detailed data — power, energy, fault codes', 'A faster motor', 'No card needed'], correct: 1 },
    ],
    takeaway: 'A VFD varies motor speed; cube-law power makes it the core energy-saving device. The BMS exchanges speed command/feedback, status, and fault — hardwired for simplicity or networked for rich data.',
  },
  {
    id: 'L37',
    module: 'Field Devices',
    moduleNum: 4,
    title: 'Module 4 boss check',
    duration: 10,
    hook: "End of Module 4 — Field Devices. The hardware your sequences depend on. Let's check it.",
    content: [
      { type: 'h3', text: 'Module 4 recap' },
      { type: 'p', text: 'You covered temperature sensors (RTD, thermistor, thermocouple), humidity/pressure/CO2 sensors, flow and energy metering, actuators and fail position, valve characteristics and sizing, dampers and PICVs, and VFDs.' },
      { type: 'p', text: 'This boss check has 8 questions across all of Module 4. Pass at 75% (6/8) to unlock Module 5.' },
      { type: 'callout', text: 'Field devices are where the BMS meets the physical world. The recurring themes — placement, range, drift, fail position, sizing — apply to almost every device you will ever specify.' },
    ],
    quiz: [
      { q: 'The most accurate, stable temperature sensor for BMS control is the:', options: ['10k thermistor', 'PT1000 RTD', 'Thermocouple', 'Bimetallic strip'], correct: 1 },
      { q: 'A CO2 sensor for demand-controlled ventilation works on which principle?', options: ['Capacitive', 'NDIR infrared', 'RTD', 'Vortex shedding'], correct: 1 },
      { q: 'To bill a tenant from a meter you need a meter that is:', options: ['Ultrasonic', 'Revenue-grade', 'Mag-type', 'Pulse-output'], correct: 1 },
      { q: 'On loss of power, a spring-return actuator:', options: ['Stops where it is', 'Drives to a defined fail position', 'Speeds up', 'Does nothing'], correct: 1 },
      { q: 'Coil control valves are almost always:', options: ['Quick-opening', 'Linear', 'Equal-percentage', 'Ball valves'], correct: 2 },
      { q: 'A valve sized on pipe diameter instead of Cv tends to be:', options: ['Perfectly sized', 'Oversized with poor authority', 'Undersized', 'Frictionless'], correct: 1 },
      { q: 'For a modulating damper you should specify:', options: ['Parallel blades', 'Opposed blades', 'No actuator', 'A solid plate'], correct: 1 },
      { q: 'Fan and pump energy savings from a VFD are large because power follows:', options: ['A linear law', 'A cube law with speed', 'No law', 'A constant'], correct: 1 },
    ],
    takeaway: 'Module 4 complete. You can now specify the sensors, meters, actuators, valves, dampers, and VFDs your sequences depend on.',
    isBoss: true,
  },
];
