// Module 5 — Controllers & Architecture
export const MODULE_5 = [
  {
    id: 'L38',
    module: 'Controllers',
    moduleNum: 5,
    title: 'DDC controllers — ASC vs programmable',
    duration: 7,
    hook: "Every sequence you write runs on a controller. Picking the right type — fixed-function or fully programmable — sets the cost and the flexibility of the whole job.",
    content: [
      { type: 'h3', text: 'Application-specific controllers (ASC)' },
      { type: 'bullets', items: [
        'Pre-built for one job — a VAV box, an FCU, a heat pump',
        'Configured (you set parameters), not programmed',
        'Cheap, fast to deploy, limited I/O, limited flexibility',
      ]},
      { type: 'h3', text: 'Programmable / general-purpose controllers' },
      { type: 'bullets', items: [
        'A blank canvas — you write the logic',
        'Run AHUs, chiller plants, anything custom',
        'More I/O, more memory, more cost',
      ]},
      { type: 'h3', text: 'Choosing between them' },
      { type: 'p', text: 'Use ASCs for the many repeated standard units — dozens of identical VAVs. Use programmable controllers for the few complex unique plants — the chiller plant, the central AHUs. A typical building has many ASCs and a handful of programmable controllers, mirroring the 3-tier pyramid from Module 1.' },
      { type: 'callout', text: 'A common costly mistake: using expensive programmable controllers for simple repeated units, or forcing a fixed-function ASC to do a job it was never built for. Match the controller class to the job — standard-and-repeated versus complex-and-unique.' },
    ],
    quiz: [
      { q: 'An application-specific controller is generally:', options: ['Programmed from scratch', 'Configured for one fixed job', 'Only for chillers', 'A supervisor'], correct: 1 },
      { q: 'A custom central chiller plant is best run by:', options: ['An ASC', 'A programmable general-purpose controller', 'A thermostat', 'An energy meter'], correct: 1 },
      { q: 'A typical building uses:', options: ['Only programmable controllers', 'Many ASCs and a few programmable controllers', 'One controller in total', 'Only ASCs'], correct: 1 },
    ],
    takeaway: 'ASCs are configured for fixed repeated jobs (VAVs, FCUs); programmable controllers are coded for complex unique plants. Match the controller class to the job.',
  },
  {
    id: 'L39',
    module: 'Controllers',
    moduleNum: 5,
    title: 'I/O capacity, processing & programming',
    duration: 7,
    hook: "Two controllers can look identical and differ hugely in what they can actually do. Three specs tell the real story: I/O, processing, and how you program them.",
    content: [
      { type: 'h3', text: 'I/O capacity' },
      { type: 'p', text: 'A controller’s I/O count — its AI/AO/DI/DO totals — caps how many physical points it can serve. Recall Module 1: size from the point list plus about 20% spare. Some controllers accept expansion modules to add I/O.' },
      { type: 'h3', text: 'Processing & memory' },
      { type: 'bullets', items: [
        'Scan time / loop speed — how fast it executes its program',
        'Memory — caps how much logic, trend history, and how many points it can hold',
        'Onboard trending and alarming capacity',
      ]},
      { type: 'h3', text: 'Programming languages' },
      { type: 'bullets', items: [
        '**Wire sheet / function block** — drag blocks, draw connections. Visual, common (Niagara and many vendors).',
        '**Ladder logic** — relay-style; common in PLC-derived controllers',
        '**Structured text** — a written programming language; powerful for complex logic',
        'Various line-based or script-based vendor languages',
      ]},
      { type: 'callout', text: 'The programming environment is a lock-in decision in disguise. Whoever maintains the building must own and know the tool. Favour widely-known environments (Niagara wire sheets, for example) so you are not the only person on Earth who can service the site — and so a client is not trapped with one contractor.' },
    ],
    quiz: [
      { q: 'A controller’s AI/AO/DI/DO totals determine:', options: ['Its price only', 'How many physical points it can serve', 'Its IP address', 'Its protocol'], correct: 1 },
      { q: 'Wire sheet programming means:', options: ['Writing text code', 'Drag-and-connect function blocks', 'Drawing ladder rungs', 'No programming at all'], correct: 1 },
      { q: 'Choosing a widely-known programming environment mainly protects against:', options: ['Slow loops', 'Vendor and contractor lock-in for maintenance', 'Power loss', 'Electrical noise'], correct: 1 },
    ],
    takeaway: 'Controllers differ in I/O capacity, processing/memory, and programming language (wire sheet, ladder, structured text). The programming environment is a lock-in decision — favour widely-known tools.',
  },
  {
    id: 'L40',
    module: 'Controllers',
    moduleNum: 5,
    title: 'The supervisory layer',
    duration: 7,
    hook: "Controllers run the building. The supervisor is where humans understand it. Knowing exactly what a supervisor adds — and what it must never be relied on for — is core architecture.",
    content: [
      { type: 'h3', text: 'What a supervisor does' },
      { type: 'bullets', items: [
        '**Graphics** — visual dashboards of plant and floors',
        '**Schedules** — building-wide time programs pushed down to controllers',
        '**Alarms** — collection, routing (email/SMS), acknowledgement, history',
        '**Trends** — long-term historical data and reports',
        '**Global strategies** — load shedding, optimum start, cross-system logic',
        '**Remote access** — one point of entry for the FM team',
      ]},
      { type: 'h3', text: 'What it must NOT be relied on for' },
      { type: 'p', text: 'Recall the 3-tier rule from Module 1: real-time control lives in the field controllers. If the supervisor is down, the building must keep running. The supervisor is for humans and history — not the millisecond control loop.' },
      { type: 'callout', text: 'A red flag in any design: a sequence that only works while the supervisor is online — a PID loop or a safety interlock running in the head end. If the supervisor reboots, that logic stops. Push all real-time control and all safeties down into the field controllers.' },
    ],
    quiz: [
      { q: 'Which is a core supervisor function?', options: ['Running each PID loop in real time', 'Graphics, alarms, trends, and schedules for humans', 'Being the freezestat', 'Powering the sensors'], correct: 1 },
      { q: 'If the supervisor goes offline, a well-designed building:', options: ['Stops', 'Keeps running from its field controllers', 'Enters fire mode', 'Loses all sensors'], correct: 1 },
      { q: 'A PID loop that only runs while the supervisor is online is:', options: ['Best practice', 'A design red flag — control belongs in field controllers', 'Required by BACnet', 'More efficient'], correct: 1 },
    ],
    takeaway: 'The supervisor gives humans graphics, schedules, alarms, trends, and remote access — but real-time control and safeties must live in the field controllers, never the head end.',
  },
  {
    id: 'L41',
    module: 'Controllers',
    moduleNum: 5,
    title: 'The Niagara JACE & supervisor types',
    duration: 8,
    hook: "One product shows up on more BMS projects than any other: the Niagara JACE. Understanding where it sits explains modern BMS architecture.",
    content: [
      { type: 'h3', text: 'The JACE' },
      { type: 'bullets', items: [
        'A JACE is a small edge device running the Niagara framework',
        'It is a **multi-protocol controller and mini-supervisor in one** — it speaks BACnet, Modbus, and more, and normalizes them',
        'It runs logic locally and serves graphics — a hybrid of Tier 2 and Tier 3',
      ]},
      { type: 'h3', text: 'Embedded vs server-based supervisors' },
      { type: 'bullets', items: [
        '**Embedded** (like a JACE) — a hardened appliance, no Windows, always-on, modest capacity',
        '**Server-based** — a Niagara Supervisor or similar on a server or VM; handles many JACEs, long-term history, big graphics',
      ]},
      { type: 'h3', text: 'The common pattern' },
      { type: 'p', text: 'JACEs sit in the building integrating field controllers of mixed protocols; a server-based Supervisor sits above, aggregating many JACEs (or many buildings) for enterprise-wide trends, alarms, and dashboards.' },
      { type: 'diagram', kind: 'tiers' },
      { type: 'callout', text: 'Why Niagara dominates: it is vendor-neutral integration glue. It does not care if the field controllers are Honeywell, Distech, or a Modbus chiller — it normalizes them all. That is also why Niagara N4 skills (Module 6) are the single highest-ROI thing you can learn.' },
    ],
    quiz: [
      { q: 'A Niagara JACE is best described as:', options: ['A pure sensor', 'A multi-protocol edge controller and mini-supervisor', 'A chiller', 'A Windows server'], correct: 1 },
      { q: 'A server-based supervisor is typically used to:', options: ['Replace field controllers', 'Aggregate many JACEs or buildings for enterprise trends and graphics', 'Power dampers', 'Act as the freezestat'], correct: 1 },
      { q: 'Niagara’s main strength is that it is:', options: ['The cheapest option', 'Vendor-neutral integration — normalizing mixed protocols', 'Able to run with no controllers', 'Offline only'], correct: 1 },
    ],
    takeaway: 'The JACE is an edge multi-protocol controller plus mini-supervisor; server-based supervisors aggregate many JACEs. Niagara dominates because it is vendor-neutral integration glue.',
  },
  {
    id: 'L42',
    module: 'Controllers',
    moduleNum: 5,
    title: 'BMS network topology',
    duration: 7,
    hook: "A BMS is only as reliable as the network under it. A handful of topology patterns cover almost every building.",
    content: [
      { type: 'h3', text: 'The layered network' },
      { type: 'bullets', items: [
        '**Field bus** — MS/TP or Modbus RTU trunks connecting field controllers, daisy-chained',
        '**Automation / IP backbone** — Ethernet linking JACEs and programmable controllers, often BACnet/IP',
        '**Supervisory network** — where servers and operator workstations sit',
      ]},
      { type: 'h3', text: 'Topology patterns' },
      { type: 'bullets', items: [
        '**Star** — each device home-run to a switch; common for IP',
        '**Daisy chain / trunk** — for serial field buses (the MS/TP rule from Module 3)',
        '**Ring** — managed switches give a self-healing loop for resilient backbones',
      ]},
      { type: 'h3', text: 'Practical guidance' },
      { type: 'p', text: 'Keep field buses short and well-terminated; keep the IP backbone on managed switches; document every IP address and every MS/TP MAC. An undocumented BMS network is the slowest thing on Earth to troubleshoot.' },
      { type: 'callout', text: 'BMS networks increasingly ride shared corporate infrastructure. That is fine only with proper segmentation — the subject of the next lesson. Never let a casual “just put it on the office LAN” pass without a segmentation conversation.' },
    ],
    quiz: [
      { q: 'A serial MS/TP field bus uses which topology?', options: ['Star', 'Daisy chain trunk', 'Mesh', 'Ring of stars'], correct: 1 },
      { q: 'A self-healing, resilient backbone is typically built as a:', options: ['Star', 'Single cable', 'Managed-switch ring', 'Daisy chain'], correct: 2 },
      { q: 'The slowest BMS network to troubleshoot is one that is:', options: ['Fast', 'Undocumented — no IP or MAC records', 'Using fiber', 'On managed switches'], correct: 1 },
    ],
    takeaway: 'BMS networks layer a serial field bus, an IP automation backbone, and a supervisory network. Star for IP, daisy chain for serial, ring for resilient backbones — and document everything.',
  },
  {
    id: 'L43',
    module: 'Controllers',
    moduleNum: 5,
    title: 'VLANs, OT segmentation & redundancy',
    duration: 8,
    hook: "The moment a BMS touches the corporate network, it becomes a cybersecurity and reliability problem. Two ideas — segmentation and redundancy — keep it safe and keep it up.",
    content: [
      { type: 'h3', text: 'OT vs IT — and segmentation' },
      { type: 'p', text: 'A BMS is operational technology (OT). It should not share a flat network with email and laptops. A VLAN (or a physically separate network) isolates the BMS into its own segment, with a firewall controlling what may cross.' },
      { type: 'bullets', items: [
        'Limits the blast radius — a malware outbreak on the office LAN cannot reach the chillers',
        'Controls traffic — only defined ports and devices cross between OT and IT',
        'Makes the BMS easier to troubleshoot — its traffic is not buried in office noise',
      ]},
      { type: 'h3', text: 'Redundancy & failover' },
      { type: 'bullets', items: [
        '**Controller autonomy** — the Tier-2 rule already gives baseline resilience',
        '**Redundant supervisors / servers** — a standby takes over if the primary fails',
        '**Network redundancy** — ring topologies, dual paths',
        '**UPS** on the head-end and critical controllers — rides through Ghana’s frequent power dips',
      ]},
      { type: 'callout', text: 'For Ghana specifically, power resilience is not optional. UPS on the head end and key panels, and graceful behaviour on power loss and return (controllers must reboot into a safe known state), belong in every design and SOO.' },
    ],
    quiz: [
      { q: 'Putting the BMS on its own VLAN, separate from office IT, mainly:', options: ['Speeds up email', 'Limits the blast radius and controls cross-traffic', 'Removes the need for controllers', 'Lowers hardware cost'], correct: 1 },
      { q: 'A BMS is an example of:', options: ['Information technology only', 'Operational technology (OT)', 'A consumer device', 'A database'], correct: 1 },
      { q: 'In Ghana, a non-optional resilience measure for the BMS head end is:', options: ['More graphics', 'UPS and safe behaviour through power dips', 'Brighter dashboards', 'More sensors'], correct: 1 },
    ],
    takeaway: 'A BMS is OT — segment it onto its own VLAN behind a firewall to limit blast radius. Add redundancy (supervisors, network paths, UPS), critical in power-unstable Ghana.',
  },
  {
    id: 'L44',
    module: 'Controllers',
    moduleNum: 5,
    title: 'Controller selection & panel layout',
    duration: 8,
    hook: "Selecting controllers and laying out panels is where engineering meets the physical world. Do it methodically and the install, the troubleshooting, and the next engineer all benefit.",
    content: [
      { type: 'h3', text: 'Controller selection method' },
      { type: 'bullets', items: [
        'Start from the point list — count AI/AO/DI/DO per piece of equipment',
        'Add about 20% spare I/O',
        'Pick the controller class — ASC for repeated standard units, programmable for complex plant',
        'Confirm protocol (BACnet native preferred) and adequate processing and memory headroom',
      ]},
      { type: 'h3', text: 'Grouping logic' },
      { type: 'p', text: 'Group points and controllers by equipment and by location. Ideally one controller serves one logical system — one AHU, one plant — so a fault is contained and the wiring runs stay short.' },
      { type: 'h3', text: 'Panel layout' },
      { type: 'bullets', items: [
        'Logical grouping — controller, I/O, terminals, power, isolation in a sensible order',
        'Clear labelling of every terminal and cable, matching the point list tags',
        'Segregate power and signal wiring to reduce electrical noise',
        'Leave physical spare space, not just spare I/O, for future additions',
      ]},
      { type: 'callout', text: 'A panel is a document as much as a box. The next engineer (often you, two years later) should open it and read it like a map. Tag every cable to the point list, and the panel, the drawings, and the live system all tell the same story.' },
    ],
    quiz: [
      { q: 'The starting point for controller selection is:', options: ['The budget', 'The point list — counted I/O per equipment', 'The brand preference', 'The panel size'], correct: 1 },
      { q: 'Ideally, one controller should serve:', options: ['Every system in the building', 'One logical system, for fault containment and short runs', 'Only one point', 'Half a floor at random'], correct: 1 },
      { q: 'Cables and terminals in a panel should be labelled to:', options: ['Random numbers', 'The point list tags, so panel and drawings agree', 'The installer’s initials', 'Nothing'], correct: 1 },
    ],
    takeaway: 'Select controllers from the point-list I/O count plus about 20% spare, matched to job type. Group by system, lay panels out logically, and tag everything to the point list.',
  },
  {
    id: 'L45',
    module: 'Controllers',
    moduleNum: 5,
    title: 'Module 5 boss check',
    duration: 10,
    hook: "End of Module 5 — Controllers & Architecture. How the BMS is structured and connected. Let's check it.",
    content: [
      { type: 'h3', text: 'Module 5 recap' },
      { type: 'p', text: 'You covered ASC versus programmable controllers, I/O and processing specs and programming languages, the supervisory layer, the Niagara JACE and supervisor types, network topology, OT segmentation and redundancy, and controller selection and panel layout.' },
      { type: 'p', text: 'This boss check has 7 questions across all of Module 5. Pass at 75% (6/7) to unlock Module 6.' },
      { type: 'callout', text: 'Architecture decisions are hard to undo once a building is wired. Getting controller class, network segmentation, and spare capacity right at design time is what separates a clean job from an expensive retrofit.' },
    ],
    quiz: [
      { q: 'Forty identical VAV boxes are best served by:', options: ['Programmable controllers', 'Application-specific controllers (ASCs)', 'One giant controller', 'Supervisors'], correct: 1 },
      { q: 'Real-time control and safeties should live in the:', options: ['Supervisor / head end', 'Field controllers', 'Cloud', 'Operator workstation'], correct: 1 },
      { q: 'A Niagara JACE is a:', options: ['Pure field sensor', 'Multi-protocol edge controller and mini-supervisor', 'Windows-only server', 'Type of valve'], correct: 1 },
      { q: 'A serial MS/TP field bus is wired as a:', options: ['Star', 'Daisy chain', 'Mesh', 'Ring of stars'], correct: 1 },
      { q: 'Putting the BMS on its own VLAN primarily:', options: ['Speeds the chillers', 'Limits the cyber blast radius and controls cross-traffic', 'Removes controllers', 'Adds graphics'], correct: 1 },
      { q: 'Controller sizing starts from:', options: ['The brand', 'The point list I/O counts plus spare', 'The panel colour', 'The supervisor'], correct: 1 },
      { q: 'In Ghana, a near-mandatory resilience item for the head end is:', options: ['More dashboards', 'A UPS', 'Brighter graphics', 'Extra sensors'], correct: 1 },
    ],
    takeaway: 'Module 5 complete. You can now choose controllers, design the network and its segmentation, and lay out panels — the architecture under every sequence.',
    isBoss: true,
  },
];
