// Module 6 — Niagara N4
export const MODULE_6 = [
  {
    id: 'L46',
    module: 'Niagara N4',
    moduleNum: 6,
    title: 'Niagara architecture',
    duration: 8,
    hook: "Niagara N4 is the most valuable single skill in BMS. Before touching Workbench, you need its mental model: stations, hosts, and how they nest.",
    content: [
      { type: 'h3', text: 'The pieces' },
      { type: 'bullets', items: [
        '**Niagara Framework** — the software platform; vendor-neutral, runs on JACEs and on servers',
        '**Host** — the hardware and OS running Niagara: a JACE, or a Windows/Linux server',
        '**Station** — the running application: your database of points, logic, schedules, and graphics. One station per host.',
        '**Workbench** — the engineering tool you use to build and connect to stations',
      ]},
      { type: 'h3', text: 'How they relate' },
      { type: 'p', text: 'You install Workbench on your laptop. You connect to a host (a JACE). On that host you create and run a station. The station contains everything — the integration of field devices, the logic, the graphics. A Supervisor is simply a station on a server, sitting above many JACE stations.' },
      { type: 'h3', text: 'Licensing' },
      { type: 'p', text: 'Niagara is licensed per host, often by point count and feature set. Licensing limits matter at design time — running out of licensed points mid-project is a real and expensive trap.' },
      { type: 'callout', text: 'The hierarchy in one line: Workbench (your tool) connects to a Host (JACE or server) which runs a Station (the live application). Say that until it is automatic — every other Niagara concept hangs off it.' },
    ],
    quiz: [
      { q: 'The running Niagara application holding your points, logic, and graphics is the:', options: ['Host', 'Workbench', 'Station', 'Module'], correct: 2 },
      { q: 'Workbench is:', options: ['The running application', 'The engineering tool you build and connect with', 'A type of JACE', 'A protocol'], correct: 1 },
      { q: 'A Niagara Supervisor is essentially:', options: ['A field sensor', 'A station running on a server above many JACE stations', 'A wire', 'A licence file'], correct: 1 },
    ],
    takeaway: 'Niagara: Workbench (engineering tool) connects to a Host (JACE or server) running a Station (the live application). A Supervisor is a station on a server above many JACEs.',
  },
  {
    id: 'L47',
    module: 'Niagara N4',
    moduleNum: 6,
    title: 'Fox, NiagaraNetwork, modules & palettes',
    duration: 7,
    hook: "Niagara stations talk to each other, and you build with reusable parts. Four terms — Fox, NiagaraNetwork, modules, palettes — cover how.",
    content: [
      { type: 'h3', text: 'Fox & the NiagaraNetwork' },
      { type: 'bullets', items: [
        '**Fox** — Niagara’s own protocol for station-to-station communication',
        '**NiagaraNetwork** — the component in a station that connects it to other Niagara stations (a Supervisor reaching down to its JACEs)',
        'Through it, a Supervisor sees and uses points from every connected JACE station',
      ]},
      { type: 'h3', text: 'Modules' },
      { type: 'p', text: 'Niagara features come in modules — installable software components. A BACnet driver is a module; the Modbus driver is a module. The modules installed on a host determine what it can do, and module versions must be compatible across connected stations.' },
      { type: 'h3', text: 'Palettes' },
      { type: 'p', text: 'A palette is a library of pre-built components you drag into your station — logic blocks, BACnet objects, graphic widgets. Building in Niagara is largely: open the right palette, drag the component, wire it up, configure it.' },
      { type: 'callout', text: 'Two recurring Niagara headaches: module version mismatches between a Supervisor and its JACEs (keep them aligned), and forgetting which palette a component lives in. Early on, keep a personal note of which palette has what — it saves hours.' },
    ],
    quiz: [
      { q: 'Niagara stations communicate with each other using:', options: ['BACnet only', 'The Fox protocol via the NiagaraNetwork', 'Modbus', 'MQTT'], correct: 1 },
      { q: 'A Niagara driver such as BACnet is delivered as a:', options: ['Palette', 'Module', 'Station', 'Host'], correct: 1 },
      { q: 'A library of drag-in pre-built components is a:', options: ['Module', 'Palette', 'Station', 'Wire sheet'], correct: 1 },
    ],
    takeaway: 'Fox is Niagara’s station-to-station protocol via the NiagaraNetwork. Modules add features (drivers); palettes are libraries of drag-in components. Keep module versions aligned across stations.',
  },
  {
    id: 'L48',
    module: 'Niagara N4',
    moduleNum: 6,
    title: 'Workbench basics & creating a station',
    duration: 8,
    hook: "Time to drive Workbench. The first real task on any Niagara job: stand up a station and find your way around the tree.",
    content: [
      { type: 'h3', text: 'The Workbench layout' },
      { type: 'bullets', items: [
        '**Nav tree** (left) — the hierarchy of hosts, stations, and components you navigate',
        '**View pane** (centre) — shows the selected component in a chosen view (property sheet, wire sheet, graphic)',
        '**Palette side bar** — open palettes and drag components from them',
      ]},
      { type: 'h3', text: 'Creating and running a station' },
      { type: 'bullets', items: [
        'Use the New Station tool to create a station on your PC',
        'Configure it, then install it onto the host (the JACE) with the Station Copier',
        'The Platform connection manages the host itself; the Station connection manages the running application',
      ]},
      { type: 'h3', text: 'Platform vs Station — a key distinction' },
      { type: 'p', text: 'You connect to a host two ways. The Platform is the host’s management layer — install software, licences, and OS-level settings. The Station is the live application. New engineers confuse these two constantly.' },
      { type: 'callout', text: 'Remember: Platform means managing the box (licences, software, station install). Station means working in the live application (points, logic, graphics). If a tool is not where you expect, you are usually connected at the wrong level.' },
    ],
    quiz: [
      { q: 'In Workbench, you navigate the hierarchy of hosts and components using the:', options: ['View pane', 'Nav tree', 'Palette', 'Console'], correct: 1 },
      { q: 'Installing software and licences onto a JACE is done via the:', options: ['Station connection', 'Platform connection', 'Wire sheet', 'Palette'], correct: 1 },
      { q: 'Working with live points, logic, and graphics happens via the:', options: ['Platform connection', 'Station connection', 'BIOS', 'Module manager'], correct: 1 },
    ],
    takeaway: 'Workbench is the nav tree, view pane, and palettes. Connect to a host via the Platform (manage the box, licences, install) or the Station (the live application).',
  },
  {
    id: 'L49',
    module: 'Niagara N4',
    moduleNum: 6,
    title: 'Drivers & discovering devices',
    duration: 8,
    hook: "A station is useless until it can see field devices. Drivers and the learn/discover workflow are how Niagara pulls the building in.",
    content: [
      { type: 'h3', text: 'Adding a driver' },
      { type: 'p', text: 'To talk to BACnet devices you add the BacnetNetwork to your station’s Drivers folder, from the bacnet palette; for Modbus, the Modbus driver. Each network is configured with the right port and parameters.' },
      { type: 'h3', text: 'The discover / learn workflow' },
      { type: 'bullets', items: [
        '**Discover** — the driver scans the network and lists the devices it found',
        '**Add** — you select discovered devices and add them into your station',
        '**Discover points** — on each device, scan for its objects or registers',
        '**Add points** — pull the points you need into the station as proxy points',
      ]},
      { type: 'h3', text: 'Proxy points' },
      { type: 'p', text: 'A point in your Niagara station that mirrors a field device object is a proxy point. It holds the live value locally and is what your logic and graphics actually use. The driver keeps the proxy in sync with the real device.' },
      { type: 'callout', text: 'Do not blindly add every discovered point — a chiller may expose hundreds. Add what the sequence, graphics, trends, and alarms actually need. A station bloated with thousands of unused proxy points is slow, hard to read, and can blow the licence count.' },
    ],
    quiz: [
      { q: 'To make a Niagara station talk BACnet you add a:', options: ['Modbus driver', 'BacnetNetwork from the bacnet palette', 'Palette only', 'A new host'], correct: 1 },
      { q: 'A station point that mirrors a field device object is a:', options: ['Module', 'Proxy point', 'Palette', 'Schedule'], correct: 1 },
      { q: 'Adding every point a device exposes, regardless of need, risks:', options: ['Nothing', 'A slow, bloated station and a blown licence count', 'Faster comms', 'Better graphics'], correct: 1 },
    ],
    takeaway: 'Drivers (BacnetNetwork, Modbus) let a station discover and learn devices. Learned points become proxy points the station uses — add only the points you actually need.',
  },
  {
    id: 'L50',
    module: 'Niagara N4',
    moduleNum: 6,
    title: 'Wire sheets & logic',
    duration: 9,
    hook: "The wire sheet is where Niagara control logic lives — a visual canvas of blocks and links. If you can read a schematic, you can read a wire sheet.",
    content: [
      { type: 'h3', text: 'What a wire sheet is' },
      { type: 'p', text: 'Every component folder in Niagara has a wire sheet view — a 2D canvas. You drop components and draw links from one component’s output slot to another’s input slot. Data flows along the links.' },
      { type: 'h3', text: 'The building blocks' },
      { type: 'bullets', items: [
        '**Logic kit** — And, Or, Not, comparisons — boolean logic',
        '**Math kit** — add, subtract, multiply, min/max — numeric logic',
        '**kitControl** — the workhorse palette: Loop (PID), timers, sequencers, latches, reset blocks',
        '**Proxy points** — your live field values, dropped onto the sheet as logic inputs and outputs',
      ]},
      { type: 'h3', text: 'Building a loop' },
      { type: 'p', text: 'A simple cooling loop on a wire sheet: a SAT proxy point and a setpoint feed a Loop (PID) component; the Loop’s output links to the cooling-valve proxy point. That is the Module 2 sequence, built visually.' },
      { type: 'callout', text: 'Wire sheets reward tidiness. Keep flow left-to-right, group related logic, label generously, and avoid link spaghetti. A messy wire sheet works exactly as well as a clean one — until someone (you) has to debug it at 2am.' },
    ],
    quiz: [
      { q: 'A Niagara wire sheet is:', options: ['A spreadsheet', 'A visual canvas of components linked output-to-input', 'A text file', 'A graphic page'], correct: 1 },
      { q: 'The PID Loop component lives in which palette?', options: ['Logic kit', 'Math kit', 'kitControl', 'bacnet'], correct: 2 },
      { q: 'On a wire sheet, data flows:', options: ['Randomly', 'Along the links from output slots to input slots', 'Top to bottom only', 'Through the host'], correct: 1 },
    ],
    takeaway: 'The wire sheet is Niagara’s visual logic canvas — drop components (logic, math, kitControl), link output to input. Build loops by wiring proxy points through a Loop (PID) component. Keep it tidy.',
  },
  {
    id: 'L51',
    module: 'Niagara N4',
    moduleNum: 6,
    title: 'Points & extensions',
    duration: 7,
    hook: "A Niagara point is more than a value. Bolt on 'extensions' and the same point also alarms, logs history, and follows a schedule — without any extra logic.",
    content: [
      { type: 'h3', text: 'Point types' },
      { type: 'bullets', items: [
        '**Numeric, Boolean, Enum, String** points — matching the kind of value held',
        'Each exists as a Writable (you or logic can command it) or read-only variant',
      ]},
      { type: 'h3', text: 'Extensions' },
      { type: 'p', text: 'An extension is a capability you add onto a point. The point stays one object; the extension gives it a new behaviour:' },
      { type: 'bullets', items: [
        '**Alarm extension** — generates an alarm when the value crosses limits',
        '**History extension** — records the value over time for trending',
        '**Schedule** (via links) — drives the point on a time program',
      ]},
      { type: 'h3', text: 'Why this matters' },
      { type: 'p', text: 'Instead of building separate alarm and trend logic, you attach extensions directly to the point. Add a History extension to a SAT point and it trends automatically; add an Alarm extension and it alarms — clean and consistent.' },
      { type: 'callout', text: 'A disciplined Niagara engineer decides up front which points get History and Alarm extensions — driven by the point list’s history and alarm-priority columns from Module 1. Extensions are where the point list turns into a real, observable system.' },
    ],
    quiz: [
      { q: 'A Niagara extension on a point:', options: ['Replaces the point', 'Adds a capability like alarming or history to it', 'Is a separate host', 'Deletes the point'], correct: 1 },
      { q: 'To make a point record its value over time you add a:', options: ['Alarm extension', 'History extension', 'New driver', 'Palette'], correct: 1 },
      { q: 'Which point-list columns should drive your extension decisions?', options: ['Cable length', 'The history and alarm-priority columns', 'Price', 'Colour'], correct: 1 },
    ],
    takeaway: 'Niagara points (numeric, boolean, enum, string) gain behaviour from extensions — Alarm for limits, History for trending. The point list’s history/alarm columns tell you which to apply.',
  },
  {
    id: 'L52',
    module: 'Niagara N4',
    moduleNum: 6,
    title: 'Schedules, calendars & alarms',
    duration: 8,
    hook: "Buildings run on time and exceptions. Niagara's schedules, calendars, and alarm classes turn 'occupied 8 to 6, except holidays, and tell someone when it breaks' into configured objects.",
    content: [
      { type: 'h3', text: 'Schedules & calendars' },
      { type: 'bullets', items: [
        'A **Schedule** component defines occupied/unoccupied (or any value) by time of day and day of week',
        'A **Calendar** lists special days — holidays, events — that schedules reference to override normal behaviour',
        'Schedules can be mastered in a Supervisor and pushed down, or kept local to each JACE',
      ]},
      { type: 'h3', text: 'Alarm handling' },
      { type: 'bullets', items: [
        'An alarm is generated by an Alarm extension on a point',
        'It is categorized by an **Alarm Class** — which sets priority and grouping',
        'An **Alarm Console** displays them; routing can send them on by email and other channels',
        'Alarms are **acknowledged** by operators — separating seen from still-active',
      ]},
      { type: 'h3', text: 'Priority discipline' },
      { type: 'p', text: 'If everything is high priority, nothing is. Reserve high priority for things that need action now — a critical plant trip. Make routine events low priority. Good alarm design is as much about suppression as detection.' },
      { type: 'callout', text: 'Alarm fatigue is a real failure mode. An operator who gets 500 nuisance alarms a day stops reading all of them — including the one that matters. Tune priorities and limits so every alarm that fires deserves attention.' },
    ],
    quiz: [
      { q: 'Holidays that override the normal time program are held in a:', options: ['Schedule', 'Calendar', 'Alarm class', 'Wire sheet'], correct: 1 },
      { q: 'An alarm’s priority and grouping are set by its:', options: ['Host', 'Alarm Class', 'Palette', 'Driver'], correct: 1 },
      { q: 'The biggest risk of marking every alarm high priority is:', options: ['Faster response', 'Alarm fatigue — operators ignore them all', 'Lower cost', 'Nothing'], correct: 1 },
    ],
    takeaway: 'Schedules set time programs; calendars hold holiday exceptions; alarm classes set priority. Tune priorities hard — alarm fatigue makes an over-alarmed system as bad as an unmonitored one.',
  },
  {
    id: 'L53',
    module: 'Niagara N4',
    moduleNum: 6,
    title: 'Graphics — PX pages',
    duration: 8,
    hook: "Graphics are how the FM team experiences the entire BMS. In Niagara they are PX pages — and a good one turns data into instant understanding.",
    content: [
      { type: 'h3', text: 'PX pages' },
      { type: 'p', text: 'Niagara graphics are PX files, built in the PX Editor inside Workbench. A PX page is a drawing — equipment, ducts, pipes — with live data bound onto it.' },
      { type: 'h3', text: 'Bindings' },
      { type: 'p', text: 'A binding links a widget on the page to a point in the station. Bind a text widget to a SAT proxy point and it shows the live temperature; bind a valve graphic’s colour or position to the valve point and it animates. Without bindings, a PX page is just a picture.' },
      { type: 'h3', text: 'Good graphic design' },
      { type: 'bullets', items: [
        'One page per system (an AHU page, a chiller plant page) plus an overview page',
        'Show the air or water path the way it physically flows',
        'Use colour with meaning, and sparingly — green everywhere tells you nothing',
        'Make abnormal states obvious at a glance — that is the whole point of a graphic',
      ]},
      { type: 'callout', text: 'The test of a graphic: can an operator glance at it and know in two seconds whether the system is healthy? If they have to hunt and read numbers, the graphic has failed its job. Design for the abnormal case, not the pretty screenshot.' },
    ],
    quiz: [
      { q: 'Niagara graphics pages, built in the PX Editor, are called:', options: ['Wire sheets', 'PX pages', 'Palettes', 'Modules'], correct: 1 },
      { q: 'The link that makes a graphic widget show a live value is a:', options: ['Module', 'Binding', 'Extension', 'Schedule'], correct: 1 },
      { q: 'A good operator graphic is designed primarily so that:', options: ['It looks pretty', 'Abnormal states are obvious at a glance', 'It has many colours', 'It hides data'], correct: 1 },
    ],
    takeaway: 'Niagara graphics are PX pages; bindings link widgets to live points. Design graphics so an operator can see system health at a glance — abnormal states must jump out.',
  },
  {
    id: 'L54',
    module: 'Niagara N4',
    moduleNum: 6,
    title: 'Tags & hierarchies (Haystack)',
    duration: 7,
    hook: "A modern Niagara station does not just hold points — it describes them. Tagging turns a pile of points into data that analytics and other tools can understand.",
    content: [
      { type: 'h3', text: 'The problem tags solve' },
      { type: 'p', text: 'A point named AHU1_SAT means something to you and nothing to software. Tags attach standardized metadata — this point is a sensor, measures air, measures temperature, belongs to AHU-1. Now software can find every supply air temperature without parsing names.' },
      { type: 'h3', text: 'Project Haystack & hierarchies' },
      { type: 'bullets', items: [
        '**Project Haystack** — an open tagging standard (a semantic data model) that Niagara supports',
        'Tags plus relationships let you build hierarchies — navigate Site to Building to Floor to Equipment to Point',
        'This is the foundation for analytics and FDD (Module 9) and for portfolio-scale dashboards',
      ]},
      { type: 'h3', text: 'Why it is worth the effort' },
      { type: 'p', text: 'Tagging is upfront discipline that pays off later. An untagged station works, but every analytics tool, every report, and every new dashboard then needs hand-mapping. A well-tagged station is reusable and machine-readable.' },
      { type: 'callout', text: 'Tagging is the bridge between a BMS that runs a building and a BMS that produces data products. For Yakuver thinking beyond installation — analytics, dashboards, recurring services — consistent tagging from day one is the enabling asset.' },
    ],
    quiz: [
      { q: 'Tags on a point provide:', options: ['A nicer name', 'Standardized machine-readable metadata about what the point is', 'Faster comms', 'A graphic'], correct: 1 },
      { q: 'The open semantic tagging standard Niagara supports is:', options: ['BACnet', 'Project Haystack', 'Modbus', 'Fox'], correct: 1 },
      { q: 'A well-tagged station mainly makes which future work easier?', options: ['Wiring', 'Analytics, reporting, and new dashboards', 'Power supply', 'Painting panels'], correct: 1 },
    ],
    takeaway: 'Tags attach standardized, machine-readable meaning to points (Project Haystack). They enable hierarchies, analytics/FDD, and reusable dashboards — upfront discipline that pays off later.',
  },
  {
    id: 'L55',
    module: 'Niagara N4',
    moduleNum: 6,
    title: 'Module 6 boss check',
    duration: 14,
    hook: "End of Module 6 — Niagara N4. The highest-ROI skill in BMS, and the heart of the TCP exam. Let's check it.",
    content: [
      { type: 'h3', text: 'Module 6 recap' },
      { type: 'p', text: 'You covered Niagara architecture (Workbench, host, station), Fox and the NiagaraNetwork, modules and palettes, creating a station and the Platform/Station split, drivers and proxy points, wire sheets and logic, points and extensions, schedules/calendars/alarms, PX graphics and bindings, and tagging with Project Haystack.' },
      { type: 'p', text: 'This boss check has 8 questions across all of Module 6. Pass at 75% (6/8) to unlock Module 7. Treat it like a TCP practice section.' },
      { type: 'callout', text: 'Nothing replaces hands-on practice. After this module, download Niagara Workbench, build a demo station, and work toward sitting the TCP exam — that is the credential.' },
    ],
    quiz: [
      { q: 'The running Niagara application is the:', options: ['Host', 'Station', 'Workbench', 'Palette'], correct: 1 },
      { q: 'Niagara stations communicate with each other over:', options: ['Modbus', 'Fox via the NiagaraNetwork', 'DALI', 'KNX'], correct: 1 },
      { q: 'Installing licences and software onto a JACE uses the:', options: ['Station connection', 'Platform connection', 'Wire sheet', 'PX editor'], correct: 1 },
      { q: 'A station point mirroring a field device object is a:', options: ['Palette', 'Proxy point', 'Module', 'Tag'], correct: 1 },
      { q: 'The PID Loop component is found in which palette?', options: ['Logic kit', 'kitControl', 'Math kit', 'bacnet'], correct: 1 },
      { q: 'To make a point trend its value over time you add a:', options: ['Alarm extension', 'History extension', 'New driver', 'Calendar'], correct: 1 },
      { q: 'A graphic widget shows a live value because of a:', options: ['Module', 'Binding', 'Schedule', 'Host'], correct: 1 },
      { q: 'The open tagging standard that enables analytics on a station is:', options: ['BACnet', 'Project Haystack', 'Fox', 'IPMVP'], correct: 1 },
    ],
    takeaway: 'Module 6 complete. You have the Niagara N4 mental model end to end — now get hands-on in Workbench and aim for the TCP certification.',
    isBoss: true,
  },
];
