// Module 7 — Design & Engineering
export const MODULE_7 = [
  {
    id: 'L56',
    module: 'Design',
    moduleNum: 7,
    title: 'BMS scope & reading drawings',
    duration: 8,
    hook: "Before a single point is priced, someone defines what the BMS does and does not cover. Get scope wrong and the whole job bleeds money.",
    content: [
      { type: 'h3', text: 'Defining BMS scope' },
      { type: 'bullets', items: [
        'List every system the BMS monitors or controls — AHUs, chillers, pumps, VRF, lighting, metering, generators',
        'For each: monitor only, or full control? Integrated over the network, or hardwired?',
        'State the interfaces with other trades — fire alarm, electrical, lifts, security',
        'State exclusions explicitly — what is NOT in scope',
      ]},
      { type: 'h3', text: 'Reading the other trades’ drawings' },
      { type: 'bullets', items: [
        '**Mechanical** drawings — the equipment and systems you will control',
        '**Electrical** drawings — power to panels, motor starters, the fire alarm interface',
        '**Architectural** drawings — zones, ceilings, where sensors and panels physically go',
      ]},
      { type: 'h3', text: 'Coordination' },
      { type: 'p', text: 'BMS sits on top of every other trade, so BMS design is mostly coordination. The point list cannot be finished until the mechanical schedule is firm; panel locations need the architect; the fire interface needs the electrical contractor.' },
      { type: 'callout', text: 'Scope creep is the silent killer of BMS margin. Every casual “can you just also integrate the...” is a variation. Write exclusions as carefully as inclusions, and price changes as changes — the SOO and point list are your evidence.' },
    ],
    quiz: [
      { q: 'BMS design is described as mostly:', options: ['Wiring', 'Coordination — it sits on top of every other trade', 'Painting', 'Sales'], correct: 1 },
      { q: 'Which drawings tell you where sensors and panels physically go?', options: ['Mechanical', 'Electrical', 'Architectural', 'None of them'], correct: 2 },
      { q: 'The silent killer of BMS project margin is:', options: ['Good drawings', 'Scope creep — unpriced additions', 'Too many sensors', 'Fast handover'], correct: 1 },
    ],
    takeaway: 'BMS scope lists every system, whether monitored or controlled, plus explicit exclusions. BMS design is coordination across mechanical, electrical, and architectural drawings — and scope creep destroys margin.',
  },
  {
    id: 'L57',
    module: 'Design',
    moduleNum: 7,
    title: 'Point lists deep dive',
    duration: 8,
    hook: "Module 1 introduced the point list. Now you build one properly — because it is the document the whole project is priced, sized, and commissioned from.",
    content: [
      { type: 'h3', text: 'From equipment to points' },
      { type: 'p', text: 'For each piece of equipment, walk its control story and write down every signal it implies. An AHU needs SAT (AI), cooling valve (AO), fan VFD (AO plus status DIs), dampers (AO times three), safeties (DI times three), and more — recall the roughly 30-point AHU from Module 1.' },
      { type: 'h3', text: 'Physical vs software points' },
      { type: 'bullets', items: [
        '**Physical** points consume real I/O and a cable — AI/AO/DI/DO',
        '**Software** points (setpoints, modes, calculated values, alarms) cost no I/O but still need listing — they are real engineering work',
      ]},
      { type: 'h3', text: 'The point list as a hub' },
      { type: 'bullets', items: [
        'Drives **pricing** (dollar-per-point) and **controller sizing** (I/O counts plus 20%)',
        'Drives **cable schedules** and containment design',
        'Becomes the **commissioning checklist** — every physical point gets tested',
        'Maps to **Niagara proxy points** and to graphic bindings',
      ]},
      { type: 'callout', text: 'Build vendor-neutral point list templates per equipment type — AHU, chiller, FCU, VRF, pump set, lighting. Reusing a refined template instead of starting blank each time is the difference between a slow estimator and a fast, accurate one. This is reusable IP for Yakuver.' },
    ],
    quiz: [
      { q: 'A setpoint or calculated value with no wire is:', options: ['A physical point consuming I/O', 'A software point — no I/O but still listed', 'Not a point at all', 'A cable'], correct: 1 },
      { q: 'The point list directly drives all of these EXCEPT:', options: ['Pricing', 'Controller sizing', 'The commissioning checklist', 'The building’s architectural style'], correct: 3 },
      { q: 'The fastest, most accurate estimating comes from:', options: ['Starting each point list blank', 'Reusing refined per-equipment templates', 'Guessing', 'Copying a competitor'], correct: 1 },
    ],
    takeaway: 'A point list captures every physical (I/O-consuming) and software point per equipment. It is the hub for pricing, sizing, cabling, and commissioning — build reusable templates per equipment type.',
  },
  {
    id: 'L58',
    module: 'Design',
    moduleNum: 7,
    title: 'Point naming conventions',
    duration: 6,
    hook: "A thousand-point building with inconsistent names is a building no one can navigate. A naming convention is boring, unglamorous, and one of the highest-leverage decisions on the job.",
    content: [
      { type: 'h3', text: 'What a good convention gives you' },
      { type: 'bullets', items: [
        'Predictability — you can guess a point’s name correctly without looking it up',
        'Sortability — points group logically in lists and trees',
        'Machine-readability — it pairs with tagging for analytics',
      ]},
      { type: 'h3', text: 'A typical structure' },
      { type: 'p', text: 'Most conventions are hierarchical and delimited: Building - System/Equipment - Component - Measurement. For example AHU01_SAT, AHU01_CLGVLV, CH02_STATUS, VAV-3F-12_FLOW.' },
      { type: 'bullets', items: [
        'Fixed abbreviations — SAT, RAT, CLG, HTG, VLV, DMP, SP, STS',
        'Consistent equipment numbering, zero-padded (AHU01 not AHU1) so they sort correctly',
        'Encode location where useful — 3F for third floor',
      ]},
      { type: 'h3', text: 'Decide once, apply everywhere' },
      { type: 'p', text: 'The convention must be agreed before the point list is written, and then applied identically across the point list, the controllers, the Niagara station, the graphics, and the trends. Changing it midway is painful and error-prone.' },
      { type: 'callout', text: 'Whatever convention you pick, write it down as a one-page standard and reuse it on every Yakuver project. Consistency across projects is worth more than any single perfect scheme — it makes your firm’s deliverables instantly recognizable and maintainable.' },
    ],
    quiz: [
      { q: 'Equipment numbers should be zero-padded (AHU01, not AHU1) mainly so that:', options: ['They look nicer', 'They sort correctly in lists and trees', 'They are shorter', 'BACnet requires it'], correct: 1 },
      { q: 'The point naming convention should be agreed:', options: ['After commissioning', 'Before the point list is written', 'By each installer separately', 'Never'], correct: 1 },
      { q: 'Across projects, what matters most for naming?', options: ['A unique scheme each time', 'Consistency — one documented standard reused everywhere', 'The longest possible names', 'Random variety'], correct: 1 },
    ],
    takeaway: 'A good point naming convention is hierarchical, delimited, abbreviation-consistent, and zero-padded. Agree it before the point list and apply it identically everywhere — reuse one standard across all projects.',
  },
  {
    id: 'L59',
    module: 'Design',
    moduleNum: 7,
    title: 'Writing a Sequence of Operation',
    duration: 10,
    hook: "Module 1 explained what an SOO is. Now you write one. This is the single most billable, most leverage-rich skill in BMS engineering.",
    content: [
      { type: 'h3', text: 'The writing process' },
      { type: 'bullets', items: [
        'One SOO section per equipment type or system',
        'State the equipment and what it serves, then the modes, then the setpoints',
        'Write each mode’s control as numbered, testable steps',
        'Add safeties and interlocks, alarms, and failure modes',
      ]},
      { type: 'h3', text: 'Make every line testable' },
      { type: 'p', text: 'The test of an SOO line: can a commissioning engineer prove it true or false on site? "Maintains comfort" is untestable. "Cooling valve PID modulates 0 to 100% to hold SAT at 13 degrees plus or minus 0.5" is testable — it has a control element, a target, and a tolerance.' },
      { type: 'h3', text: 'ASHRAE Guideline 36' },
      { type: 'p', text: 'Guideline 36 provides proven, detailed standard sequences for common HVAC equipment. Start from G36 rather than a blank page — adapt it to the project instead of reinventing (and re-debugging) sequences the industry already solved.' },
      { type: 'callout', text: 'Untestable SOO language causes about 90% of commissioning disputes (Module 1). The discipline: every sentence names the controlled element, the target, and the tolerance or condition. If you cannot tick it on a checklist, rewrite it.' },
    ],
    quiz: [
      { q: 'The test of a well-written SOO line is that it:', options: ['Sounds professional', 'Can be proven true or false on site', 'Is short', 'Names a brand'], correct: 1 },
      { q: 'ASHRAE Guideline 36 gives you:', options: ['Pricing data', 'Proven standard HVAC control sequences to adapt', 'Cybersecurity rules', 'Cable sizes'], correct: 1 },
      { q: '"The AHU maintains occupant comfort" is:', options: ['A good SOO line', 'An untestable line — no element, target, or tolerance', 'A setpoint', 'An alarm'], correct: 1 },
    ],
    takeaway: 'Write the SOO per system — modes, setpoints, numbered sequences, safeties, failure modes. Every line must name a controlled element, a target, and a tolerance. Start from ASHRAE Guideline 36.',
  },
  {
    id: 'L60',
    module: 'Design',
    moduleNum: 7,
    title: 'Controls drawings',
    duration: 7,
    hook: "The SOO says what the building does; the controls drawings say how it is wired. Four drawing types carry a BMS design from paper to a working panel.",
    content: [
      { type: 'h3', text: 'The drawing set' },
      { type: 'bullets', items: [
        '**Riser / architecture diagram** — the whole BMS network: controllers, buses, how they connect across floors. The one-page big picture.',
        '**Schematic / control diagram** — per equipment: every point, every terminal, every field device wired to the controller',
        '**Wiring / termination drawings** — the installer’s exact terminal-by-terminal guide',
        '**Panel layout drawings** — the physical arrangement inside each panel',
      ]},
      { type: 'h3', text: 'Title blocks & revision control' },
      { type: 'p', text: 'Every drawing carries a title block: project, drawing number, revision, date, who drew and who checked it. Revision control matters — the installer must always be building from the current issue, not a superseded one.' },
      { type: 'h3', text: 'Drawings and the point list agree' },
      { type: 'p', text: 'The point list, the schematics, the panel layout, and the live system must all tell the same story — same tags, same terminals. A discrepancy between them is a site error waiting to happen.' },
      { type: 'callout', text: 'As-built discipline: when wiring changes on site (and it always does), the drawings must be updated to match. A drawing set that no longer reflects reality is worse than none — it actively misleads the next engineer.' },
    ],
    quiz: [
      { q: 'The single-page big picture of the whole BMS network is the:', options: ['Panel layout', 'Riser or architecture diagram', 'Wiring drawing', 'Title block'], correct: 1 },
      { q: 'The installer’s exact terminal-by-terminal guide is the:', options: ['Riser diagram', 'Wiring / termination drawing', 'SOO', 'Point list'], correct: 1 },
      { q: 'When site wiring changes during install, the drawings should be:', options: ['Left as designed', 'Updated to as-built so they still match reality', 'Discarded', 'Hidden'], correct: 1 },
    ],
    takeaway: 'BMS controls drawings: riser (network overview), schematics (per-equipment points), wiring/termination (installer guide), panel layout (physical). All must agree with the point list — and be kept as-built.',
  },
  {
    id: 'L61',
    module: 'Design',
    moduleNum: 7,
    title: 'The BOQ structure',
    duration: 8,
    hook: "The Bill of Quantities is where the design becomes a number. Structure it well and you can defend every line; structure it badly and you lose money you cannot even find.",
    content: [
      { type: 'h3', text: 'The BOQ split' },
      { type: 'bullets', items: [
        '**Hardware** — controllers, sensors, actuators, valves, panels, cabling, network gear',
        '**Software & licensing** — supervisor and Niagara licences, graphics, integration drivers',
        '**Labour** — design, installation, programming, commissioning, project management',
      ]},
      { type: 'h3', text: 'From point list to BOQ' },
      { type: 'p', text: 'The point list drives the hardware count and a first-pass estimate (dollar-per-point). But labour — especially programming and commissioning — is estimated separately; it does not scale linearly with point count. A few complex sequences can cost more than hundreds of simple points.' },
      { type: 'h3', text: 'Do not forget the invisible lines' },
      { type: 'bullets', items: [
        'Spares — recommended spare controllers, sensors, modules',
        'Network infrastructure — switches, containment, UPS',
        'Testing and commissioning time — frequently underestimated',
        'Training and documentation — real deliverables with real hours',
      ]},
      { type: 'callout', text: 'The most under-priced BOQ lines are commissioning and programming time. They are invisible until the end of the job — exactly when an under-estimate hurts most. Estimate them from the SOO complexity, not as a percentage of hardware.' },
    ],
    quiz: [
      { q: 'A BMS BOQ splits broadly into:', options: ['Only hardware', 'Hardware, software & licensing, and labour', 'Only labour', 'Sensors and cable'], correct: 1 },
      { q: 'Programming and commissioning labour, relative to point count:', options: ['Scales exactly linearly', 'Does not scale linearly — complex sequences cost more', 'Is always free', 'Equals the hardware cost'], correct: 1 },
      { q: 'The most commonly under-priced BOQ lines are:', options: ['Sensors', 'Commissioning and programming time', 'Cable', 'Panels'], correct: 1 },
    ],
    takeaway: 'A BMS BOQ splits into hardware, software/licensing, and labour. The point list drives hardware; programming and commissioning labour must be estimated from sequence complexity — and are the lines most often under-priced.',
  },
  {
    id: 'L62',
    module: 'Design',
    moduleNum: 7,
    title: 'Ghana pricing factors',
    duration: 7,
    hook: "A BMS BOQ that works in London loses money in Accra. Ghana-specific cost realities have to be designed into the price, not discovered after.",
    content: [
      { type: 'h3', text: 'Import and currency factors' },
      { type: 'bullets', items: [
        'Most BMS hardware is imported — import duties, shipping, and clearing add real cost',
        'Currency — pricing in GHS against USD or EUR-denominated equipment exposes you to exchange-rate swings between quote and purchase',
        'Lead times are long — quote validity and delivery clauses matter',
      ]},
      { type: 'h3', text: 'Local cost realities' },
      { type: 'bullets', items: [
        'Skilled BMS labour is scarce and therefore not cheap — do not assume cheap local labour',
        'Power instability means UPS and generator-interface costs are normal line items',
        'Site conditions — heat, dust, humidity — push toward higher ingress-protection enclosures',
      ]},
      { type: 'h3', text: 'Margin & risk' },
      { type: 'p', text: 'Build explicit contingency for currency and lead-time risk into the price, and keep quote validity short. A margin that looks healthy can be entirely eaten by a cedi move between winning the job and buying the kit.' },
      { type: 'callout', text: 'Price in the currency you incur the cost in, or hedge the gap explicitly. The most avoidable loss on a Ghana BMS job is an exchange-rate move on imported hardware between quote and order — protect against it in the commercial terms.' },
    ],
    quiz: [
      { q: 'Because most BMS hardware is imported into Ghana, the BOQ must include:', options: ['Nothing extra', 'Import duties, shipping, and clearing costs', 'Only labour', 'A discount'], correct: 1 },
      { q: 'A common Ghana-specific BMS line item driven by power instability is:', options: ['Extra graphics', 'UPS and generator-interface provision', 'More paint', 'Cheaper sensors'], correct: 1 },
      { q: 'The most avoidable loss on a Ghana BMS job is:', options: ['Too many sensors', 'An exchange-rate move on imported kit between quote and order', 'Fast commissioning', 'Good drawings'], correct: 1 },
    ],
    takeaway: 'Ghana BMS pricing must absorb import duties, currency risk, long lead times, scarce skilled labour, and power-related kit (UPS). Protect the margin against cedi moves between quote and purchase.',
  },
  {
    id: 'L63',
    module: 'Design',
    moduleNum: 7,
    title: 'Spare I/O strategy & coordination',
    duration: 7,
    hook: "The cheapest capacity you will ever buy is spare capacity bought at design time. The most expensive is the same capacity bought after handover.",
    content: [
      { type: 'h3', text: 'Why spares matter' },
      { type: 'bullets', items: [
        'Buildings change — tenants fit out, equipment gets added, scope grows',
        'Adding a point to a controller with spare I/O is trivial; adding one to a full controller means a new controller, panel space, and a site visit',
        'About 20% spare I/O is the standard rule (Module 1) — per controller, not just per building',
      ]},
      { type: 'h3', text: 'Spare beyond I/O' },
      { type: 'bullets', items: [
        'Physical panel space and spare DIN rail',
        'Spare cable cores and containment capacity',
        'Niagara licence headroom — spare licensed points',
        'A recommended set of spare parts for the FM team',
      ]},
      { type: 'h3', text: 'Coordination timing' },
      { type: 'p', text: 'Spare strategy ties back to coordination — you cannot finalize controller sizing until the mechanical schedule is firm, and you add the spare on top of the firm count, not instead of confirming it.' },
      { type: 'callout', text: 'Frame spare capacity to the client as cheap insurance: a small percentage now versus a controller-plus-truck-roll later. It is an easy, honest value argument — and a building designed with headroom reflects well on Yakuver years after handover.' },
    ],
    quiz: [
      { q: 'The standard spare I/O rule is roughly:', options: ['0%', '20% spare per controller', '100%', 'Only at building level'], correct: 1 },
      { q: 'Adding a point to an already-full controller typically requires:', options: ['Nothing', 'A new controller, panel space, and a site visit', 'Just software', 'A reboot'], correct: 1 },
      { q: 'Spare capacity should also be planned for all of these EXCEPT:', options: ['Panel space', 'Cable cores and licence headroom', 'The building’s paint colour', 'Spare parts'], correct: 2 },
    ],
    takeaway: 'Plan about 20% spare I/O per controller, plus spare panel space, cable cores, licence headroom, and parts. Spare bought at design time is cheap insurance against costly post-handover changes.',
  },
  {
    id: 'L64',
    module: 'Design',
    moduleNum: 7,
    title: 'Module 7 boss check',
    duration: 10,
    hook: "End of Module 7 — Design & Engineering. Turning intent into priced, buildable deliverables. Let's check it.",
    content: [
      { type: 'h3', text: 'Module 7 recap' },
      { type: 'p', text: 'You covered BMS scope and reading drawings, building point lists, naming conventions, writing the Sequence of Operation, controls drawings, the BOQ structure, Ghana pricing factors, and spare I/O strategy.' },
      { type: 'p', text: 'This boss check has 7 questions across all of Module 7. Pass at 75% (6/7) to unlock Module 8.' },
      { type: 'callout', text: 'These are the deliverables clients actually pay for. A clean point list, a testable SOO, and a defensible BOQ are exactly what lets Yakuver bid BMS scope with confidence.' },
    ],
    quiz: [
      { q: 'BMS design work is mostly:', options: ['Wiring', 'Coordination across the other trades', 'Sales', 'Painting'], correct: 1 },
      { q: 'A setpoint with no physical wire is recorded on the point list as a:', options: ['Physical AI', 'Software point', 'Cable', 'Nothing'], correct: 1 },
      { q: 'A good SOO line always specifies a controlled element, a target, and a:', options: ['Brand', 'Tolerance or condition', 'Price', 'Colour'], correct: 1 },
      { q: 'The one-page overview of the whole BMS network is the:', options: ['Panel layout', 'Riser / architecture diagram', 'BOQ', 'Title block'], correct: 1 },
      { q: 'The most commonly under-priced BOQ lines are:', options: ['Sensors and cable', 'Programming and commissioning labour', 'Panels', 'Controllers'], correct: 1 },
      { q: 'For a Ghana BMS quote, a key risk to hedge is:', options: ['Too many drawings', 'Currency movement on imported hardware', 'Fast handover', 'Spare I/O'], correct: 1 },
      { q: 'The standard spare I/O allowance per controller is about:', options: ['0%', '20%', '200%', 'None'], correct: 1 },
    ],
    takeaway: 'Module 7 complete. You can define scope, build point lists, write testable SOOs, produce controls drawings, and price a BMS job for the Ghana market.',
    isBoss: true,
  },
];
