// ============================================================================
// LESSON CONTENT
// Modules 1 & 2 are defined inline below; Modules 3-10 live in ./lessons/*
// Content block types: h3 | p | bullets | callout | diagram
// ============================================================================

import { MODULE_3 } from './lessons/module3.js';
import { MODULE_4 } from './lessons/module4.js';
import { MODULE_5 } from './lessons/module5.js';
import { MODULE_6 } from './lessons/module6.js';
import { MODULE_7 } from './lessons/module7.js';
import { MODULE_8 } from './lessons/module8.js';
import { MODULE_9 } from './lessons/module9.js';
import { MODULE_10 } from './lessons/module10.js';

const CORE = [
  {
    id: 'L1',
    module: 'Foundations',
    moduleNum: 1,
    title: 'What is a BMS, really?',
    duration: 6,
    hook: "A 30-story office tower in Accra runs ~$80,000 of electricity a month. The BMS is the silent system deciding when the chillers run, how fast pumps spin, and whether the lights dim at 6pm. Get it wrong and you burn money. Get it right and you have a quiet, comfortable, efficient building no one notices.",
    content: [
      { type: 'h3', text: 'Three terms, often confused' },
      { type: 'p', text: 'You will hear BMS, BAS, and SCADA used interchangeably. They are not quite the same.' },
      { type: 'bullets', items: [
        '**BMS (Building Management System)** — the umbrella term, common in UK/EU/Africa. Covers HVAC, lighting, metering, sometimes security and fire.',
        '**BAS (Building Automation System)** — the US-preferred term. Functionally identical to BMS in most usage.',
        '**SCADA (Supervisory Control and Data Acquisition)** — industrial cousin. Same architecture, but applied to factories, water plants, oil & gas. BMS is essentially SCADA for buildings.',
      ]},
      { type: 'h3', text: 'What a BMS actually does' },
      { type: 'p', text: 'A BMS is a distributed network of controllers, sensors, and actuators that monitors and adjusts a building\'s mechanical and electrical systems in real time. It exists to deliver four outcomes:' },
      { type: 'bullets', items: [
        '**Comfort** — temperature, humidity, fresh air, lighting at the right level',
        '**Efficiency** — minimum energy use to deliver the comfort',
        '**Safety** — smoke control, freeze protection, leak detection',
        '**Compliance** — logs, trends, alarms for audits and regulations',
      ]},
      { type: 'callout', text: 'The MEP engineer designs the systems. The BMS engineer makes them behave intelligently. Without the BMS, you have a Ferrari engine being driven by someone with no steering wheel.' },
    ],
    quiz: [
      {
        q: 'Which statement best describes the relationship between BMS and BAS?',
        options: ['BMS controls hardware, BAS controls software', 'They are essentially the same thing, with regional naming differences', 'BAS is older technology that BMS replaced', 'BMS only does HVAC, BAS does everything'],
        correct: 1,
      },
      {
        q: 'Which of these is NOT one of the four core outcomes a BMS exists to deliver?',
        options: ['Comfort', 'Efficiency', 'Aesthetic design', 'Compliance'],
        correct: 2,
      },
      {
        q: 'A BMS is most architecturally similar to which industrial system?',
        options: ['ERP', 'CRM', 'SCADA', 'PLM'],
        correct: 2,
      },
    ],
    takeaway: 'A BMS is the intelligence layer that makes a building\'s MEP systems behave with purpose — for comfort, efficiency, safety, and compliance.',
  },
  {
    id: 'L2',
    module: 'Foundations',
    moduleNum: 1,
    title: 'The 3-tier architecture',
    duration: 8,
    hook: "Every BMS on Earth — from a $5k clinic system to a $5M airport stack — follows the same three-tier shape. Once you see it, you can walk into any building and instantly know where to look for what.",
    content: [
      { type: 'h3', text: 'The three tiers' },
      { type: 'p', text: 'BMS architecture is always pyramidal. Bottom tier is many, top tier is few.' },
      { type: 'diagram', kind: 'tiers' },
      { type: 'h3', text: 'Tier 1 — Field layer' },
      { type: 'p', text: 'The "hands and eyes." Hundreds or thousands of devices physically attached to your HVAC equipment.' },
      { type: 'bullets', items: [
        'Sensors — temperature, humidity, pressure, CO2, flow, occupancy',
        'Actuators — valve actuators, damper actuators, VFDs',
        'Meters — power, water, gas, BTU',
        'These devices speak simple signals: 0–10V, 4–20mA, dry contacts',
      ]},
      { type: 'h3', text: 'Tier 2 — Automation layer' },
      { type: 'p', text: 'The "brains in the field." DDC controllers that run sequences of operation locally.' },
      { type: 'bullets', items: [
        'Application-Specific Controllers (ASCs) — for VAVs, FCUs, small fixed-function devices',
        'Field controllers / B-BCs — programmable, run AHUs, chillers, plant rooms',
        'They execute PID loops, schedules, and interlocks autonomously',
        'Critical: if the supervisor crashes, this tier keeps the building running',
      ]},
      { type: 'h3', text: 'Tier 3 — Management/Supervisory layer' },
      { type: 'p', text: 'The "control room." Servers and workstations where humans interact with the system.' },
      { type: 'bullets', items: [
        'Graphical dashboards showing plant status',
        'Schedules and setpoint management',
        'Alarms and event routing (email, SMS)',
        'Trend logs and energy reports',
        'Remote access for FM teams',
      ]},
      { type: 'callout', text: 'Rule of thumb: tier 1 = thousands of points, tier 2 = tens of controllers, tier 3 = one or two servers. Money flows the opposite direction — tier 3 software licenses are often the most expensive single line item.' },
    ],
    quiz: [
      {
        q: 'A pressure sensor wired to a JACE controller via BACnet MS/TP belongs to which tier?',
        options: ['Field layer (Tier 1)', 'Automation layer (Tier 2)', 'Supervisory layer (Tier 3)', 'It spans Tier 1 and Tier 2'],
        correct: 0,
      },
      {
        q: 'If the supervisory server crashes, what happens to control of the AHU?',
        options: ['AHU shuts down', 'AHU continues running its sequence from the field controller', 'Building enters fire mode', 'Sensors stop sending data'],
        correct: 1,
      },
      {
        q: 'A Niagara JACE 8000 is best described as a:',
        options: ['Field sensor', 'Field controller / supervisor hybrid', 'Pure cloud service', 'Type of actuator'],
        correct: 1,
      },
    ],
    takeaway: 'BMS is a 3-tier pyramid: many sensors/actuators (field), fewer controllers (automation), one or two supervisors. The middle tier keeps the building alive if the top tier dies.',
  },
  {
    id: 'L3',
    module: 'Foundations',
    moduleNum: 1,
    title: 'Why BMS exists — the business case',
    duration: 5,
    hook: "Selling BMS is hard because clients see it as a cost, not an asset. Knowing the four arguments cold is the difference between winning the scope and losing it to the lowest-bid 'we'll just put a thermostat on it' contractor.",
    content: [
      { type: 'h3', text: 'The four business cases' },
      { type: 'p', text: 'Every BMS scope you ever pitch will land on one or more of these. Memorize them.' },
      { type: 'bullets', items: [
        '**Energy savings** — a properly commissioned BMS typically saves 15–30% on HVAC energy versus no controls. In Ghana, with ECG tariffs at ~GHS 2.5/kWh for commercial, this is real money fast.',
        '**Comfort and tenant satisfaction** — fewer hot/cold complaints, better IAQ, more productive staff. Hard to measure but devastating when missing.',
        '**Operational efficiency** — FM team monitors and adjusts remotely; preventive maintenance via trend analysis; faster fault diagnosis.',
        '**Compliance and reporting** — energy audits, sustainability ratings (EDGE, LEED), regulatory disclosure. Increasingly important even in Ghana.',
      ]},
      { type: 'h3', text: 'The Ghana-specific case' },
      { type: 'bullets', items: [
        'Power tariff structure rewards demand management (peak shaving)',
        'Diesel generator costs make every kWh of grid power saved worth more',
        'Heat and humidity make HVAC the dominant energy load — BMS impact is huge',
        'Skilled FM labor is scarce — remote monitoring multiplies one good engineer',
      ]},
      { type: 'callout', text: 'Pitch tip: lead with energy savings (concrete numbers), close with operational efficiency (peace of mind). Comfort and compliance are bonuses that don\'t sell on their own.' },
    ],
    quiz: [
      {
        q: 'Typical HVAC energy savings from a properly commissioned BMS is:',
        options: ['1–5%', '15–30%', '50–70%', '90%+'],
        correct: 1,
      },
      {
        q: 'Which business case is usually the strongest opener when selling BMS scope?',
        options: ['Aesthetic appeal of dashboards', 'Energy savings with concrete numbers', 'Compliance requirements', 'It makes the building look modern'],
        correct: 1,
      },
    ],
    takeaway: 'Four reasons BMS exists: energy savings, comfort, operational efficiency, compliance. Lead pitches with energy, close with operations.',
  },
  {
    id: 'L4',
    module: 'Foundations',
    moduleNum: 1,
    title: 'Open vs closed loop control',
    duration: 7,
    hook: "Your bathroom shower mixer is closed-loop control. Your kettle is open-loop. The difference between these two ideas explains 80% of why BMS systems fail.",
    content: [
      { type: 'h3', text: 'Open loop' },
      { type: 'p', text: 'Open loop control means: you send a command, and trust it produced the desired result. There is no feedback.' },
      { type: 'p', text: 'Example: a kettle. You press "on" for 3 minutes. You trust the water is hot. The kettle does not measure water temperature — it just heats.' },
      { type: 'p', text: 'In BMS: a damper actuator told to drive to 50% open. We assume it got there. No position feedback.' },
      { type: 'h3', text: 'Closed loop' },
      { type: 'p', text: 'Closed loop means: you measure the result, compare to your goal, adjust until they match. The "loop" is sensor → controller → actuator → process → back to sensor.' },
      { type: 'p', text: 'Example: a shower mixer with a thermostat. You set 38°C. The mixer measures water temperature continuously and adjusts the hot/cold blend to hold 38°C even when someone flushes a toilet upstream.' },
      { type: 'p', text: 'In BMS: an AHU supply air sensor reads 16°C, setpoint is 13°C, controller opens the chilled water valve more. Sensor reads 13°C, valve modulates to hold position.' },
      { type: 'h3', text: 'Vocabulary you must know cold' },
      { type: 'bullets', items: [
        '**Setpoint (SP)** — the goal value (e.g. 13°C supply air)',
        '**Process variable (PV)** — what you actually measure (e.g. 16°C actual)',
        '**Error** — the difference (SP − PV = 3°C in this case)',
        '**Control output (CO)** — what the controller drives in response (e.g. valve at 67% open)',
      ]},
      { type: 'callout', text: 'Almost every "BMS not working" complaint is really a closed-loop problem: sensor drifted, valve stuck, controller tuning wrong, or the loop was never properly closed in the first place. Train your ear for "sensor / setpoint / output" — if you can\'t name all three, you can\'t fix the problem.' },
    ],
    quiz: [
      {
        q: 'A motorized damper actuator with no position feedback being driven to 70% is an example of:',
        options: ['Open loop', 'Closed loop', 'Cascade loop', 'Feedforward'],
        correct: 0,
      },
      {
        q: 'In the equation Error = Setpoint − Process Variable, if SP is 22°C and PV is 24°C, the error is:',
        options: ['+2°C (heating needed)', '−2°C (cooling needed)', '0°C (at setpoint)', 'Cannot be determined'],
        correct: 1,
      },
      {
        q: 'Which of these is closed loop?',
        options: ['A timer-based exhaust fan running 8am–6pm', 'A space temperature sensor adjusting a VAV damper to hold 22°C', 'A light switch', 'A pump set to constant speed'],
        correct: 1,
      },
    ],
    takeaway: 'Closed loop = measure, compare, adjust. Open loop = command and pray. Almost all BMS control is (and should be) closed loop.',
  },
  {
    id: 'L5',
    module: 'Foundations',
    moduleNum: 1,
    title: 'PID control, intuitively',
    duration: 10,
    hook: "PID is the single most important algorithm in your entire BMS career. Every modulating loop — every valve, every damper, every VFD — uses PID. The math looks scary; the intuition is dead simple.",
    content: [
      { type: 'h3', text: 'The three terms' },
      { type: 'p', text: 'PID = Proportional + Integral + Derivative. Three responses to error, added together.' },
      { type: 'bullets', items: [
        '**P (Proportional)** — react to *how big* the error is right now',
        '**I (Integral)** — react to *how long* the error has persisted',
        '**D (Derivative)** — react to *how fast* the error is changing',
      ]},
      { type: 'h3', text: 'The driving analogy' },
      { type: 'p', text: 'You\'re driving toward a stop line.' },
      { type: 'bullets', items: [
        '**P alone:** the further from the line, the harder you brake. But near the line, you brake softly — you might roll past it and never settle exactly on it. This leftover gap is called *offset*.',
        '**I added:** "I\'ve been 1 meter short for 5 seconds — that\'s unacceptable, push the brake harder until I\'m exactly on the line." I eliminates offset over time.',
        '**D added:** "I\'m approaching the line fast — ease off the brake before I overshoot." D dampens overshoot and oscillation.',
      ]},
      { type: 'h3', text: 'In BMS terms' },
      { type: 'p', text: 'Supply air setpoint is 13°C. Current temp is 18°C.' },
      { type: 'bullets', items: [
        '**P kicks in:** big error (5°C) → drive valve mostly open',
        '**As temp drops to 14°C:** P alone would leave valve nearly closed, leaving a 1°C offset',
        '**I builds up:** "we\'ve been 1°C off for 30 seconds" → push valve a bit more open until error = 0',
        '**D watches the rate:** if temp is crashing down fast (overshoot risk), pull the valve back a bit',
      ]},
      { type: 'h3', text: 'Tuning in plain language' },
      { type: 'bullets', items: [
        'Loop too slow / lazy → increase P',
        'Loop never quite hits setpoint → add or increase I',
        'Loop overshoots and oscillates → reduce P, or add a touch of D',
        'Loop is noisy / jittery → reduce D (D amplifies sensor noise)',
      ]},
      { type: 'callout', text: 'Most field engineers tune PID by feel after seeing 50+ loops behave. You\'ll get there. For now: 90% of HVAC loops work fine with P-only or PI. D is rarely needed and often causes more problems than it solves.' },
      { type: 'p', text: '**Try it now → open the PID Lab from the home screen.** Drag P, I, D sliders and watch a real loop respond. Nothing builds intuition faster.' },
    ],
    quiz: [
      {
        q: 'A control loop reaches steady state with a persistent 2°C error below setpoint. Which term most directly addresses this?',
        options: ['P (Proportional)', 'I (Integral)', 'D (Derivative)', 'Add a deadband'],
        correct: 1,
      },
      {
        q: 'A PID loop is oscillating — supply air swings between 11°C and 15°C every minute. First action?',
        options: ['Increase P', 'Decrease P', 'Increase D significantly', 'Switch to on/off control'],
        correct: 1,
      },
      {
        q: 'D term is generally avoided in HVAC because:',
        options: ['It is patented', 'It amplifies sensor noise and HVAC processes are slow', 'It requires more memory', 'It doesn\'t work below 0°C'],
        correct: 1,
      },
    ],
    takeaway: 'PID = react to size (P), duration (I), and rate (D) of error. Most HVAC loops only need P or PI. D usually causes more trouble than it solves.',
  },
  {
    id: 'L6',
    module: 'Foundations',
    moduleNum: 1,
    title: 'Signals — analog vs digital I/O',
    duration: 6,
    hook: "Every wire that leaves a BMS controller is one of four signal types. Knowing them cold lets you read any panel drawing and instantly understand what every terminal does.",
    content: [
      { type: 'h3', text: 'The four signal families' },
      { type: 'bullets', items: [
        '**AI (Analog Input)** — reads a continuous value. Temperature, pressure, humidity sensors.',
        '**AO (Analog Output)** — sends a continuous value. Modulating valves, dampers, VFD speed.',
        '**DI (Digital Input)** — reads on/off. Status feedback, alarms, dry contacts.',
        '**DO (Digital Output)** — sends on/off. Relay outputs to start/stop motors, energize coils.',
      ]},
      { type: 'h3', text: 'Common signal standards' },
      { type: 'bullets', items: [
        '**0–10V DC** — most common AI/AO standard. 0V = 0%, 10V = 100%. Cheap, distance-limited.',
        '**4–20mA** — industrial AI standard. More noise-immune, longer distances. The "4" baseline means a broken wire reads 0mA, instantly detectable.',
        '**RTD (PT100, PT1000)** — temperature sensing via resistance. Very accurate.',
        '**Thermistor (10kΩ NTC, 20kΩ NTC)** — cheaper temperature sensing, less accurate but fine for HVAC.',
        '**Dry contact** — just a switch closure for DI. No voltage from the field device.',
        '**Pulse** — counted DI for meters (1 pulse = X kWh or X liters).',
      ]},
      { type: 'h3', text: 'Quick read of a controller I/O sheet' },
      { type: 'p', text: 'A typical small AHU controller might have: 6 AI, 4 AO, 6 DI, 4 DO. That means it can read 6 sensors, drive 4 modulating outputs, read 6 status signals, and switch 4 relays. Sizing means counting these for your application + adding spare capacity (typically 20%).' },
      { type: 'callout', text: 'In Ghana, 4–20mA pays off — long sensor runs, electrical noise, and humidity make 0–10V signals drift more than spec sheets suggest. Worth the small cost premium on critical points.' },
    ],
    quiz: [
      {
        q: 'A modulating chilled water valve being driven from a controller is connected to which I/O type?',
        options: ['AI', 'AO', 'DI', 'DO'],
        correct: 1,
      },
      {
        q: 'A pump "run status" signal (auxiliary contact from the starter) connects to which I/O type?',
        options: ['AI', 'AO', 'DI', 'DO'],
        correct: 2,
      },
      {
        q: 'Main advantage of 4–20mA over 0–10V:',
        options: ['Faster response', 'Wire break detection (reads 0mA) and noise immunity', 'Cheaper sensors', 'Works underwater'],
        correct: 1,
      },
    ],
    takeaway: 'Four signal types: AI (read continuous), AO (drive continuous), DI (read on/off), DO (switch on/off). Standards: 0–10V, 4–20mA, RTD/thermistor, dry contacts, pulse.',
  },
  {
    id: 'L7',
    module: 'Foundations',
    moduleNum: 1,
    title: 'Why BACnet won the protocol wars',
    duration: 7,
    hook: "Before BACnet existed, every vendor locked you in. Buy Trane chillers? You needed Trane controllers, Trane software, Trane technicians, Trane forever. BACnet broke that cartel and is now in 95% of commercial buildings worldwide.",
    content: [
      { type: 'h3', text: 'The pre-BACnet dark ages' },
      { type: 'p', text: 'Through the 1980s, every major HVAC manufacturer had a proprietary protocol. Trane spoke Trane. Honeywell spoke Honeywell. Mixing brands was nearly impossible without expensive gateways. Building owners were captives.' },
      { type: 'h3', text: 'BACnet is born' },
      { type: 'p', text: 'In 1995, ASHRAE released BACnet (Building Automation and Control networks) as an open standard. It defined a universal language: how devices describe themselves, what objects they expose, how to read/write data, how to discover each other on a network.' },
      { type: 'h3', text: 'Why it won' },
      { type: 'bullets', items: [
        '**Open standard** — no licensing fees, anyone can implement it',
        '**Object-oriented** — devices expose standard "objects" (Analog Input, Schedule, etc.) any other device can understand',
        '**Network-flexible** — runs on Ethernet (BACnet/IP) or RS-485 (BACnet MS/TP) or other media',
        '**Backed by ASHRAE** — the trusted industry body forced consensus',
        '**Building-specific** — unlike Modbus (industrial), BACnet was designed for HVAC scenarios',
      ]},
      { type: 'h3', text: 'BACnet today' },
      { type: 'bullets', items: [
        'Required by spec on virtually all commercial projects globally',
        'Two physical layers dominate: BACnet/IP (Ethernet) for backbones, BACnet MS/TP (RS-485) for field buses',
        'BACnet/SC (Secure Connect) is the new secure variant, slowly rolling out',
        'Native in every major BMS vendor: Siemens, JCI, Honeywell, Schneider, Trane, Carrier, Distech, ALC, Delta',
      ]},
      { type: 'callout', text: 'When you spec BMS scope: always require "BACnet/IP native" for the supervisor and "BACnet MS/TP or IP native" for field controllers. Reject any bid that needs gateways or proprietary cards as primary integration — that\'s the lock-in trying to creep back in.' },
    ],
    quiz: [
      {
        q: 'BACnet was released by ASHRAE in:',
        options: ['1985', '1995', '2005', '2015'],
        correct: 1,
      },
      {
        q: 'BACnet MS/TP runs over which physical layer?',
        options: ['Ethernet', 'RS-485 twisted pair', 'Wi-Fi', 'Fiber optic only'],
        correct: 1,
      },
      {
        q: 'Why is "BACnet/IP native" preferred over "BACnet via gateway"?',
        options: ['It\'s faster', 'It avoids vendor lock-in and an extra point of failure', 'It\'s cheaper hardware', 'It\'s required by Ghana law'],
        correct: 1,
      },
    ],
    takeaway: 'BACnet is the universal open language of building automation. Spec it native. Anything else risks vendor lock-in.',
  },
  {
    id: 'L8',
    module: 'Foundations',
    moduleNum: 1,
    title: 'Anatomy of a Sequence of Operation',
    duration: 9,
    hook: "The Sequence of Operation is the most important document in any BMS project. It's the contract between the designer (you) and the integrator (them) that defines exactly how the building should behave. A bad SOO causes 90% of commissioning fights.",
    content: [
      { type: 'h3', text: 'What an SOO is' },
      { type: 'p', text: 'A Sequence of Operation is a plain-language description of how each piece of equipment should be controlled under every condition: occupied, unoccupied, startup, shutdown, fire, fault, maintenance.' },
      { type: 'h3', text: 'The standard structure (ASHRAE Guideline 36)' },
      { type: 'bullets', items: [
        '**Equipment description** — what it is, what it serves',
        '**Modes of operation** — Occupied, Unoccupied, Setback, Warm-up, Cool-down, Test',
        '**Setpoints** — supply air temp, static pressure, OA flow, etc.',
        '**Control sequences** — for each mode, exactly what each component does',
        '**Safeties and interlocks** — freezestat, smoke, high static, low temp',
        '**Alarms** — what triggers an alarm, what priority',
        '**Failure modes** — what happens when sensor X fails or valve Y is stuck',
      ]},
      { type: 'h3', text: 'A mini SOO for an AHU' },
      { type: 'p', text: 'Just to feel the texture:' },
      { type: 'callout', text: 'Supply fan: starts when the schedule is Occupied OR when zone temperature exceeds setback. VFD modulates to maintain duct static pressure setpoint of 1.5 in. w.g. ± 0.1 in. w.g. Cooling valve: PID modulates 0–100% to maintain supply air temperature setpoint of 13°C ± 0.5°C. Economizer: enables when OAT < 18°C AND OAT < RAT − 2°C. On fire alarm: supply fan stops within 5 seconds, outside air damper closes, return air damper closes, exhaust damper opens.' },
      { type: 'h3', text: 'Why it matters commercially' },
      { type: 'bullets', items: [
        'A great SOO = predictable commissioning, no disputes, on-time handover',
        'A bad SOO = endless RFIs, blame games, late projects, unhappy clients',
        'Yakuver can charge a premium for SOO writing alone — it\'s a high-leverage service',
        'ASHRAE Guideline 36 is free online and gives you templates for everything',
      ]},
    ],
    quiz: [
      {
        q: 'An SOO that says "AHU controls supply air temperature appropriately" is:',
        options: ['Adequate — engineers know what that means', 'Inadequate — must specify setpoint, control element, and tolerances', 'A pricing strategy', 'Required only for chillers'],
        correct: 1,
      },
      {
        q: 'Which document is considered the gold standard reference for HVAC sequences?',
        options: ['ASHRAE 90.1', 'ASHRAE Guideline 36', 'IEEE 802.11', 'ISO 9001'],
        correct: 1,
      },
      {
        q: 'Best place to specify "what happens during a fire alarm" in BMS scope:',
        options: ['Verbal handover meeting', 'In the SOO under safeties/failure modes', 'On site during commissioning', 'In the cleaning manual'],
        correct: 1,
      },
    ],
    takeaway: 'The SOO is the contract. Write it precisely — modes, setpoints, sequences, safeties, alarms, failure modes — and your projects will commission cleanly.',
  },
  {
    id: 'L9',
    module: 'Foundations',
    moduleNum: 1,
    title: 'Reading a point list',
    duration: 8,
    hook: "Every BMS project has a point list. It's a spreadsheet with hundreds of rows that tells you exactly what's being controlled, how, and with what hardware. If you can read one fluently, you can scope and price any BMS job.",
    content: [
      { type: 'h3', text: 'What a point list is' },
      { type: 'p', text: 'A point list (also called I/O schedule) is a row-per-signal inventory of every physical and software point in the BMS. Each row tells you: what equipment, what signal, what type, what device, what tag, what notes.' },
      { type: 'h3', text: 'Standard columns' },
      { type: 'bullets', items: [
        '**Equipment** — AHU-01, CH-02, VAV-3F-12',
        '**Description** — Supply Air Temperature, Cooling Valve Position',
        '**Tag / Point name** — AHU01.SAT, CH02.CHWVLV',
        '**Type** — AI, AO, DI, DO, AV, BV (BACnet virtual points)',
        '**Signal** — 0–10V, 4–20mA, PT1000, dry contact',
        '**Range / units** — 0–50°C, 0–100%',
        '**Field device** — sensor make/model, valve actuator',
        '**Controller** — which controller, which terminal',
        '**Notes** — alarm priority, history collection, network exposure',
      ]},
      { type: 'h3', text: 'A typical AHU point list — roughly 30 points' },
      { type: 'bullets', items: [
        'Supply air temp (AI), return air temp (AI), mixed air temp (AI), outside air temp (AI shared)',
        'Supply air humidity (AI), return air humidity (AI)',
        'Supply duct static pressure (AI), filter DP (AI or DI)',
        'Supply fan VFD speed (AO), VFD status (DI), VFD fault (DI), VFD speed feedback (AI)',
        'Return fan equivalent set',
        'Cooling valve (AO), heating valve (AO)',
        'OA damper (AO), RA damper (AO), EA damper (AO)',
        'Freezestat (DI), smoke detector (DI), high static safety (DI)',
        'Zone CO2 (AI), occupancy override (DI)',
        '...and software points: setpoints (AV), occupied state (BV), schedule, alarms',
      ]},
      { type: 'h3', text: 'Why this matters' },
      { type: 'bullets', items: [
        '**Pricing** — point count × $/point is the fastest BMS estimate method (rough order: $300–$800 per point in Ghana including hardware, software, install, commissioning)',
        '**Controller sizing** — sum your AI/AO/DI/DO counts and add 20% spare to pick controllers',
        '**Cable scheduling** — every point needs a cable; the list drives containment design',
        '**Commissioning checklist** — every row gets a "tested" tick mark during P2P',
      ]},
      { type: 'callout', text: 'Productize this: a clean, vendor-neutral point list template per equipment type (AHU, chiller, FCU, VRF, pump set, lighting circuit) is one of the most valuable IP assets a small MEP firm can own. Worth building for Yakuver, worth selling later.' },
    ],
    quiz: [
      {
        q: 'A supply duct static pressure transmitter reading 0–2 in. w.g. into a controller is:',
        options: ['AI', 'AO', 'DI', 'DO'],
        correct: 0,
      },
      {
        q: 'Rough Ghana-market BMS pricing per point (all-in: hardware, software, install, commissioning) is approximately:',
        options: ['$10–$50', '$300–$800', '$5,000–$10,000', '$50,000+'],
        correct: 1,
      },
      {
        q: 'When sizing a controller from a point list, you should:',
        options: ['Match I/O exactly to point count', 'Add ~20% spare I/O capacity', 'Pick the cheapest controller', 'Use one controller per point'],
        correct: 1,
      },
    ],
    takeaway: 'The point list is the BMS bible — drives pricing, controller sizing, cable scheduling, and Cx. Build great templates and you have an asset for life.',
  },
  {
    id: 'L10',
    module: 'Foundations',
    moduleNum: 1,
    title: 'Module 1 boss check',
    duration: 12,
    hook: "End of Module 1. Let's see if it stuck.",
    content: [
      { type: 'h3', text: 'Module 1 recap' },
      { type: 'p', text: 'You\'ve covered: what BMS is, the 3-tier architecture, the business case, open vs closed loop control, PID intuition, signals and I/O, why BACnet won, what an SOO is, and how to read a point list.' },
      { type: 'p', text: 'This boss check has 8 questions across all of Module 1. Pass at 75% (6/8) to unlock Module 2.' },
      { type: 'callout', text: 'If you fail, the app will spaced-repeat the wrong topics over the next 3 days before you re-attempt. That\'s by design — your brain encodes better after the failure.' },
    ],
    quiz: [
      {
        q: 'A field controller for an AHU loses its connection to the supervisor. What happens?',
        options: ['AHU stops', 'AHU keeps running its local sequence', 'Building enters fire mode', 'Alarms are deleted'],
        correct: 1,
      },
      {
        q: 'PID loop oscillates ±2°C around setpoint, period of ~3 minutes. Best first action:',
        options: ['Add deadband', 'Increase P (proportional gain)', 'Decrease P (proportional gain)', 'Increase D (derivative)'],
        correct: 2,
      },
      {
        q: 'A modulating damper actuator driven 0–10V from a controller is connected to:',
        options: ['AI', 'AO', 'DI', 'DO'],
        correct: 1,
      },
      {
        q: 'Which is NOT one of the four core BMS business cases?',
        options: ['Energy savings', 'Comfort and IAQ', 'Aesthetic dashboards for the lobby', 'Compliance and reporting'],
        correct: 2,
      },
      {
        q: 'You receive a bid that requires a proprietary gateway between the BMS supervisor and the chiller. Best response:',
        options: ['Accept — gateways are normal', 'Push back and require BACnet/IP native on the chiller', 'Cancel the project', 'Use Modbus only'],
        correct: 1,
      },
      {
        q: 'The Sequence of Operation should specify all of the following EXCEPT:',
        options: ['Setpoints and tolerances', 'Modes of operation', 'Failure modes and safeties', 'The exact brand of valves to use'],
        correct: 3,
      },
      {
        q: 'A point list for a typical commercial AHU contains approximately:',
        options: ['3–5 points', '30–40 points', '300–400 points', '3,000+ points'],
        correct: 1,
      },
      {
        q: 'BACnet/IP runs over UDP port:',
        options: ['80', '443', '47808', '8080'],
        correct: 2,
      },
    ],
    takeaway: 'Module 1 complete. Foundation laid. Module 2 (HVAC Controls Applied) is where your 8 years of HVAC experience starts paying massive dividends.',
    isBoss: true,
  },

  // ==========================================================================
  // MODULE 2 — HVAC Controls Applied
  // ==========================================================================
  {
    id: 'L11',
    module: 'HVAC Controls',
    moduleNum: 2,
    title: 'The AHU as a control problem',
    duration: 8,
    hook: "An air handling unit is just a box that pulls in air, conditions it, and pushes it out. But to a BMS engineer it is a dozen control points wearing a trench coat. Learn to see the AHU the way the controller sees it and every sequence afterwards becomes obvious.",
    content: [
      { type: 'h3', text: 'The air path — always in this order' },
      { type: 'p', text: 'Air flows through an AHU in a fixed order. Memorize the order — every sequence you will ever read references it.' },
      { type: 'diagram', kind: 'ahu' },
      { type: 'bullets', items: [
        '**OA damper** — lets in fresh outside air; a modulating AO',
        '**RA damper** — recirculates room air; a modulating AO',
        '**Mixing box** — where OA and RA blend; the mixed air temp (MAT) sensor sits here',
        '**Filters** — a differential pressure switch or sensor flags when they are dirty',
        '**Cooling coil** — chilled water or DX; a modulating valve (AO) controls it',
        '**Heating coil** — hot water or electric; modulating valve or stages',
        '**Supply fan** — usually VFD-driven; pushes conditioned air to the zones',
        '**SAT sensor** — supply air temperature, downstream of the coils — the AHU\'s main feedback point',
      ]},
      { type: 'h3', text: 'Strip the sheet metal — what is left is points' },
      { type: 'bullets', items: [
        '**Inputs (AI):** OAT, RAT, MAT, SAT, supply humidity, duct static pressure, filter DP',
        '**Inputs (DI):** fan run status, VFD fault, freezestat, duct smoke detector',
        '**Outputs (AO):** cooling valve, heating valve, OA/RA/EA dampers, fan VFD speed',
        '**Outputs (DO):** fan start/stop command',
      ]},
      { type: 'callout', text: 'When you walk up to any AHU on site, find three things in order: where does air come in, where are the coils, where is the SAT sensor. If the SAT sensor sits in the wrong place — before a coil, or in a dead air pocket — every loop downstream will misbehave and no amount of tuning will ever fix it.' },
    ],
    quiz: [
      {
        q: 'The mixed air temperature (MAT) sensor is located:',
        options: ['In the supply duct after the fan', 'In the mixing box where OA and RA blend', 'Inside the cooling coil', 'At the zone thermostat'],
        correct: 1,
      },
      {
        q: 'The AHU\'s primary feedback sensor for coil control is:',
        options: ['Outside air temperature', 'Return air temperature', 'Supply air temperature', 'Filter differential pressure'],
        correct: 2,
      },
      {
        q: 'A modulating chilled water valve on the cooling coil is which I/O type?',
        options: ['AI', 'AO', 'DI', 'DO'],
        correct: 1,
      },
    ],
    takeaway: 'An AHU is an ordered air path — mix, filter, cool, heat, fan — wrapped around a handful of control points. Learn to see the points, not the sheet metal.',
  },
  {
    id: 'L12',
    module: 'HVAC Controls',
    moduleNum: 2,
    title: 'Supply air temperature control',
    duration: 9,
    hook: "Supply air temperature control is the single most-run loop in any building. Get it right and the whole AHU behaves. Get it wrong and you get the classic complaint: 'half the floor is freezing, the other half is roasting.'",
    content: [
      { type: 'h3', text: 'The job' },
      { type: 'p', text: 'The AHU\'s coils exist to deliver air at a target temperature — the supply air temperature (SAT) setpoint. A PID loop reads the SAT sensor and modulates the coil valves to hold that setpoint.' },
      { type: 'h3', text: 'One loop, two coils — sequenced control' },
      { type: 'p', text: 'You do not run cooling and heating as two independent loops. That wastes energy fighting itself. You run ONE loop whose output is split across both coils.' },
      { type: 'bullets', items: [
        'Loop output 0–50% → heating valve modulates 100%→0%, cooling valve stays shut',
        'Loop output ≈50% → both valves shut — a deadband, the cheapest comfort there is',
        'Loop output 50–100% → cooling valve modulates 0%→100%, heating valve stays shut',
      ]},
      { type: 'p', text: 'This is called sequenced or split-range control. The deadband in the middle stops the AHU from heating and cooling at the same time.' },
      { type: 'h3', text: 'Why the deadband matters' },
      { type: 'callout', text: 'A 2–3°C deadband between heating and cooling is the highest-ROI line in any sequence. Without it, on a mild day the heating coil and the cooling coil chase each other forever — you pay for both and the building still drifts. With it, the AHU simply coasts.' },
      { type: 'h3', text: 'Common failures' },
      { type: 'bullets', items: [
        'SAT never quite reaches setpoint → integral term too weak, or the valve is undersized',
        'SAT oscillates ±2°C → proportional gain too high; retune it (the PID Lab shows exactly this)',
        'SAT is correct but zones still complain → the problem is downstream (VAV, balancing), not the AHU',
      ]},
    ],
    quiz: [
      {
        q: 'Why combine heating and cooling into a single sequenced loop?',
        options: ['It saves wiring', 'It prevents the two coils fighting each other and wasting energy', 'BACnet requires it', 'Heating coils cannot have their own loop'],
        correct: 1,
      },
      {
        q: 'At ~50% loop output in a properly sequenced AHU:',
        options: ['Both coils are full open', 'Both coils are shut (deadband)', 'Cooling full, heating off', 'Heating full, cooling off'],
        correct: 1,
      },
      {
        q: 'SAT holds steady 1.5°C above setpoint and never closes the gap. Most likely fix:',
        options: ['Increase derivative', 'Increase or add integral action', 'Widen the deadband', 'Replace the fan'],
        correct: 1,
      },
    ],
    takeaway: 'Supply air temperature is held by one sequenced loop split across heating and cooling coils, with a deadband between them so the AHU never heats and cools at once.',
  },
  {
    id: 'L13',
    module: 'HVAC Controls',
    moduleNum: 2,
    title: 'Economizer & free cooling',
    duration: 9,
    hook: "On a cool harmattan morning in Accra, the cheapest cooling you will ever buy is the air already outside. An economizer is the logic that grabs it. Done right it slashes chiller hours; done wrong it drags humid air into the building and the cooling coil pays for your mistake.",
    content: [
      { type: 'h3', text: 'An economizer is a mode, not a device' },
      { type: 'p', text: 'When outside air is cooler — or otherwise better — than return air, the AHU opens the OA damper wide and uses outside air to cool the space instead of, or before, the chilled water coil.' },
      { type: 'h3', text: 'The enable decision — three flavours' },
      { type: 'bullets', items: [
        '**Dry-bulb economizer** — enable when OAT < a changeover setpoint (e.g. OAT < 18°C). Simple, cheap, common.',
        '**Differential dry-bulb** — enable when OAT < RAT − 2°C. Smarter; uses outside air only when it genuinely helps.',
        '**Enthalpy economizer** — compares *total heat* (temperature + humidity). Essential in humid climates: cool but very wet outside air can carry more heat than warm dry return air.',
      ]},
      { type: 'callout', text: 'In Ghana\'s coastal humidity, a plain dry-bulb economizer is a trap. 26°C saturated outside air holds far more heat than 24°C conditioned return air. Spec enthalpy (or at least differential enthalpy) changeover, or the economizer will load your cooling coil instead of unloading it.' },
      { type: 'h3', text: 'How it modulates — integrated economizer' },
      { type: 'p', text: 'When the economizer is enabled, the OA/RA dampers become the first stage of cooling. The SAT loop drives the dampers first; only when the dampers are 100% open and SAT is still too high does the chilled water valve begin to open.' },
      { type: 'h3', text: 'Minimum position never goes away' },
      { type: 'p', text: 'Even with the economizer off, the OA damper never fully closes — it holds a minimum position for fresh-air ventilation (driven by occupancy or CO2). Economizer logic sits on top of that minimum.' },
    ],
    quiz: [
      {
        q: 'An economizer saves energy by:',
        options: ['Running the supply fan slower', 'Using cool outside air instead of the chiller', 'Closing the OA damper', 'Boosting the heating coil'],
        correct: 1,
      },
      {
        q: 'In a humid coastal climate, the safest economizer changeover type is:',
        options: ['Fixed dry-bulb temperature', 'Enthalpy (total heat)', 'A fixed time schedule', 'Always-on'],
        correct: 1,
      },
      {
        q: 'In an integrated economizer sequence, when OA dampers are 100% open and SAT is still above setpoint:',
        options: ['The AHU shuts down', 'The chilled water valve begins to open', 'The fan stops', 'Heating enables'],
        correct: 1,
      },
    ],
    takeaway: 'An economizer is a control mode that uses cool outside air as free cooling. In humid climates, enable it on enthalpy, not dry-bulb, or it backfires.',
  },
  {
    id: 'L14',
    module: 'HVAC Controls',
    moduleNum: 2,
    title: 'Duct static pressure & reset',
    duration: 8,
    hook: "A VAV system has dozens of boxes opening and closing all day. The supply fan has to feed every one of them — without starving the far zones or blasting the near ones. The single control variable that holds it all together is duct static pressure.",
    content: [
      { type: 'h3', text: 'Why static pressure is the fan\'s setpoint' },
      { type: 'p', text: 'In a VAV system you cannot control the fan on temperature — temperature is each zone\'s job. The fan\'s job is to keep the supply duct pressurized enough that every VAV box can pull the air it needs. So the fan VFD modulates to hold a duct static pressure setpoint.' },
      { type: 'bullets', items: [
        'The pressure sensor sits roughly two-thirds of the way down the longest duct run',
        'VAV boxes open → duct pressure drops → fan speeds up to recover it',
        'VAV boxes close → duct pressure rises → fan slows down',
      ]},
      { type: 'h3', text: 'The cost of a fixed setpoint' },
      { type: 'p', text: 'Fan power rises with the cube of speed. Holding a high fixed static pressure all day — sized for the worst-case hour — wastes enormous energy during the 95% of hours that are not the worst case.' },
      { type: 'h3', text: 'Static pressure reset (ASHRAE Guideline 36)' },
      { type: 'p', text: 'Instead of a fixed setpoint, reset it down until the system is just satisfied. The trim-and-respond method:' },
      { type: 'bullets', items: [
        'Poll every VAV box: how many are nearly wide open — starved for air?',
        'Too many boxes pinned open → they generate requests → raise the static setpoint a notch',
        'No boxes requesting → trim the setpoint down a notch',
        'The duct pressure floats to the lowest value that still satisfies the hungriest zone',
      ]},
      { type: 'callout', text: 'Static pressure reset is one of the biggest single energy wins in a VAV building — fan energy savings of 20–40% are routine — and it costs nothing but logic. If a VAV AHU you inherit runs a fixed static setpoint, that is free money sitting on the table.' },
    ],
    quiz: [
      {
        q: 'The supply fan VFD in a VAV system modulates to maintain:',
        options: ['Supply air temperature', 'Duct static pressure', 'Outside air temperature', 'Zone CO2'],
        correct: 1,
      },
      {
        q: 'Fan power varies with fan speed roughly:',
        options: ['Linearly', 'With the square', 'With the cube', 'Not at all'],
        correct: 2,
      },
      {
        q: 'Trim-and-respond static pressure reset lowers the setpoint until:',
        options: ['The fan stops', 'The hungriest VAV box is just satisfied and no further', 'All boxes are fully closed', 'The chiller trips'],
        correct: 1,
      },
    ],
    takeaway: 'The VAV supply fan holds duct static pressure, not temperature. Resetting that pressure down with trim-and-respond logic is a 20–40% fan-energy win for free.',
  },
  {
    id: 'L15',
    module: 'HVAC Controls',
    moduleNum: 2,
    title: 'AHU safeties & interlocks',
    duration: 7,
    hook: "Control sequences make a building comfortable. Safeties stop it from destroying itself. When a freezestat trips or the fire alarm sounds, the BMS must do the right thing in seconds — and do it even if the supervisor is offline.",
    content: [
      { type: 'h3', text: 'Hardwired vs software safeties' },
      { type: 'p', text: 'A real safety is hardwired — it acts directly on the equipment, independent of controller logic. The BMS also reads it as a point so it can alarm and log, but the protection itself does not depend on software running correctly.' },
      { type: 'h3', text: 'The core AHU safeties' },
      { type: 'bullets', items: [
        '**Freezestat (low-limit thermostat)** — senses air across the coil; if it drops near freezing it stops the fan and closes the OA damper before the coil bursts. Manual reset.',
        '**Duct smoke detector** — on smoke it shuts the fan down and ties into the fire alarm system.',
        '**High static pressure cutout** — if a fire damper slams shut or the duct blocks, pressure spikes; the cutout trips the fan before the ductwork is damaged.',
        '**Fire alarm interlock** — on a building fire signal the AHU goes to fire mode: typically fan off and dampers driven to a defined safe position, or a dedicated smoke-control sequence.',
      ]},
      { type: 'h3', text: 'Fail-safe positions' },
      { type: 'p', text: 'Every actuator must have a defined position for loss of power or signal. Spring-return actuators move there automatically.' },
      { type: 'bullets', items: [
        'Chilled water valve → fails closed or open depending on design intent',
        'Heating valve in a cold climate → often fails open, to protect the coil from freezing',
        'OA damper → fails closed, so a dead AHU does not pull in unconditioned air',
      ]},
      { type: 'callout', text: 'In commissioning, never test a safety by reading the point on the graphic. Physically trip it — chill the freezestat element, push the smoke test, drop the fire signal — and watch the fan actually stop. A safety wired to the wrong terminal looks perfect on screen and does absolutely nothing in a real event.' },
    ],
    quiz: [
      {
        q: 'A freezestat protects against:',
        options: ['High duct pressure', 'A coil freezing and bursting', 'Dirty filters', 'Fan overspeed'],
        correct: 1,
      },
      {
        q: 'A genuine safety interlock should be:',
        options: ['Pure software logic in the supervisor', 'Hardwired so it acts independently of controller software', 'Optional on commercial jobs', 'Reset automatically every night'],
        correct: 1,
      },
      {
        q: 'On a building fire alarm signal, a typical AHU response is:',
        options: ['Speed the supply fan up', 'Stop the fan and drive dampers to a defined safe position', 'Open the cooling valve fully', 'Ignore it — fire is the fire panel\'s job'],
        correct: 1,
      },
    ],
    takeaway: 'AHU safeties — freezestat, duct smoke, high-static cutout, fire interlock — must be hardwired to act without software, and must be physically tripped during commissioning, not just read on a screen.',
  },
  {
    id: 'L16',
    module: 'HVAC Controls',
    moduleNum: 2,
    title: 'Chilled water: primary-secondary vs variable primary',
    duration: 9,
    hook: "The chillers make the cold water. The pumps move it. How you arrange those pumps decides how much energy the plant wastes and how hard it is to control. Two architectures dominate — knowing the difference is core BMS literacy.",
    content: [
      { type: 'h3', text: 'The problem these architectures solve' },
      { type: 'p', text: 'A chiller needs reasonably constant flow through its evaporator to run safely. The building, however, wants variable flow — lots of chilled water on a hot afternoon, very little at night. Reconciling "constant at the chiller, variable at the load" is the whole game.' },
      { type: 'h3', text: 'Primary-secondary (decoupled)' },
      { type: 'bullets', items: [
        'A **primary loop** runs constant flow through the chillers, each with a dedicated pump',
        'A **secondary loop** runs variable flow out to the building, with VFD-driven pumps',
        'The two loops meet at a **decoupler** — a short common pipe that hydraulically separates them',
        'Simple, forgiving, very common — but two sets of pumps means more pump energy',
      ]},
      { type: 'h3', text: 'Variable primary flow (VPF)' },
      { type: 'bullets', items: [
        'One set of variable-speed pumps serves chillers and building together',
        'Flow through the chiller is allowed to vary, down to the manufacturer\'s minimum',
        'A **minimum-flow bypass valve** opens when building demand falls below the chiller minimum, protecting the evaporator',
        'Fewer pumps, less pump energy — but tighter, less forgiving control',
      ]},
      { type: 'callout', text: 'Watch the decoupler flow direction in a primary-secondary plant. If water flows from return toward supply through the decoupler, the secondary loop is demanding more than the running chillers can deliver — that is your hard signal to stage on another chiller.' },
      { type: 'h3', text: 'Choosing between them' },
      { type: 'p', text: 'Primary-secondary for simplicity, retrofits, and operators who want forgiveness. Variable primary for new plants chasing efficiency, where the controls and the chiller minimum-flow limits are well understood.' },
    ],
    quiz: [
      {
        q: 'A chiller evaporator needs:',
        options: ['Zero flow when idle', 'Reasonably constant minimum flow to run safely', 'Maximum flow at all times', 'Flow only at night'],
        correct: 1,
      },
      {
        q: 'In a variable primary flow plant, the minimum-flow bypass valve exists to:',
        options: ['Increase building flow', 'Protect the chiller when building demand drops below its minimum flow', 'Replace the decoupler', 'Speed up the pumps'],
        correct: 1,
      },
      {
        q: 'In primary-secondary, decoupler flow running from return toward supply indicates:',
        options: ['The plant is oversized', 'Secondary demand exceeds current chiller capacity — stage up', 'A pump has failed', 'Normal night operation'],
        correct: 1,
      },
    ],
    takeaway: 'Chilled water plants reconcile constant chiller flow with variable building demand. Primary-secondary is simple and forgiving; variable primary is leaner but needs tighter controls and a minimum-flow bypass.',
  },
  {
    id: 'L17',
    module: 'HVAC Controls',
    moduleNum: 2,
    title: 'Chiller sequencing, staging & lead/lag',
    duration: 9,
    hook: "A plant with three chillers should almost never run three when two will do — and should never let one chiller rack up all the hours while its twin sits brand new. Staging and rotation logic is where a chilled water plant is won or lost.",
    content: [
      { type: 'h3', text: 'Staging — how many chillers to run' },
      { type: 'p', text: 'Staging decides when to bring a chiller on and when to shed one. Get it wrong in either direction and you pay.' },
      { type: 'bullets', items: [
        'Stage **up** too late → chillers run flat out, cannot hold setpoint, the building drifts warm',
        'Stage **up** too early → chillers run lightly loaded and inefficient',
        'Stage **down** too late → wasted energy; too early → short-cycling and tripped compressors',
      ]},
      { type: 'h3', text: 'What triggers a stage change' },
      { type: 'bullets', items: [
        '**Chilled water supply temperature** — cannot hold setpoint for a sustained period → stage up',
        '**Plant load / amps** — running chillers above a load threshold (e.g. >90% for 15 min) → stage up',
        '**Flow** (variable primary) — building flow approaching the capacity of running chillers → stage up',
        'Always use a **time delay** and a **deadband** so a brief spike does not trigger a stage change',
      ]},
      { type: 'callout', text: 'The number-one chiller-plant fault in the field is short-cycling — a chiller starting and stopping repeatedly. It hammers compressors and destroys efficiency. The fix is almost always a longer minimum-runtime / minimum-off timer and a wider staging deadband, not a hardware change.' },
      { type: 'h3', text: 'Lead/lag rotation' },
      { type: 'p', text: 'The lead chiller starts first and stops last; the lag follows. If you never rotate which chiller is lead, one unit ages out while the other stays nearly new.' },
      { type: 'bullets', items: [
        'Rotate lead/lag on **runtime hours** — keep total hours roughly equal across units',
        'Or rotate on a **schedule** — for example weekly',
        'Rotation also means a single chiller failure is not catastrophic — the others are exercised and proven',
      ]},
    ],
    quiz: [
      {
        q: 'The most common destructive chiller-plant fault is:',
        options: ['Overcooling', 'Short-cycling — repeated rapid start/stop', 'Running too quietly', 'Excess flow'],
        correct: 1,
      },
      {
        q: 'A staging sequence should always include a time delay and deadband because:',
        options: ['BACnet requires it', 'They stop a brief load spike from triggering an unnecessary stage change', 'They save wiring', 'Chillers cannot start otherwise'],
        correct: 1,
      },
      {
        q: 'Lead/lag rotation based on runtime hours mainly achieves:',
        options: ['Lower chilled water temperature', 'Even wear across chillers and proven standby capacity', 'Faster staging', 'Higher flow'],
        correct: 1,
      },
    ],
    takeaway: 'Stage chillers on supply temp, load, or flow — always with a delay and deadband — and rotate lead/lag on runtime hours so the plant wears evenly and short-cycling never sets in.',
  },
  {
    id: 'L18',
    module: 'HVAC Controls',
    moduleNum: 2,
    title: 'VAV terminal units — pressure-independent control',
    duration: 9,
    hook: "The AHU delivers a duct full of cool air. The VAV box is what each zone uses to take exactly the amount it needs — no more, no less. The clever part is a two-loop trick that makes a VAV box ignore duct pressure swings entirely.",
    content: [
      { type: 'h3', text: 'What a VAV box does' },
      { type: 'p', text: 'A Variable Air Volume box is a damper plus an airflow sensor in a small duct serving one zone. It throttles airflow to hold the zone at setpoint. Many also have a reheat coil for when the zone needs warming.' },
      { type: 'h3', text: 'Why a single loop fails' },
      { type: 'p', text: 'If the zone thermostat drove the damper directly, then every time another VAV box opened elsewhere the duct pressure would shift and this box\'s airflow would wander — even though its zone never changed. The zone would never settle.' },
      { type: 'h3', text: 'The pressure-independent solution — cascaded loops' },
      { type: 'bullets', items: [
        '**Outer loop (zone temp):** the thermostat compares room temp to setpoint and outputs an *airflow setpoint* in CFM or L/s — not a damper position',
        '**Inner loop (airflow):** a fast loop reads the box\'s own airflow sensor and modulates the damper to hit that airflow setpoint',
        'Because the inner loop controls *measured airflow*, a duct pressure swing is corrected instantly — the zone loop never even sees it',
      ]},
      { type: 'callout', text: 'This is cascade control — the same pattern as the chiller and the AHU. The outer loop sets a target for the inner loop. "Pressure-independent" simply means there is an airflow sensor and an inner airflow loop. A "pressure-dependent" box has no airflow sensor and the thermostat drives the damper directly — cheap, and exactly as unstable as it sounds.' },
      { type: 'h3', text: 'Cooling and reheat sequence' },
      { type: 'bullets', items: [
        'Zone too warm → airflow setpoint rises between the minimum and the maximum cooling airflow',
        'Zone satisfied → airflow drops to the **minimum** — a ventilation floor, enough fresh air for occupants',
        'Zone too cold → airflow stays at minimum and the **reheat** valve modulates to warm that minimum airflow',
        'Never reheat at high airflow — heating a large airflow to satisfy one cold zone is the classic VAV energy sin',
      ]},
    ],
    quiz: [
      {
        q: 'In a pressure-independent VAV box, the zone thermostat\'s output is:',
        options: ['A damper position', 'An airflow setpoint that an inner loop then holds', 'A fan speed', 'A water valve position'],
        correct: 1,
      },
      {
        q: '"Pressure-independent" is possible because the box has:',
        options: ['A bigger damper', 'Its own airflow sensor and an inner airflow loop', 'A reheat coil', 'A faster thermostat'],
        correct: 1,
      },
      {
        q: 'When a VAV zone is satisfied and slightly too cold, the box should:',
        options: ['Increase airflow and reheat', 'Hold airflow at minimum and modulate reheat', 'Close the damper fully', 'Speed up the AHU fan'],
        correct: 1,
      },
    ],
    takeaway: 'A VAV box uses cascaded loops — zone temp sets an airflow target, an inner loop holds that airflow against duct pressure swings. Reheat happens at minimum airflow, never at high flow.',
  },
  {
    id: 'L19',
    module: 'HVAC Controls',
    moduleNum: 2,
    title: 'Module 2 boss check',
    duration: 12,
    hook: "End of Module 2 — HVAC Controls Applied. Eight lessons of AHU, chilled water, and VAV logic. Let's see what stuck.",
    content: [
      { type: 'h3', text: 'Module 2 recap' },
      { type: 'p', text: 'You covered: the AHU as a set of control points, supply air temperature control, economizer free cooling, duct static pressure and reset, AHU safeties, chilled water pumping architectures, chiller staging and lead/lag, and pressure-independent VAV control.' },
      { type: 'p', text: 'This boss check has 8 questions across all of Module 2. Pass at 75% (6/8).' },
      { type: 'callout', text: 'This is where your HVAC field experience compounds with the controls layer. If a question feels obvious now, that is the point — the controls vocabulary is becoming yours.' },
    ],
    quiz: [
      {
        q: 'The AHU sensor that every coil-control loop feeds back from is:',
        options: ['Outside air temp', 'Return air temp', 'Supply air temp', 'Filter differential pressure'],
        correct: 2,
      },
      {
        q: 'A correctly sequenced AHU at ~50% loop output has:',
        options: ['Both coils open', 'Both coils shut — deadband', 'Cooling coil full open', 'Heating coil full open'],
        correct: 1,
      },
      {
        q: 'In humid coastal Ghana, economizer changeover should be based on:',
        options: ['Fixed dry-bulb temperature', 'Enthalpy (total heat)', 'A time schedule', 'Return air CO2'],
        correct: 1,
      },
      {
        q: 'The VAV supply fan VFD modulates to hold:',
        options: ['Supply air temperature', 'Duct static pressure', 'Chilled water temperature', 'Zone humidity'],
        correct: 1,
      },
      {
        q: 'A genuine AHU freeze or fire safety must be:',
        options: ['Software logic in the supervisor', 'Hardwired to act independently of controller software', 'Tested only by reading the point', 'Optional on commercial jobs'],
        correct: 1,
      },
      {
        q: 'Decoupler flow from return toward supply in a primary-secondary plant means:',
        options: ['The plant is oversized', 'Stage up another chiller — secondary demand exceeds capacity', 'A pump has failed', 'Normal idle operation'],
        correct: 1,
      },
      {
        q: 'The most common destructive chiller-plant fault, fixed mostly by timers and deadband, is:',
        options: ['Overcooling', 'Short-cycling', 'A low-flow alarm', 'Sensor drift'],
        correct: 1,
      },
      {
        q: 'A pressure-independent VAV box stays stable during duct pressure swings because:',
        options: ['Its damper is larger', 'An inner loop controls measured airflow, not damper position', 'It has a reheat coil', 'Its thermostat is faster'],
        correct: 1,
      },
    ],
    takeaway: 'Module 2 complete. You can now read an AHU, a chilled water plant, and a VAV system as control problems — the core of applied HVAC controls.',
    isBoss: true,
  },
];

export const LESSONS = [
  ...CORE,
  ...MODULE_3,
  ...MODULE_4,
  ...MODULE_5,
  ...MODULE_6,
  ...MODULE_7,
  ...MODULE_8,
  ...MODULE_9,
  ...MODULE_10,
];
