// ============================================================================
// REFERENCE LIBRARY — original, freely-readable BMS reference articles.
// These are quick-reference pieces (distinct from the course lessons): things
// you look up while working, not a structured curriculum.
// Content block types: h3 | p | bullets | callout
// ============================================================================

export const LIBRARY_CATEGORIES = [
  'Reference',
  'Protocols',
  'Field & Signals',
  'Design & Practice',
];

export const LIBRARY = [
  {
    id: 'glossary',
    category: 'Reference',
    title: 'BMS glossary & acronyms',
    summary: 'Every acronym and term you will meet on a BMS job — decoded.',
    readMins: 7,
    content: [
      { type: 'p', text: 'BMS work is dense with acronyms. Keep this open; the vocabulary becomes second nature fast.' },
      { type: 'h3', text: 'Equipment & systems' },
      { type: 'bullets', items: [
        '**BMS / BAS** — Building Management / Automation System',
        '**HVAC** — Heating, Ventilation and Air Conditioning',
        '**AHU** — Air Handling Unit',
        '**FCU** — Fan Coil Unit',
        '**VAV** — Variable Air Volume (terminal box)',
        '**VRF / VRV** — Variable Refrigerant Flow / Volume',
        '**CHW / HW / CW** — Chilled Water / Hot Water / Condenser Water',
        '**VFD / VSD** — Variable Frequency / Speed Drive',
        '**CT** — Cooling Tower (also Current Transformer in metering)',
      ]},
      { type: 'h3', text: 'Signals & I/O' },
      { type: 'bullets', items: [
        '**AI / AO** — Analog Input / Output',
        '**DI / DO** — Digital (Binary) Input / Output',
        '**RTD** — Resistance Temperature Detector (PT100 / PT1000)',
        '**NTC** — Negative Temperature Coefficient thermistor',
        '**DP** — Differential Pressure',
        '**I/O** — Input / Output (the points a controller handles)',
      ]},
      { type: 'h3', text: 'Process & control' },
      { type: 'bullets', items: [
        '**SP** — Setpoint (the target value)',
        '**PV** — Process Variable (the measured value)',
        '**CO** — Control Output (what the controller drives)',
        '**PID** — Proportional + Integral + Derivative control',
        '**SAT / RAT / MAT / OAT** — Supply / Return / Mixed / Outside Air Temperature',
        '**COV** — Change of Value (event-driven reporting)',
        '**DCV** — Demand-Controlled Ventilation',
      ]},
      { type: 'h3', text: 'Controllers & architecture' },
      { type: 'bullets', items: [
        '**DDC** — Direct Digital Control',
        '**ASC** — Application-Specific Controller',
        '**JACE** — a Niagara edge controller / supervisor',
        '**BBMD** — BACnet Broadcast Management Device',
        '**MS/TP** — Master-Slave / Token-Passing (BACnet over RS-485)',
        '**OT / IT** — Operational Technology / Information Technology',
      ]},
      { type: 'h3', text: 'Project & commissioning' },
      { type: 'bullets', items: [
        '**SOO** — Sequence of Operation',
        '**BOQ** — Bill of Quantities',
        '**Cx** — Commissioning',
        '**PFC** — Pre-Functional Checks',
        '**P2P** — Point-to-Point testing',
        '**FPT** — Functional Performance Testing',
        '**FDD** — Fault Detection and Diagnostics',
        '**M&V** — Measurement and Verification',
      ]},
      { type: 'callout', text: 'If a term on a drawing or in a spec is not on this list, that is itself useful — note it and chase the definition. An undefined acronym is a coordination gap waiting to bite.' },
    ],
  },
  {
    id: 'bacnet-ref',
    category: 'Protocols',
    title: 'BACnet quick reference',
    summary: 'Objects, services, ports and the priority array — at a glance.',
    readMins: 6,
    content: [
      { type: 'p', text: 'BACnet models every device as a set of objects, each with properties. You read and write properties using services.' },
      { type: 'h3', text: 'Object types' },
      { type: 'bullets', items: [
        '**AI / AO** — Analog Input / Output (physical, continuous)',
        '**BI / BO** — Binary Input / Output (physical, on/off)',
        '**AV / BV** — Analog / Binary Value (software values — setpoints, flags)',
        '**MSV** — Multi-State Value (an enumerated state)',
        '**Schedule** — writes values on a time program',
        '**Calendar** — a list of special dates a Schedule references',
        '**Trend Log** — records samples of a property over time',
        '**Notification Class** — defines alarm routing and priority',
      ]},
      { type: 'h3', text: 'Core services' },
      { type: 'bullets', items: [
        '**ReadProperty / ReadPropertyMultiple** — fetch property values',
        '**WriteProperty** — command a property value',
        '**Who-Is / I-Am** — device discovery',
        '**COV** — subscribe once; the device pushes updates only on change',
      ]},
      { type: 'h3', text: 'Networks & ports' },
      { type: 'bullets', items: [
        '**BACnet/IP** — over Ethernet, UDP port **47808** (0xBAC0)',
        '**BACnet MS/TP** — over RS-485 twisted pair, daisy-chained, terminated both ends',
        '**BACnet/SC** — Secure Connect: encrypted, authenticated, firewall-friendly',
        'Cross-subnet discovery needs exactly **one BBMD per subnet**',
      ]},
      { type: 'h3', text: 'The priority array' },
      { type: 'p', text: 'A commandable object (e.g. an AO) has a 16-level priority array. Many sources can write; the highest-priority active level wins. Writing NULL at your level relinquishes control back down the stack.' },
      { type: 'callout', text: 'If a BACnet point ignores your write, check the priority array before anything else — a higher-priority entry is almost certainly holding it.' },
    ],
  },
  {
    id: 'modbus-ref',
    category: 'Protocols',
    title: 'Modbus quick reference',
    summary: 'Register types, function codes and the endianness trap.',
    readMins: 5,
    content: [
      { type: 'p', text: 'Modbus is a simple client/server protocol with numbered registers and no self-description — you always need the vendor register map.' },
      { type: 'h3', text: 'RTU vs TCP' },
      { type: 'bullets', items: [
        '**Modbus RTU** — serial, over RS-485; one master, slave IDs 1–247',
        '**Modbus TCP** — over Ethernet, port **502**; allows multiple masters',
      ]},
      { type: 'h3', text: 'Register types' },
      { type: 'bullets', items: [
        '**Coils** — read/write single bits (outputs)',
        '**Discrete Inputs** — read-only single bits (inputs)',
        '**Holding Registers** — read/write 16-bit words (setpoints, most data)',
        '**Input Registers** — read-only 16-bit words (sensor readings)',
      ]},
      { type: 'h3', text: 'Common function codes' },
      { type: 'bullets', items: [
        '**FC01 / FC02** — read coils / read discrete inputs',
        '**FC03 / FC04** — read holding registers / read input registers',
        '**FC05 / FC06** — write single coil / single register',
        '**FC15 / FC16** — write multiple coils / multiple registers',
      ]},
      { type: 'h3', text: 'The endianness trap' },
      { type: 'p', text: 'A 32-bit float spans two 16-bit registers. Byte order and word order give four possible interpretations of the same data. Calibrate against a register whose correct value you already know, then apply that order everywhere for that vendor.' },
      { type: 'callout', text: 'Other Modbus traps: register addresses off by one (the 40001-vs-0 base confusion), signed vs unsigned values, and scaling factors (a register reading 247 that means 24.7).' },
    ],
  },
  {
    id: 'signals-ref',
    category: 'Field & Signals',
    title: 'Signals & wiring reference',
    summary: 'The four I/O types and every common field signal standard.',
    readMins: 6,
    content: [
      { type: 'h3', text: 'The four I/O types' },
      { type: 'bullets', items: [
        '**AI (Analog Input)** — reads a continuous value: temperature, pressure, humidity',
        '**AO (Analog Output)** — drives a continuous value: modulating valves, dampers, VFD speed',
        '**DI (Digital Input)** — reads on/off: status feedback, alarms, dry contacts',
        '**DO (Digital Output)** — switches on/off: relays starting motors, energizing coils',
      ]},
      { type: 'h3', text: 'Analog signal standards' },
      { type: 'bullets', items: [
        '**0–10V DC** — most common AI/AO standard. 0V = 0%, 10V = 100%. Cheap, distance-limited.',
        '**4–20mA** — industrial AI standard. Noise-immune, longer runs. The 4mA floor means a broken wire reads 0mA — instantly detectable.',
        '**2–10V** — a 0–10V variant with a live-zero floor, like 4–20mA',
      ]},
      { type: 'h3', text: 'Temperature sensing' },
      { type: 'bullets', items: [
        '**RTD (PT100 / PT1000)** — platinum resistance; very accurate and stable. PT1000 preferred for BMS.',
        '**Thermistor (10kΩ / 20kΩ NTC)** — cheaper, sensitive over a narrow range, drifts more',
        '**Thermocouple** — wide range, used for high temperatures (flues, boilers); rare in comfort HVAC',
      ]},
      { type: 'h3', text: 'Digital signals' },
      { type: 'bullets', items: [
        '**Dry contact** — a voltage-free switch closure for a DI',
        '**Pulse** — a counted DI for meters (1 pulse = X kWh or X litres)',
        '**Relay / triac DO** — switches a load; check the contact rating against the load',
      ]},
      { type: 'callout', text: 'In hot, humid, electrically-noisy environments, 4–20mA on long or critical runs pays for its small cost premium — 0–10V signals drift and pick up noise more than spec sheets suggest.' },
    ],
  },
  {
    id: 'ahu-soo',
    category: 'Design & Practice',
    title: 'AHU sequence of operation — reference',
    summary: 'A reusable, testable sequence-of-operation template for an AHU.',
    readMins: 7,
    content: [
      { type: 'p', text: 'A reference SOO for a VAV air handling unit. Every line names a controlled element, a target and a tolerance — so a commissioning engineer can prove it true or false on site. Adapt the values to the project.' },
      { type: 'h3', text: 'Modes of operation' },
      { type: 'bullets', items: [
        '**Occupied** — per the building schedule',
        '**Unoccupied** — fans off; night setback maintained by the zones',
        '**Warm-up / Cool-down** — pre-occupancy conditioning with outside air minimised',
        '**Fire** — driven by the fire alarm interface',
      ]},
      { type: 'h3', text: 'Supply fan' },
      { type: 'callout', text: 'The supply fan starts when the schedule is Occupied OR a zone exceeds its setback limit. The VFD modulates to maintain a duct static pressure setpoint (e.g. 250 Pa ± 25 Pa), with the setpoint reset down by trim-and-respond logic from VAV box demand.' },
      { type: 'h3', text: 'Supply air temperature' },
      { type: 'callout', text: 'A single sequenced PID loop holds the supply air temperature setpoint (e.g. 13°C ± 0.5°C): 0–50% output modulates the heating valve 100→0%, ~50% is a deadband with both coils shut, 50–100% modulates the cooling valve 0→100%.' },
      { type: 'h3', text: 'Economizer' },
      { type: 'callout', text: 'When enabled, the OA/RA dampers act as the first stage of cooling. Enable on enthalpy (total heat) changeover, not dry-bulb, in humid climates. The OA damper never closes below its minimum ventilation position.' },
      { type: 'h3', text: 'Safeties & interlocks' },
      { type: 'bullets', items: [
        '**Freezestat** — hardwired; stops the fan and closes the OA damper near freezing',
        '**Duct smoke detector** — hardwired; stops the fan, signals the fire system',
        '**High static cutout** — hardwired; trips the fan before ductwork is damaged',
        '**Fire alarm** — on signal: fan stops within 5s, dampers drive to their defined safe positions',
      ]},
      { type: 'h3', text: 'Alarms' },
      { type: 'bullets', items: [
        'Supply air temperature outside setpoint band for a sustained period',
        'Fan commanded on but no run status (fan failure)',
        'Filter differential pressure above the dirty-filter threshold',
        'Any safety tripped — high priority',
      ]},
    ],
  },
  {
    id: 'g36',
    category: 'Design & Practice',
    title: 'ASHRAE Guideline 36 — overview',
    summary: 'What Guideline 36 standardizes, and how to actually use it.',
    readMins: 5,
    content: [
      { type: 'h3', text: 'What it is' },
      { type: 'p', text: 'ASHRAE Guideline 36, "High-Performance Sequences of Operation for HVAC Systems", is a library of detailed, proven, standardized control sequences for common HVAC equipment. It exists so engineers stop reinventing — and re-debugging — sequences the industry has already solved.' },
      { type: 'h3', text: 'What it standardizes' },
      { type: 'bullets', items: [
        'AHU control — supply air temperature and static pressure reset, economizer logic',
        'VAV terminal unit control — pressure-independent airflow, reheat',
        'Chilled and hot water plant sequencing',
        'Trim-and-respond reset logic — resetting setpoints to the minimum that still satisfies demand',
        'Alarming and fault detection built into the sequences',
      ]},
      { type: 'h3', text: 'How to use it' },
      { type: 'bullets', items: [
        'Start your SOO from the relevant G36 sequence rather than a blank page',
        'Adapt the setpoints, tolerances and modes to the specific project',
        'Keep the G36 reset strategies — they are where most of the energy savings live',
        'Cite G36 in your specification so bidders know the expected standard',
      ]},
      { type: 'callout', text: 'Guideline 36 is the single highest-leverage reference a BMS designer can own. A G36-based SOO commissions cleaner because the logic is already proven and the language is already testable.' },
    ],
  },
  {
    id: 'controller-select',
    category: 'Design & Practice',
    title: 'Controller selection & I/O sizing',
    summary: 'A reference checklist for picking and sizing DDC controllers.',
    readMins: 5,
    content: [
      { type: 'h3', text: 'The sizing method' },
      { type: 'bullets', items: [
        'Start from the point list — count AI, AO, DI and DO per piece of equipment',
        'Add roughly **20% spare I/O** of each type — per controller, not just per building',
        'Round up to a real controller (or controller-plus-expansion) that covers the count',
        'Confirm processing and memory headroom for the logic, trends and alarms it must run',
      ]},
      { type: 'h3', text: 'Choosing the controller class' },
      { type: 'bullets', items: [
        '**Application-specific (ASC)** — for many repeated standard units (VAVs, FCUs). Configured, not programmed. Cheap, fast.',
        '**Programmable / general-purpose** — for complex unique plant (AHUs, chiller plants). You write the logic. More I/O, more cost.',
        'A typical building uses many ASCs and a handful of programmable controllers',
      ]},
      { type: 'h3', text: 'Selection checklist' },
      { type: 'bullets', items: [
        'Protocol — BACnet native (IP or MS/TP) preferred; avoid gateway-only integration',
        'I/O count covers the point list plus spare',
        'Programming environment is widely known (avoids contractor lock-in)',
        'One controller serves one logical system — so a fault stays contained',
        'Physical panel space and spare DIN rail left for future additions',
      ]},
      { type: 'callout', text: 'The cheapest capacity you will ever buy is spare capacity bought at design time. Adding a point to a controller with spare I/O is trivial; adding one to a full controller means a new controller, panel space and a site visit.' },
    ],
  },
];
