// ============================================================================
// REFERENCE LIBRARY — original, freely-readable BMS reference articles.
// These are quick-reference pieces (distinct from the course lessons): things
// you look up while working, not a structured curriculum.
// Content block types: h3 | p | bullets | callout
// ============================================================================

export const LIBRARY_CATEGORIES = [
  'Reference',
  'Protocols',
  'Controllers & Networks',
  'Field & Signals',
  'Design & Practice',
];

export const LIBRARY = [
  {
    id: 'glossary',
    category: 'Reference',
    title: 'BMS glossary & acronyms',
    summary: 'Every acronym and term you will meet on a BMS job — decoded.',
    readMins: 7,
    content: [
      { type: 'p', text: 'BMS work is dense with acronyms. Keep this open; the vocabulary becomes second nature fast.' },
      { type: 'h3', text: 'Equipment & systems' },
      { type: 'bullets', items: [
        '**BMS / BAS** — Building Management / Automation System',
        '**HVAC** — Heating, Ventilation and Air Conditioning',
        '**AHU** — Air Handling Unit',
        '**FCU** — Fan Coil Unit',
        '**VAV** — Variable Air Volume (terminal box)',
        '**VRF / VRV** — Variable Refrigerant Flow / Volume',
        '**CHW / HW / CW** — Chilled Water / Hot Water / Condenser Water',
        '**VFD / VSD** — Variable Frequency / Speed Drive',
        '**CT** — Cooling Tower (also Current Transformer in metering)',
      ]},
      { type: 'h3', text: 'Signals & I/O' },
      { type: 'bullets', items: [
        '**AI / AO** — Analog Input / Output',
        '**DI / DO** — Digital (Binary) Input / Output',
        '**RTD** — Resistance Temperature Detector (PT100 / PT1000)',
        '**NTC** — Negative Temperature Coefficient thermistor',
        '**DP** — Differential Pressure',
        '**I/O** — Input / Output (the points a controller handles)',
      ]},
      { type: 'h3', text: 'Process & control' },
      { type: 'bullets', items: [
        '**SP** — Setpoint (the target value)',
        '**PV** — Process Variable (the measured value)',
        '**CO** — Control Output (what the controller drives)',
        '**PID** — Proportional + Integral + Derivative control',
        '**SAT / RAT / MAT / OAT** — Supply / Return / Mixed / Outside Air Temperature',
        '**COV** — Change of Value (event-driven reporting)',
        '**DCV** — Demand-Controlled Ventilation',
      ]},
      { type: 'h3', text: 'Controllers & architecture' },
      { type: 'bullets', items: [
        '**DDC** — Direct Digital Control',
        '**ASC** — Application-Specific Controller',
        '**JACE** — a Niagara edge controller / supervisor',
        '**BBMD** — BACnet Broadcast Management Device',
        '**MS/TP** — Master-Slave / Token-Passing (BACnet over RS-485)',
        '**OT / IT** — Operational Technology / Information Technology',
      ]},
      { type: 'h3', text: 'Project & commissioning' },
      { type: 'bullets', items: [
        '**SOO** — Sequence of Operation',
        '**BOQ** — Bill of Quantities',
        '**Cx** — Commissioning',
        '**PFC** — Pre-Functional Checks',
        '**P2P** — Point-to-Point testing',
        '**FPT** — Functional Performance Testing',
        '**FDD** — Fault Detection and Diagnostics',
        '**M&V** — Measurement and Verification',
      ]},
      { type: 'callout', text: 'If a term on a drawing or in a spec is not on this list, that is itself useful — note it and chase the definition. An undefined acronym is a coordination gap waiting to bite.' },
    ],
  },
  {
    id: 'bacnet-ref',
    category: 'Protocols',
    title: 'BACnet quick reference',
    summary: 'Objects, services, ports and the priority array — at a glance.',
    readMins: 6,
    content: [
      { type: 'p', text: 'BACnet models every device as a set of objects, each with properties. You read and write properties using services.' },
      { type: 'h3', text: 'Object types' },
      { type: 'bullets', items: [
        '**AI / AO** — Analog Input / Output (physical, continuous)',
        '**BI / BO** — Binary Input / Output (physical, on/off)',
        '**AV / BV** — Analog / Binary Value (software values — setpoints, flags)',
        '**MSV** — Multi-State Value (an enumerated state)',
        '**Schedule** — writes values on a time program',
        '**Calendar** — a list of special dates a Schedule references',
        '**Trend Log** — records samples of a property over time',
        '**Notification Class** — defines alarm routing and priority',
      ]},
      { type: 'h3', text: 'Core services' },
      { type: 'bullets', items: [
        '**ReadProperty / ReadPropertyMultiple** — fetch property values',
        '**WriteProperty** — command a property value',
        '**Who-Is / I-Am** — device discovery',
        '**COV** — subscribe once; the device pushes updates only on change',
      ]},
      { type: 'h3', text: 'Networks & ports' },
      { type: 'bullets', items: [
        '**BACnet/IP** — over Ethernet, UDP port **47808** (0xBAC0)',
        '**BACnet MS/TP** — over RS-485 twisted pair, daisy-chained, terminated both ends',
        '**BACnet/SC** — Secure Connect: encrypted, authenticated, firewall-friendly',
        'Cross-subnet discovery needs exactly **one BBMD per subnet**',
      ]},
      { type: 'h3', text: 'The priority array' },
      { type: 'p', text: 'A commandable object (e.g. an AO) has a 16-level priority array. Many sources can write; the highest-priority active level wins. Writing NULL at your level relinquishes control back down the stack.' },
      { type: 'callout', text: 'If a BACnet point ignores your write, check the priority array before anything else — a higher-priority entry is almost certainly holding it.' },
    ],
  },
  {
    id: 'modbus-ref',
    category: 'Protocols',
    title: 'Modbus quick reference',
    summary: 'Register types, function codes and the endianness trap.',
    readMins: 5,
    content: [
      { type: 'p', text: 'Modbus is a simple client/server protocol with numbered registers and no self-description — you always need the vendor register map.' },
      { type: 'h3', text: 'RTU vs TCP' },
      { type: 'bullets', items: [
        '**Modbus RTU** — serial, over RS-485; one master, slave IDs 1–247',
        '**Modbus TCP** — over Ethernet, port **502**; allows multiple masters',
      ]},
      { type: 'h3', text: 'Register types' },
      { type: 'bullets', items: [
        '**Coils** — read/write single bits (outputs)',
        '**Discrete Inputs** — read-only single bits (inputs)',
        '**Holding Registers** — read/write 16-bit words (setpoints, most data)',
        '**Input Registers** — read-only 16-bit words (sensor readings)',
      ]},
      { type: 'h3', text: 'Common function codes' },
      { type: 'bullets', items: [
        '**FC01 / FC02** — read coils / read discrete inputs',
        '**FC03 / FC04** — read holding registers / read input registers',
        '**FC05 / FC06** — write single coil / single register',
        '**FC15 / FC16** — write multiple coils / multiple registers',
      ]},
      { type: 'h3', text: 'The endianness trap' },
      { type: 'p', text: 'A 32-bit float spans two 16-bit registers. Byte order and word order give four possible interpretations of the same data. Calibrate against a register whose correct value you already know, then apply that order everywhere for that vendor.' },
      { type: 'callout', text: 'Other Modbus traps: register addresses off by one (the 40001-vs-0 base confusion), signed vs unsigned values, and scaling factors (a register reading 247 that means 24.7).' },
    ],
  },
  {
    id: 'signals-ref',
    category: 'Field & Signals',
    title: 'Signals & wiring reference',
    summary: 'The four I/O types and every common field signal standard.',
    readMins: 6,
    content: [
      { type: 'h3', text: 'The four I/O types' },
      { type: 'bullets', items: [
        '**AI (Analog Input)** — reads a continuous value: temperature, pressure, humidity',
        '**AO (Analog Output)** — drives a continuous value: modulating valves, dampers, VFD speed',
        '**DI (Digital Input)** — reads on/off: status feedback, alarms, dry contacts',
        '**DO (Digital Output)** — switches on/off: relays starting motors, energizing coils',
      ]},
      { type: 'h3', text: 'Analog signal standards' },
      { type: 'bullets', items: [
        '**0–10V DC** — most common AI/AO standard. 0V = 0%, 10V = 100%. Cheap, distance-limited.',
        '**4–20mA** — industrial AI standard. Noise-immune, longer runs. The 4mA floor means a broken wire reads 0mA — instantly detectable.',
        '**2–10V** — a 0–10V variant with a live-zero floor, like 4–20mA',
      ]},
      { type: 'h3', text: 'Temperature sensing' },
      { type: 'bullets', items: [
        '**RTD (PT100 / PT1000)** — platinum resistance; very accurate and stable. PT1000 preferred for BMS.',
        '**Thermistor (10kΩ / 20kΩ NTC)** — cheaper, sensitive over a narrow range, drifts more',
        '**Thermocouple** — wide range, used for high temperatures (flues, boilers); rare in comfort HVAC',
      ]},
      { type: 'h3', text: 'Digital signals' },
      { type: 'bullets', items: [
        '**Dry contact** — a voltage-free switch closure for a DI',
        '**Pulse** — a counted DI for meters (1 pulse = X kWh or X litres)',
        '**Relay / triac DO** — switches a load; check the contact rating against the load',
      ]},
      { type: 'callout', text: 'In hot, humid, electrically-noisy environments, 4–20mA on long or critical runs pays for its small cost premium — 0–10V signals drift and pick up noise more than spec sheets suggest.' },
    ],
  },
  {
    id: 'ahu-soo',
    category: 'Design & Practice',
    title: 'AHU sequence of operation — reference',
    summary: 'A reusable, testable sequence-of-operation template for an AHU.',
    readMins: 7,
    content: [
      { type: 'p', text: 'A reference SOO for a VAV air handling unit. Every line names a controlled element, a target and a tolerance — so a commissioning engineer can prove it true or false on site. Adapt the values to the project.' },
      { type: 'h3', text: 'Modes of operation' },
      { type: 'bullets', items: [
        '**Occupied** — per the building schedule',
        '**Unoccupied** — fans off; night setback maintained by the zones',
        '**Warm-up / Cool-down** — pre-occupancy conditioning with outside air minimised',
        '**Fire** — driven by the fire alarm interface',
      ]},
      { type: 'h3', text: 'Supply fan' },
      { type: 'callout', text: 'The supply fan starts when the schedule is Occupied OR a zone exceeds its setback limit. The VFD modulates to maintain a duct static pressure setpoint (e.g. 250 Pa ± 25 Pa), with the setpoint reset down by trim-and-respond logic from VAV box demand.' },
      { type: 'h3', text: 'Supply air temperature' },
      { type: 'callout', text: 'A single sequenced PID loop holds the supply air temperature setpoint (e.g. 13°C ± 0.5°C): 0–50% output modulates the heating valve 100→0%, ~50% is a deadband with both coils shut, 50–100% modulates the cooling valve 0→100%.' },
      { type: 'h3', text: 'Economizer' },
      { type: 'callout', text: 'When enabled, the OA/RA dampers act as the first stage of cooling. Enable on enthalpy (total heat) changeover, not dry-bulb, in humid climates. The OA damper never closes below its minimum ventilation position.' },
      { type: 'h3', text: 'Safeties & interlocks' },
      { type: 'bullets', items: [
        '**Freezestat** — hardwired; stops the fan and closes the OA damper near freezing',
        '**Duct smoke detector** — hardwired; stops the fan, signals the fire system',
        '**High static cutout** — hardwired; trips the fan before ductwork is damaged',
        '**Fire alarm** — on signal: fan stops within 5s, dampers drive to their defined safe positions',
      ]},
      { type: 'h3', text: 'Alarms' },
      { type: 'bullets', items: [
        'Supply air temperature outside setpoint band for a sustained period',
        'Fan commanded on but no run status (fan failure)',
        'Filter differential pressure above the dirty-filter threshold',
        'Any safety tripped — high priority',
      ]},
    ],
  },
  {
    id: 'g36',
    category: 'Design & Practice',
    title: 'ASHRAE Guideline 36 — overview',
    summary: 'What Guideline 36 standardizes, and how to actually use it.',
    readMins: 5,
    content: [
      { type: 'h3', text: 'What it is' },
      { type: 'p', text: 'ASHRAE Guideline 36, "High-Performance Sequences of Operation for HVAC Systems", is a library of detailed, proven, standardized control sequences for common HVAC equipment. It exists so engineers stop reinventing — and re-debugging — sequences the industry has already solved.' },
      { type: 'h3', text: 'What it standardizes' },
      { type: 'bullets', items: [
        'AHU control — supply air temperature and static pressure reset, economizer logic',
        'VAV terminal unit control — pressure-independent airflow, reheat',
        'Chilled and hot water plant sequencing',
        'Trim-and-respond reset logic — resetting setpoints to the minimum that still satisfies demand',
        'Alarming and fault detection built into the sequences',
      ]},
      { type: 'h3', text: 'How to use it' },
      { type: 'bullets', items: [
        'Start your SOO from the relevant G36 sequence rather than a blank page',
        'Adapt the setpoints, tolerances and modes to the specific project',
        'Keep the G36 reset strategies — they are where most of the energy savings live',
        'Cite G36 in your specification so bidders know the expected standard',
      ]},
      { type: 'callout', text: 'Guideline 36 is the single highest-leverage reference a BMS designer can own. A G36-based SOO commissions cleaner because the logic is already proven and the language is already testable.' },
    ],
  },
  {
    id: 'controller-select',
    category: 'Design & Practice',
    title: 'Controller selection & I/O sizing',
    summary: 'A reference checklist for picking and sizing DDC controllers.',
    readMins: 5,
    content: [
      { type: 'h3', text: 'The sizing method' },
      { type: 'bullets', items: [
        'Start from the point list — count AI, AO, DI and DO per piece of equipment',
        'Add roughly **20% spare I/O** of each type — per controller, not just per building',
        'Round up to a real controller (or controller-plus-expansion) that covers the count',
        'Confirm processing and memory headroom for the logic, trends and alarms it must run',
      ]},
      { type: 'h3', text: 'Choosing the controller class' },
      { type: 'bullets', items: [
        '**Application-specific (ASC)** — for many repeated standard units (VAVs, FCUs). Configured, not programmed. Cheap, fast.',
        '**Programmable / general-purpose** — for complex unique plant (AHUs, chiller plants). You write the logic. More I/O, more cost.',
        'A typical building uses many ASCs and a handful of programmable controllers',
      ]},
      { type: 'h3', text: 'Selection checklist' },
      { type: 'bullets', items: [
        'Protocol — BACnet native (IP or MS/TP) preferred; avoid gateway-only integration',
        'I/O count covers the point list plus spare',
        'Programming environment is widely known (avoids contractor lock-in)',
        'One controller serves one logical system — so a fault stays contained',
        'Physical panel space and spare DIN rail left for future additions',
      ]},
      { type: 'callout', text: 'The cheapest capacity you will ever buy is spare capacity bought at design time. Adding a point to a controller with spare I/O is trivial; adding one to a full controller means a new controller, panel space and a site visit.' },
    ],
  },
  {
    id: 'knx-dali',
    category: 'Protocols',
    title: 'KNX & DALI quick reference',
    summary: 'The two protocols that rule lighting and room control — and how the BMS meets them.',
    readMins: 5,
    content: [
      { type: 'h3', text: 'KNX' },
      { type: 'bullets', items: [
        'A decentralized protocol for lighting, blinds and room control, common in Europe and the Middle East',
        'Runs mostly on a dedicated twisted pair; every device is a peer — no central controller required',
        'Devices are linked by **group addresses** — a switch and a light share a group address, and that is the link',
        'Commissioned with one tool: **ETS** (Engineering Tool Software)',
      ]},
      { type: 'h3', text: 'DALI' },
      { type: 'bullets', items: [
        '**DALI-2** — Digital Addressable Lighting Interface, a dedicated bus for light fittings',
        'Each fitting (driver) gets a digital address — dim and group fixtures individually in software, no rewiring',
        'Reports back lamp failure, hours run and energy use',
        'One DALI line supports up to 64 control-gear addresses',
      ]},
      { type: 'h3', text: 'Meeting the BMS' },
      { type: 'p', text: 'The BMS rarely speaks KNX or DALI natively. A gateway translates them to BACnet or Modbus, exposing lighting status and control as points the BMS can use.' },
      { type: 'callout', text: 'When scoping lighting integration, the gateway is the critical line item. Confirm exactly which points it exposes — many give on/off and level but hide per-fixture fault data.' },
    ],
  },
  {
    id: 'modern-protocols',
    category: 'Protocols',
    title: 'Modern protocols — MQTT, OPC-UA & REST',
    summary: 'How BMS data gets up to dashboards, the cloud and other software.',
    readMins: 5,
    content: [
      { type: 'h3', text: 'MQTT' },
      { type: 'bullets', items: [
        'A lightweight publish/subscribe messaging protocol — the backbone of IoT',
        'Devices publish data to topics on a broker; anything interested subscribes',
        'Tiny overhead and tolerant of flaky connections — ideal for pushing BMS data to the cloud',
      ]},
      { type: 'h3', text: 'OPC-UA' },
      { type: 'bullets', items: [
        'An industrial interoperability standard — bridges a BMS to manufacturing and SCADA systems',
        'Strongly typed and secure, with a rich information model',
        'Common where a building sits inside an industrial site',
      ]},
      { type: 'h3', text: 'REST APIs & webhooks' },
      { type: 'bullets', items: [
        'Modern supervisors expose **REST APIs** — read and write points over HTTPS with JSON',
        '**Webhooks** push events out to other apps — an alarm firing a message, for example',
        'This is how a BMS connects to analytics platforms, mobile apps and custom software',
      ]},
      { type: 'callout', text: 'The modern BMS pattern: BACnet and Modbus down at the equipment, MQTT or REST up to the cloud. The edge controller is the translator between those two worlds.' },
    ],
  },
  {
    id: 'architecture',
    category: 'Controllers & Networks',
    title: 'BMS architecture — the 3-tier model',
    summary: 'The pyramid every BMS follows: field, automation, supervisory.',
    readMins: 5,
    content: [
      { type: 'h3', text: 'The three tiers' },
      { type: 'p', text: 'Every BMS, from a small clinic system to an airport, follows the same pyramidal shape — many devices at the bottom, few at the top.' },
      { type: 'bullets', items: [
        '**Tier 1 — Field layer** — sensors, actuators, valves, dampers, VFDs, meters. The hands and eyes; thousands of points.',
        '**Tier 2 — Automation layer** — DDC controllers and JACEs running the sequences locally; tens of controllers.',
        '**Tier 3 — Supervisory layer** — servers and workstations for graphics, schedules, alarms and trends; one or two.',
      ]},
      { type: 'h3', text: 'Why the middle tier matters' },
      { type: 'p', text: 'Real-time control lives in Tier 2. If the supervisor goes offline, the field controllers keep the building running on their own. A design where control depends on the head-end being up is a red flag.' },
      { type: 'callout', text: 'Rule of thumb: Tier 1 = thousands of points, Tier 2 = tens of controllers, Tier 3 = one or two servers. Cost often runs the other way — Tier 3 software licences are frequently the single most expensive line item.' },
    ],
  },
  {
    id: 'networks-security',
    category: 'Controllers & Networks',
    title: 'BMS networks & cybersecurity',
    summary: 'Network topology, OT segmentation and hardening a BMS against attack.',
    readMins: 6,
    content: [
      { type: 'h3', text: 'The layered network' },
      { type: 'bullets', items: [
        '**Field bus** — MS/TP or Modbus RTU trunks, daisy-chained between field controllers',
        '**IP backbone** — Ethernet linking JACEs and programmable controllers, often BACnet/IP',
        '**Supervisory network** — where servers and operator workstations sit',
      ]},
      { type: 'h3', text: 'OT segmentation' },
      { type: 'p', text: 'A BMS is operational technology (OT). It should not share a flat network with email and laptops. A VLAN — or a physically separate network — behind a firewall isolates it.' },
      { type: 'bullets', items: [
        'Limits the blast radius — malware on the office LAN cannot reach the chillers',
        'Controls traffic — only defined ports and devices cross between the OT and IT sides',
      ]},
      { type: 'h3', text: 'Hardening checklist' },
      { type: 'bullets', items: [
        'Change every default password; never share credentials',
        'Allow remote access only via VPN with multi-factor authentication — never expose it directly to the internet',
        'Keep controllers and supervisors patched',
        'Prefer **BACnet/SC** (Secure Connect) for new work — encrypted and authenticated',
        'Use unique per-user accounts, least-privilege roles, and keep logs and audit trails',
      ]},
      { type: 'callout', text: 'The highest-impact, lowest-cost security action on any BMS is changing default passwords. A large share of real BMS compromises trace straight back to a default or shared credential.' },
    ],
  },
  {
    id: 'niagara',
    category: 'Controllers & Networks',
    title: 'Niagara N4 — orientation',
    summary: 'The mental model for the most widely used BMS framework.',
    readMins: 6,
    content: [
      { type: 'h3', text: 'The core pieces' },
      { type: 'bullets', items: [
        '**Niagara Framework** — a vendor-neutral software platform that runs on JACEs and on servers',
        '**Host** — the hardware and OS running Niagara: a JACE, or a Windows/Linux server',
        '**Station** — the running application: the database of points, logic, schedules and graphics. One per host.',
        '**Workbench** — the engineering tool you build and connect with',
      ]},
      { type: 'h3', text: 'The one-line hierarchy' },
      { type: 'p', text: 'Workbench (your tool) connects to a Host (a JACE or server) which runs a Station (the live application). A Supervisor is simply a station on a server, sitting above many JACE stations.' },
      { type: 'h3', text: 'Working inside a station' },
      { type: 'bullets', items: [
        '**Drivers** discover field devices; learned points become **proxy points** in the station',
        '**Wire sheets** are the visual canvas where control logic is built from components',
        '**Extensions** add behaviour to a point — alarming, or history for trending',
        '**PX pages** are the graphics; **bindings** link a widget to a live point',
        '**Tags** (Project Haystack) attach machine-readable meaning to points',
      ]},
      { type: 'callout', text: 'Niagara dominates because it is vendor-neutral integration glue — it normalizes BACnet, Modbus and more into one model. Niagara skills, and the TCP certification, are among the highest-ROI things a BMS engineer can learn.' },
    ],
  },
  {
    id: 'sensors',
    category: 'Field & Signals',
    title: 'Sensors reference',
    summary: 'Temperature, humidity, pressure, CO2, flow and metering — what to use and watch for.',
    readMins: 6,
    content: [
      { type: 'h3', text: 'Temperature' },
      { type: 'bullets', items: [
        '**RTD (PT100 / PT1000)** — platinum resistance; very accurate and stable. PT1000 is the BMS default for anything that matters.',
        '**Thermistor (10kΩ NTC)** — cheaper, fine for comfort ranges, drifts more over time',
        '**Thermocouple** — wide range, used for high temperatures such as flues and boilers',
        'Placement beats sensor grade — a great sensor in sun, draft or a dead pocket reads worse than a cheap one placed well',
      ]},
      { type: 'h3', text: 'Humidity' },
      { type: 'bullets', items: [
        'Almost all BMS humidity sensors are capacitive',
        'They drift — plan to recalibrate every 1 to 2 years; humid climates accelerate it',
        'Control humidity to a band, not a tight setpoint',
      ]},
      { type: 'h3', text: 'Pressure' },
      { type: 'bullets', items: [
        '**Differential pressure** — across filters (dirty-filter detection), fans and coils',
        '**Static pressure** — duct pressure, used for VAV supply-fan control',
        'Match the sensor range to the job — a 0–2500 Pa sensor is useless on a 0–100 Pa duct measurement',
      ]},
      { type: 'h3', text: 'CO2, flow & metering' },
      { type: 'bullets', items: [
        'CO2 sensors use the NDIR (infrared) principle and drive demand-controlled ventilation',
        'Flow — electromagnetic for water, ultrasonic for retrofits, turbine or vortex when cost matters',
        'Energy (BTU) meters combine a flow meter with two temperatures; bill tenants only from revenue-grade meters',
      ]},
      { type: 'callout', text: 'Two recurring sensor themes: range and drift. The wrong range gives garbage resolution; a sensor never recalibrated slowly lies. Build recalibration into the maintenance plan.' },
    ],
  },
  {
    id: 'valves-dampers',
    category: 'Field & Signals',
    title: 'Valves, dampers & actuators reference',
    summary: 'Characteristics, sizing, fail position — and the PICV.',
    readMins: 6,
    content: [
      { type: 'h3', text: 'Valve characteristics' },
      { type: 'bullets', items: [
        '**Quick-opening** — most flow change happens early in the stroke; used for 2-position service',
        '**Linear** — flow is proportional to stroke',
        '**Equal-percentage** — small flow near closed, large near open; it cancels a coil non-linearity, so it is the default for coil control valves',
      ]},
      { type: 'h3', text: 'Sizing — Cv & authority' },
      { type: 'bullets', items: [
        'Size a valve on its flow coefficient **Cv (or Kv)**, never on pipe diameter',
        '**Authority** — the valve share of the loop pressure drop; aim for 0.25 to 0.5 or higher',
        'A valve sized on pipe size ends up oversized with poor authority — it controls within a tiny part of its stroke and slams',
      ]},
      { type: 'h3', text: 'Dampers' },
      { type: 'bullets', items: [
        '**Opposed-blade** for modulating control (more linear); **parallel-blade** is fine for 2-position service',
        'Even a closed damper leaks — specify low-leakage dampers for outside-air and isolation duties',
      ]},
      { type: 'h3', text: 'Actuators & fail position' },
      { type: 'bullets', items: [
        '**Spring-return** drives to a defined safe position on power loss; **non-spring** fails in place',
        'Control types: modulating (0–10V / 4–20mA), floating (3-point), and 2-position',
        'Size for torque and close-off pressure — undersized, a valve will not fully shut',
      ]},
      { type: 'callout', text: 'A PICV (pressure-independent control valve) builds a differential-pressure regulator into the valve, holding a set flow regardless of pressure swings elsewhere — making hydronic balancing largely automatic.' },
    ],
  },
  {
    id: 'chw-soo',
    category: 'Design & Practice',
    title: 'Chilled water plant — sequence of operation',
    summary: 'A reference sequence for a multi-chiller plant: staging, rotation, resets.',
    readMins: 7,
    content: [
      { type: 'p', text: 'A reference sequence of operation for a chilled water plant with two or more chillers. Adapt the thresholds and timers to the project and to the chiller manufacturer limits.' },
      { type: 'h3', text: 'Pumping arrangement' },
      { type: 'bullets', items: [
        '**Primary-secondary** — constant flow through the chillers, variable flow to the building, separated by a decoupler',
        '**Variable primary flow** — one set of variable-speed pumps, with a minimum-flow bypass valve protecting the chillers',
      ]},
      { type: 'h3', text: 'Staging' },
      { type: 'callout', text: 'A chiller stages on when the running chillers cannot hold the chilled water supply temperature for a sustained period, or run above a load threshold (for example, above 90% for 15 minutes). A chiller stages off when load drops below a lower threshold. Every stage change uses a time delay and a deadband so a brief spike does not trigger it.' },
      { type: 'h3', text: 'Lead/lag rotation' },
      { type: 'bullets', items: [
        'The lead chiller starts first and stops last; the lag follows',
        'Rotate lead/lag on runtime hours so wear is even and standby capacity is regularly proven',
      ]},
      { type: 'h3', text: 'Resets & safeties' },
      { type: 'bullets', items: [
        '**Chilled water temperature reset** — raise the supply setpoint when cooling demand is low',
        '**Pump pressure reset** — trim toward the lowest differential pressure that still satisfies the load',
        'Minimum-flow protection — the bypass valve in a variable primary plant',
        'Minimum-runtime and minimum-off timers to prevent short-cycling',
      ]},
      { type: 'callout', text: 'The number-one chiller-plant fault in the field is short-cycling — repeated rapid start and stop. The fix is almost always longer timers and a wider staging deadband, not new hardware.' },
    ],
  },
  {
    id: 'vav',
    category: 'Design & Practice',
    title: 'VAV terminal units — control reference',
    summary: 'Pressure-independent control, cooling, and the reheat sequence.',
    readMins: 5,
    content: [
      { type: 'h3', text: 'What a VAV box does' },
      { type: 'p', text: 'A Variable Air Volume box is a damper plus an airflow sensor in a duct serving one zone. It throttles airflow to hold the zone at setpoint; many boxes also have a reheat coil.' },
      { type: 'h3', text: 'Pressure-independent control' },
      { type: 'bullets', items: [
        '**Outer loop** — the zone thermostat compares room temperature to setpoint and outputs an airflow setpoint, not a damper position',
        '**Inner loop** — a fast loop reads the box airflow sensor and modulates the damper to hit that airflow setpoint',
        'Because the inner loop controls measured airflow, a duct-pressure swing is corrected instantly — the zone loop never sees it',
      ]},
      { type: 'h3', text: 'Cooling & reheat sequence' },
      { type: 'bullets', items: [
        'Zone too warm → airflow rises between the minimum and the maximum cooling airflow',
        'Zone satisfied → airflow drops to the minimum — a ventilation floor, enough fresh air for occupants',
        'Zone too cold → airflow stays at minimum and the reheat valve modulates',
        'Never reheat at high airflow — heating a large airflow to satisfy one cold zone is the classic VAV energy sin',
      ]},
      { type: 'callout', text: 'Pressure-independent simply means the box has an airflow sensor and an inner airflow loop. A pressure-dependent box has neither — the thermostat drives the damper directly, and it is exactly as unstable as that sounds.' },
    ],
  },
  {
    id: 'vrf-integration',
    category: 'Design & Practice',
    title: 'VRF integration with the BMS',
    summary: 'How VRF systems connect to a BMS — gateways, exposed points and pitfalls.',
    readMins: 6,
    content: [
      { type: 'h3', text: 'VRF from a controls view' },
      { type: 'p', text: 'A VRF (Variable Refrigerant Flow) system is largely a closed, self-contained control system from the manufacturer. The BMS does not run the refrigerant logic — it monitors and supervises the VRF through a gateway.' },
      { type: 'h3', text: 'The gateway' },
      { type: 'bullets', items: [
        'Each manufacturer supplies a gateway that translates its proprietary VRF bus to BACnet or Modbus',
        'Examples include the Daikin DMS / iTM, the Midea CCM gateway, and the Mitsubishi AE-200',
        'The gateway defines exactly what the BMS can see and do — it is the critical scope item',
      ]},
      { type: 'h3', text: 'What VRF typically exposes' },
      { type: 'bullets', items: [
        'Per indoor unit — on/off, mode, setpoint, room temperature, fan speed and fault status',
        'Often also filter sign and operating hours',
        'What it usually hides — refrigerant-level detail, compressor internals, and the heat-recovery logic',
      ]},
      { type: 'h3', text: 'Integration pitfalls' },
      { type: 'bullets', items: [
        'Confirm the exposed points list before quoting — assume nothing; get it from the gateway documentation',
        'Gateways often cap how many indoor units they handle — count carefully against that limit',
        'Setpoint and mode write-back can behave differently per manufacturer — test it during commissioning',
        'The VRF keeps running if the BMS is offline — this is supervision, not control',
      ]},
      { type: 'callout', text: 'When scoping VRF integration, the gateway model and its exact points list are the whole job. A BMS spec that only says to integrate the VRF, without naming the gateway and its points, is an open-ended risk.' },
    ],
  },
];
